# Generated by Django 4.2.9 on 2024-03-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='menu',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='nlu',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='NLU',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='Stories',
        ),
    ]
