# Generated by Django 4.2.9 on 2024-03-22 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='chatbot_data.bot'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='chatbot_data.intent'),
        ),
        migrations.AlterField(
            model_name='expressionparameter',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='chatbot_data.entity'),
        ),
        migrations.AlterField(
            model_name='expressionparameter',
            name='expression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='chatbot_data.expression'),
        ),
        migrations.AlterField(
            model_name='expressionparameter',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='chatbot_data.intent'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='chatbot_data.bot'),
        ),
        migrations.AlterField(
            model_name='regex',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regexes', to='chatbot_data.bot'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='chatbot_data.bot'),
        ),
    ]
