# Generated by Django 4.2.9 on 2024-03-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0005_action_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_name', models.TextField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookups', to='chatbot_data.bot')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.TextField()),
                ('rule_steps', models.TextField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='chatbot_data.bot')),
            ],
        ),
        migrations.CreateModel(
            name='RegexVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField()),
                ('regex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='chatbot_data.regex')),
            ],
        ),
        migrations.CreateModel(
            name='LookupVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('lookup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='chatbot_data.lookup')),
            ],
        ),
    ]
