# Generated by Django 4.2.9 on 2024-03-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0006_lookup_rule_regexvariant_lookupvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regex',
            name='regex_pattern',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='regex_pattern',
        ),
    ]
