# Generated by Django 4.2.9 on 2024-03-24 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0007_remove_regex_regex_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
