# Generated by Django 4.2.9 on 2024-03-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0008_rule_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_config',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
    ]
