# Generated by Django 4.2.9 on 2024-03-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0009_action_action_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
