# Generated by Django 4.2.9 on 2024-04-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0010_alter_action_action_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='is_train',
            field=models.BooleanField(default=True),
        ),
    ]
