# Generated by Django 4.2.9 on 2024-04-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0011_expression_is_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.TextField()),
                ('session_id', models.TextField()),
                ('entities', models.TextField()),
                ('user_say', models.TextField()),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_data.bot')),
            ],
        ),
    ]
