# Generated by Django 4.2.9 on 2024-04-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0012_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='bot',
        ),
    ]
