# Generated by Django 4.2.9 on 2024-04-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0013_remove_history_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='chatlog_id',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
    ]
