# Generated by Django 4.2.9 on 2024-04-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0014_history_chatlog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='session_id',
        ),
    ]
