# Generated by Django 4.2.9 on 2024-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0015_remove_history_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='sender',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='entities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='intent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
