# Generated by Django 4.2.9 on 2024-04-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0016_history_response_history_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='sender',
            new_name='sender_id',
        ),
    ]
