# Generated by Django 4.2.9 on 2024-04-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0018_history_sender_name_history_slot_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.TextField()),
                ('sender_name', models.TextField()),
            ],
        ),
    ]
