# Generated by Django 4.2.9 on 2024-04-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0020_remove_history_sender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='chatlog_id',
        ),
    ]
