# Generated by Django 4.2.9 on 2024-04-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0021_remove_history_chatlog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='intent_ranking',
            field=models.TextField(blank=True, null=True),
        ),
    ]
