# Generated by Django 4.2.9 on 2024-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0022_history_intent_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='next_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
