# Generated by Django 4.2.9 on 2024-05-19 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0024_test_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='chart1_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='chart2_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_data.test'),
        ),
    ]
