# Generated by Django 4.2.9 on 2024-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0025_testresult_chart1_path_testresult_chart2_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('intent', 'Intent Test'), ('story', 'Story Test')], default=str, max_length=10),
            preserve_default=False,
        ),
    ]
