# Generated by Django 4.2.9 on 2024-06-16 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_data', '0027_alter_history_confidence_alter_history_entities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Bot', 'verbose_name_plural': 'Bots'},
        ),
        migrations.AlterModelOptions(
            name='chatuser',
            options={'verbose_name': 'Chat User', 'verbose_name_plural': 'Chat Users'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='expression',
            options={'verbose_name': 'Expression', 'verbose_name_plural': 'Expressions'},
        ),
        migrations.AlterModelOptions(
            name='expressionparameter',
            options={'verbose_name': 'Expression Parameter', 'verbose_name_plural': 'Expression Parameters'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'History', 'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterModelOptions(
            name='intent',
            options={'verbose_name': 'Intent', 'verbose_name_plural': 'Intents'},
        ),
        migrations.AlterModelOptions(
            name='lookup',
            options={'verbose_name': 'Lookup', 'verbose_name_plural': 'Lookups'},
        ),
        migrations.AlterModelOptions(
            name='lookupvariant',
            options={'verbose_name': 'Lookup Variant', 'verbose_name_plural': 'Lookup Variants'},
        ),
        migrations.AlterModelOptions(
            name='modelmodel',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='nlulog',
            options={'verbose_name': 'NLU Log', 'verbose_name_plural': 'NLU Logs'},
        ),
        migrations.AlterModelOptions(
            name='regex',
            options={'verbose_name': 'Regex', 'verbose_name_plural': 'Regexes'},
        ),
        migrations.AlterModelOptions(
            name='regexvariant',
            options={'verbose_name': 'Regex Variant', 'verbose_name_plural': 'Regex Variants'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Response', 'verbose_name_plural': 'Responses'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Rule', 'verbose_name_plural': 'Rules'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterModelOptions(
            name='synonym',
            options={'verbose_name': 'Synonym', 'verbose_name_plural': 'Synonyms'},
        ),
        migrations.AlterModelOptions(
            name='synonymvariant',
            options={'verbose_name': 'Synonym Variant', 'verbose_name_plural': 'Synonym Variants'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Test Result', 'verbose_name_plural': 'Test Results'},
        ),
        migrations.AlterField(
            model_name='action',
            name='action_config',
            field=models.TextField(blank=True, null=True, verbose_name='Action Config'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_name',
            field=models.TextField(verbose_name='Action Name'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('utter', 'UTTER'), ('action', 'ACTION'), ('form', 'FORM'), ('slot_set', 'SLOT_SET')], default='utter', max_length=10, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='action',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_data.bot', verbose_name='Bot'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_config',
            field=models.TextField(verbose_name='Bot Config'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_name',
            field=models.TextField(verbose_name='Bot Name'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='output_folder',
            field=models.TextField(verbose_name='Output Folder'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='sender_id',
            field=models.TextField(verbose_name='Sender ID'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='sender_name',
            field=models.TextField(verbose_name='Sender Name'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_data.bot', verbose_name='Bot'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation',
            field=models.TextField(verbose_name='Conversation'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='ip_address',
            field=models.TextField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='story',
            field=models.TextField(blank=True, null=True, verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='chatbot_data.bot', verbose_name='Bot'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_name',
            field=models.TextField(verbose_name='Entity Name'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='slot_data_type',
            field=models.TextField(verbose_name='Slot Data Type'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='expression_text',
            field=models.TextField(verbose_name='Expression Text'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='chatbot_data.intent', verbose_name='Intent'),
        ),
        migrations.AlterField(
            model_name='expression',
            name='is_train',
            field=models.BooleanField(default=True, verbose_name='Is Train'),
        ),
        migrations.AlterField(
            model_name='expressionparameter',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='chatbot_data.entity', verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='expressionparameter',
            name='expression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='chatbot_data.expression', verbose_name='Expression'),
        ),
        migrations.AlterField(
            model_name='expressionparameter',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='chatbot_data.intent', verbose_name='Intent'),
        ),
        migrations.AlterField(
            model_name='expressionparameter',
            name='parameter_end',
            field=models.IntegerField(verbose_name='Parameter End'),
        ),
        migrations.AlterField(
            model_name='expressionparameter',
            name='parameter_start',
            field=models.IntegerField(verbose_name='Parameter Start'),
        ),
        migrations.AlterField(
            model_name='expressionparameter',
            name='parameter_value',
            field=models.TextField(verbose_name='Parameter Value'),
        ),
        migrations.AlterField(
            model_name='history',
            name='confidence',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Confidence'),
        ),
        migrations.AlterField(
            model_name='history',
            name='entities',
            field=models.TextField(blank=True, default='[]', verbose_name='Entities'),
        ),
        migrations.AlterField(
            model_name='history',
            name='intent',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Intent'),
        ),
        migrations.AlterField(
            model_name='history',
            name='intent_ranking',
            field=models.TextField(blank=True, default='[]', verbose_name='Intent Ranking'),
        ),
        migrations.AlterField(
            model_name='history',
            name='next_action',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Next Action'),
        ),
        migrations.AlterField(
            model_name='history',
            name='response',
            field=models.TextField(blank=True, default='', verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='history',
            name='sender_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sender ID'),
        ),
        migrations.AlterField(
            model_name='history',
            name='slot_values',
            field=models.TextField(blank=True, default='{}', verbose_name='Slot Values'),
        ),
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user_say',
            field=models.TextField(blank=True, default='', verbose_name='User Say'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='chatbot_data.bot', verbose_name='Bot'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='intent_name',
            field=models.TextField(verbose_name='Intent Name'),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookups', to='chatbot_data.bot', verbose_name='Bot'),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='lookup_name',
            field=models.TextField(verbose_name='Lookup Name'),
        ),
        migrations.AlterField(
            model_name='lookupvariant',
            name='lookup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='chatbot_data.lookup', verbose_name='Lookup'),
        ),
        migrations.AlterField(
            model_name='lookupvariant',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='modelmodel',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_data.bot', verbose_name='Bot'),
        ),
        migrations.AlterField(
            model_name='modelmodel',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='modelmodel',
            name='local_path',
            field=models.TextField(verbose_name='Local Path'),
        ),
        migrations.AlterField(
            model_name='modelmodel',
            name='model_name',
            field=models.TextField(verbose_name='Model Name'),
        ),
        migrations.AlterField(
            model_name='modelmodel',
            name='server_path',
            field=models.TextField(verbose_name='Server Path'),
        ),
        migrations.AlterField(
            model_name='modelmodel',
            name='server_response',
            field=models.TextField(verbose_name='Server Response'),
        ),
        migrations.AlterField(
            model_name='modelmodel',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='nlulog',
            name='event_data',
            field=models.TextField(verbose_name='Event Data'),
        ),
        migrations.AlterField(
            model_name='nlulog',
            name='event_type',
            field=models.TextField(verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='nlulog',
            name='ip_address',
            field=models.TextField(verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='nlulog',
            name='query',
            field=models.TextField(verbose_name='Query'),
        ),
        migrations.AlterField(
            model_name='nlulog',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='regex',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regexes', to='chatbot_data.bot', verbose_name='Bot'),
        ),
        migrations.AlterField(
            model_name='regex',
            name='regex_name',
            field=models.TextField(verbose_name='Regex Name'),
        ),
        migrations.AlterField(
            model_name='regexvariant',
            name='pattern',
            field=models.TextField(verbose_name='Pattern'),
        ),
        migrations.AlterField(
            model_name='regexvariant',
            name='regex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='chatbot_data.regex', verbose_name='Regex'),
        ),
        migrations.AlterField(
            model_name='response',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_data.action', verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_text',
            field=models.TextField(verbose_name='Response Text'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_type',
            field=models.TextField(verbose_name='Response Type'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='chatbot_data.bot', verbose_name='Bot'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_name',
            field=models.TextField(verbose_name='Rule Name'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_steps',
            field=models.TextField(verbose_name='Rule Steps'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='setting_name',
            field=models.TextField(unique=True, verbose_name='Setting Name'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='setting_value',
            field=models.TextField(verbose_name='Setting Value'),
        ),
        migrations.AlterField(
            model_name='story',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_data.bot', verbose_name='Bot'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.TextField(verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_name',
            field=models.TextField(verbose_name='Story Name'),
        ),
        migrations.AlterField(
            model_name='story',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='chatbot_data.bot', verbose_name='Bot'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='synonym_reference',
            field=models.TextField(verbose_name='Synonym Reference'),
        ),
        migrations.AlterField(
            model_name='synonymvariant',
            name='synonym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_data.synonym', verbose_name='Synonym'),
        ),
        migrations.AlterField(
            model_name='synonymvariant',
            name='synonym_value',
            field=models.TextField(verbose_name='Synonym Value'),
        ),
        migrations.AlterField(
            model_name='test',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('intent', 'Intent Test'), ('story', 'Story Test')], max_length=10, verbose_name='Test Type'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='chart1_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chart 1 Path'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='chart2_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chart 2 Path'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.JSONField(verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_data.test', verbose_name='Test'),
        ),
    ]
