INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Lãnh đạo cơ quan Đảng Cộng sản Việt Nam cấp trung ương và địa phương (chuyên trách)','','10','','',''),
	 ('Lãnh đạo cơ quan Đảng Cộng sản Việt Nam cấp trung ương (chuyên trách)','','','101','',''),
	 ('Tổng Bí thư, Thường trực Ban Bí thư, Ban Bí thư, Ủy viên Bộ Chính trị, Ủy viên Ban Chấp hành Trung ương Đảng','','','','1011','10110'),
	 ('Bí thư, Phó Bí thư Đảng ủy cơ quan trung ương','','','','1012','10120'),
	 ('Bí thư, Phó Bí thư Đảng ủy khối trực thuộc trung ương','','','','1013','10130'),
	 ('Trưởng ban, Phó Trưởng ban Đảng và tương đương thuộc cấp trung ương ','','','','1014','10140'),
	 ('Trợ lý Ủy viên Bộ Chính trị ','','','','1015','10150'),
	 ('Vụ trưởng, Phó Vụ trưởng và tương đương','','','','1016','10160'),
	 ('Lãnh đạo cơ quan Đảng Cộng sản Việt Nam cấp tỉnh (chuyên trách)','','','102','',''),
	 ('Bí thư Tỉnh ủy, Phó Bí thư Tỉnh ủy, Ủy viên Ban Chấp hành Đảng bộ cấp tỉnh','','','','1021','10210');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Bí thư, Phó Bí thư Đảng ủy sở, ban, ngành cấp tỉnh','','','','1022','10220'),
	 ('Bí thư, Phó Bí thư Đảng ủy khối cơ quan cấp tỉnh','','','','1023','10230'),
	 ('Trưởng ban, Phó Trưởng ban Đảng và tương đương thuộc cấp tỉnh','','','','1024','10240'),
	 ('Lãnh đạo Đảng Cộng sản Việt Nam cấp huyện (chuyên trách)','','','103','',''),
	 ('Bí thư Huyện ủy, Phó Bí thư Huyện ủy, Ủy viên Ban Chấp hành Đảng bộ cấp huyện','','','','1031','10310'),
	 ('Bí thư, Phó Bí thư Đảng ủy ban, ngành cấp huyện','','','','1032','10320'),
	 ('Trưởng ban, Phó Trưởng ban Đảng và tương đương thuộc cấp huyện','','','','1033','10330'),
	 ('Lãnh đạo Đảng Cộng sản Việt Nam cấp xã (chuyên trách)','','','104','',''),
	 ('Bí thư, Phó Bí thư Đảng ủy cấp xã','','','','1040','10400'),
	 ('Lãnh đạo Đảng Cộng sản Việt Nam tại doanh nghiệp và các tổ chức sự nghiệp (chuyên trách)','','','105','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Bí thư, Phó Bí thư Đảng ủy','','','','1050','10500'),
	 ('Lãnh đạo, quản lý của Quốc hội, Văn phòng Quốc hội và Văn phòng Chủ tịch nước (chuyên trách)','','11','','',''),
	 ('Lãnh đạo, quản lý của Quốc hội, Văn phòng Quốc hội (chuyên trách)','','','111','',''),
	 ('Chủ tịch Quốc hội, Phó Chủ tịch Quốc hội, Ủy viên thường vụ Quốc hội ','','','','1111','11110'),
	 ('Chủ nhiệm, Phó Chủ nhiệm Ủy ban và tương đương làm việc tại Văn phòng Quốc hội','','','','1112','11120'),
	 ('Vụ trưởng, Phó Vụ trưởng và tương đương','','','','1113','11130'),
	 ('Lãnh đạo, quản lý của Nhà nước, Văn phòng Chủ tịch nước (chuyên trách)','','','112','',''),
	 ('Chủ tịch nước, Phó Chủ tịch nước','','','','1121','11210'),
	 ('Chủ nhiệm, Phó Chủ nhiệm tương đương Bộ trưởng, Thứ trưởng và tương đương làm việc tại Văn phòng Chủ tịch nước','','','','1122','11220'),
	 ('Vụ trưởng, Phó Vụ trưởng và tương đương','','','','1123','11230');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Lãnh đạo, quản lý của Chính phủ, Văn phòng Chính phủ, các bộ, ngành và tương đương thuộc Chính phủ (chuyên trách)','','12','','',''),
	 ('Lãnh đạo, quản lý của Chính phủ, Văn phòng Chính phủ (chuyên trách)','','','121','',''),
	 ('Thủ tướng, Phó Thủ tướng Chính phủ','','','','1211','12110'),
	 ('Chủ nhiệm, Phó Chủ nhiệm và tương đương làm việc tại Văn phòng Chính phủ','','','','1212','12120'),
	 ('Vụ trưởng, Phó Vụ trưởng và tương đương','','','','1213','12130'),
	 ('Lãnh đạo, quản lý bộ, ngành và tương đương thuộc Chính phủ (chuyên trách)','','','122','',''),
	 ('Bộ trưởng, Thứ trưởng và tương đương của các bộ, ngành, các cơ quan ngang bộ, các cơ quan thuộc Chính phủ','','','','1221','12210'),
	 ('Trợ lý Bộ trưởng Bộ Ngoại giao','','','','1222','12220'),
	 ('Vụ trưởng, Phó Vụ trưởng, Trưởng ban, Phó Trưởng ban và tương đương','','','','1223','12230'),
	 ('Lãnh đạo, quản lý tổng cục thuộc bộ (chuyên trách)','','','123','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Tổng cục trưởng, Phó Tổng cục trưởng và tương đương ','','','','1231','12310'),
	 ('Vụ trưởng, Phó Vụ trưởng, Trưởng ban, Phó Trưởng ban và tương đương','','','','1232','12320'),
	 ('Lãnh đạo, quản lý của Tòa án nhân dân và Viện Kiểm sát nhân dân (chuyên trách)','','13','','',''),
	 ('Lãnh đạo, quản lý của Tòa án nhân dân tối cao và cấp cao và Viện Kiểm sát nhân dân tối cao và cấp cao (chuyên trách)','','','131','',''),
	 ('Chánh án, Phó Chánh án Tòa án nhân dân tối cao và cấp cao; Viện trưởng, Phó Viện trưởng Viện Kiểm sát nhân dân tối cao và cấp cao','','','','1311','13110'),
	 ('Vụ trưởng, Phó Vụ trưởng và tương đương làm việc ở Tòa án nhân dân tối cao và cấp cao và Viện Kiểm sát nhân dân tối cao và cấp cao','','','','1312','13120'),
	 ('Lãnh đạo, quản lý của Tòa án nhân dân và Viện Kiểm sát nhân dân ở địa phương (chuyên trách)','','','132','',''),
	 ('Chánh án, Phó Chánh án Tòa án nhân dân; Viện trưởng, Phó Viện trưởng Viện Kiểm sát nhân dân cấp tỉnh','','','','1321','13210'),
	 ('Chánh án, Phó Chánh án Tòa án nhân dân cấp huyện','','','','1322','13220'),
	 ('Lãnh đạo, quản lý của Tòa án khác (trừ Tòa án Quân sự) do luật định (chuyên trách)','','','133','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Chánh án, Phó Chánh án Tòa án khác (trừ Tòa án Quân sự) do luật định','','','','1330','1330'),
	 ('Lãnh đạo, quản lý của Hội đồng nhân dân và Ủy ban nhân dân địa phương (kể cả các cơ quan chuyên môn ở địa phương, trừ tư pháp và đoàn thể) (chuyên trách)','','14','','',''),
	 ('Lãnh đạo, quản lý của Hội đồng nhân dân (chuyên trách)','','','141','',''),
	 ('Chủ tịch, Phó Chủ tịch và Thường trực Hội đồng nhân dân cấp tỉnh','','','','1411','14110'),
	 ('Trưởng ban, Phó Trưởng ban và tương đương trong các cơ quan của Hội đồng nhân dân cấp tỉnh','','','','1412','14120'),
	 ('Nhà vật lý học và thiên văn học','','','','2111','21110'),
	 ('Chủ tịch, Phó Chủ tịch và Thường trực Hội đồng nhân dân cấp huyện','','','','1413','14130'),
	 ('Trưởng ban, Phó Trưởng ban và tương đương trong các cơ quan của Hội đồng nhân dân cấp huyện','','','','1414','14140'),
	 ('Chủ tịch, Phó Chủ tịch Hội đồng nhân dân cấp xã','','','','1415','14150'),
	 ('Lãnh đạo, quản lý của Ủy ban nhân dân (kể cả các cơ quan chuyên môn) (chuyên trách)','','','142','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Chủ tịch, Phó Chủ tịch và Ủy viên thường trực Ủy ban nhân dân cấp tỉnh','','','','1421','14210'),
	 ('Chủ tịch, Phó Chủ tịch và Ủy viên thường trực Ủy ban nhân dân cấp huyện','','','','1422','14220'),
	 ('Chủ tịch, Phó Chủ tịch Ủy ban nhân dân cấp xã','','','','1423','14230'),
	 ('Trưởng ngành, Phó Trưởng ngành, ban, sở và tương đương của các cơ quan chuyên môn cấp tỉnh','','','','1424','14240'),
	 ('Trưởng ngành, Phó Trưởng ngành, ban và tương đương của các cơ quan chuyên môn cấp huyện','','','','1425','14250'),
	 ('Lãnh đạo, quản lý khối đoàn thể; Mặt trận Tổ quốc, Liên đoàn Lao động, Hội Phụ nữ, Hội Nông dân, Đoàn Thanh niên Cộng sản Hồ Chí Minh, Hội Cựu chiến binh (chuyên trách)','','15','','',''),
	 ('Lãnh đạo, quản lý khối đoàn thể (trừ Liên đoàn Lao động) (chuyên trách)','','','151','',''),
	 ('Chủ tịch, Phó Chủ tịch','','','','1511','15110'),
	 ('Ủy viên cấp trung ương','','','','1512','15120'),
	 ('Vụ trưởng, Phó Vụ trưởng và tương đương cấp trung ương','','','','1513','15130');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Ủy viên cấp tỉnh','','','','1514','15140'),
	 ('Ủy viên cấp huyện','','','','1515','15150'),
	 ('Lãnh đạo, quản lý Liên đoàn Lao động (chuyên trách)','','','152','',''),
	 ('Chủ tịch, Phó Chủ tịch','','','','1521','15210'),
	 ('Ủy viên của Tổng Liên đoàn Lao động Việt Nam','','','','1522','15220'),
	 ('Vụ trưởng, Phó Vụ trưởng và tương đương của Tổng Liên đoàn Lao động Việt Nam','','','','1523','15230'),
	 ('Ủy viên trở lên của Liên đoàn Lao động cấp tỉnh','','','','1524','15240'),
	 ('Ủy viên trở lên của Liên đoàn Lao động cấp huyện','','','','1525','15250'),
	 ('Chủ tịch, Phó Chủ tịch tổ chức công đoàn cơ quan bộ, ngành ở trung ương','','','','1526','15260'),
	 ('Chủ tịch, Phó Chủ tịch tổ chức công đoàn doanh nghiệp và các tổ chức sự nghiệp','','','','1527','15270');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà quản lý của Tổ chức nghiệp chủ, nhân đạo và vì quyền lợi đặc thù khác (chuyên trách)','','16','','',''),
	 ('Nhà quản lý của Tổ chức nghiệp chủ (chuyên trách)','','','161','',''),
	 ('Chủ tịch, Phó Chủ tịch ','','','','1610','16100'),
	 ('Nhà quản lý của Tổ chức nhân đạo và vì quyền lợi đặc thù khác (chuyên trách)','','','162','',''),
	 ('Chủ tịch, Phó Chủ tịch ','','','','1620','16200'),
	 ('Nhà quản lý của các cơ quan tập đoàn, tổng công ty và tương đương (chuyên trách)','','17','','',''),
	 ('Chủ tịch, Phó Chủ tịch Hội đồng quản trị, Tổng giám đốc doanh nghiệp, Phó Tổng giám đốc doanh nghiệp, Chủ tịch, Phó Chủ tịch Hội đồng trường, Hiệu trưởng, Phó Hiệu trưởng trường đại học lớn và tương đương (chuyên trách)','','','171','1710','17100'),
	 ('Giám đốc, Phó Giám đốc của các đơn vị sản xuất và triển khai thuộc cơ quan tập đoàn, tổng công ty, trường đại học lớn và tương đương (chuyên trách)','','','172','',''),
	 ('Nông nghiệp, lâm nghiệp và thủy sản','','','','1721','17210'),
	 ('Khai khoáng, công nghiệp chế biến, chế tạo, sản xuất và phân phối điện, khí đốt, nước nóng, hơi nước và điều hòa không khí','','','','1722','17220');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Xây dựng','','','','1723','17230'),
	 ('Bán buôn, bán lẻ','','','','1724','17240'),
	 ('Dịch vụ lưu trú và ăn uống','','','','1725','17250'),
	 ('Vận tải, kho bãi; Thông tin và truyền thông','','','','1726','17260'),
	 ('Dịch vụ kinh doanh','','','','1727','17270'),
	 ('Dịch vụ cá nhân và cộng đồng','','','','1728','17280'),
	 ('Các đơn vị sản xuất và dịch vụ còn lại chưa được phân vào đâu','','','','1729','17290'),
	 ('Giám đốc, Phó Giám đốc các đơn vị quản lý thuộc cơ quan Liên hiệp, Tổng công ty, trường đại học lớn và tương đương (chuyên trách)','','','173','',''),
	 ('Tài chính, kế toán, quản trị hành chính','','','','1731','17310'),
	 ('Tổ chức nhân sự và mối quan hệ công nghệ','','','','1732','17320');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Bán hàng và tiếp thị','','','','1733','17330'),
	 ('Quảng cáo và các vấn đề liên quan đến công chúng','','','','1734','17340'),
	 ('Cung ứng và phân phối','','','','1735','17350'),
	 ('Dịch vụ và tính toán','','','','1736','17360'),
	 ('Nghiên cứu và phát triển','','','','1737','17370'),
	 ('Các đơn vị khác chưa được phân vào đâu','','','','1739','17390'),
	 ('Giám đốc, Phó Giám đốc công ty, doanh nghiệp, xí nghiệp, hợp tác xã; Hiệu trưởng, Phó Hiệu trưởng trường nhỏ và tương đương (chuyên trách)','','','174','',''),
	 ('Nông nghiệp, lâm nghiệp và thủy sản','','','','1741','17410'),
	 ('Khai khoáng, công nghiệp chế biến, chế tạo, sản xuất và phân phối điện, khí đốt, nước nóng, hơi nước và điều hòa không khí','','','','1742','17420'),
	 ('Xây dựng','','','','1743','17430');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Bán buôn, bán lẻ','','','','1744','17440'),
	 ('Dịch vụ lưu trú và ăn uống ','','','','1745','17450'),
	 ('Vận tải kho bãi; Thông tin và truyền thông','','','','1746','17460'),
	 ('Dịch vụ kinh doanh','','','','1747','17470'),
	 ('Dịch vụ cá nhân và cộng đồng','','','','1748','17480'),
	 ('Các đơn vị sản xuất và dịch vụ còn lại chưa được phân vào đâu','','','','1749','17490'),
	 ('Nhà chuyên môn bậc cao ','2','','','',''),
	 ('Nhà chuyên môn trong lĩnh vực khoa học và kỹ thuật','','21','','',''),
	 ('Nhà chuyên môn về khoa học trái đất và vật lý','','','211','',''),
	 ('Đầu bếp','','','512','5120','51200');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà khí tượng học','','','','2112','21120'),
	 ('Nhà hóa học','','','','2113','21130'),
	 ('Nhà địa chất, địa vật lý','','','','2114','21140'),
	 ('Nhà toán học, nhà thống kê','','','212','',''),
	 ('Nhà toán học','','','','2121',''),
	 ('Nhà toán học','','','','','21211'),
	 ('Nhà phân tích nghiên cứu hoạt động','','','','','21212'),
	 ('Nhà thống kê','','','','2122','21220'),
	 ('Nhà chuyên môn về khoa học sự sống','','','213','',''),
	 ('Nhà sinh vật học, thực vật học, động vật học và các chuyên môn liên quan','','','','2131','21310');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà tư vấn nông, lâm nghiệp và thủy sản','','','','2132',''),
	 ('Nhà trồng trọt','','','','','21321'),
	 ('Nhà tư vấn làm vườn','','','','','21322'),
	 ('Nhà bệnh học thực vật','','','','','21323'),
	 ('Nhà khoa học đất đai','','','','','21324'),
	 ('Nhà chăn nuôi','','','','','21325'),
	 ('Nhà nuôi cấy tế bào động vật','','','','','21326'),
	 ('Nhà nuôi cấy mô thực vật','','','','','21327'),
	 ('Nhà tư vấn nuôi trồng thủy sản','','','','','21328'),
	 ('Các chuyên gia nông, lâm, thủy sản khác','','','','','21329');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà chuyên môn về bảo vệ môi trường','','','','2133','21330'),
	 ('Nhà chuyên môn về kỹ thuật (trừ kỹ thuật điện)','','','214','',''),
	 ('Kỹ sư công nghiệp chế biến, chế tạo','','','','2141','21410'),
	 ('Kỹ sư xây dựng','','','','2142','21420'),
	 ('Kỹ sư môi trường','','','','2143','21430'),
	 ('Kỹ sư cơ học, cơ khí','','','','2144','21440'),
	 ('Kỹ sư hóa học','','','','2145','21450'),
	 ('Kỹ sư khai thác mỏ, luyện kim và các nghề liên quan','','','','2146','21460'),
	 ('Kỹ sư kỹ thuật khác chưa được phân vào đâu','','','','2149','21490'),
	 ('Kỹ sư kỹ thuật điện','','','215','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Kỹ sư điện','','','','2151','21510'),
	 ('Kỹ sư điện tử','','','','2152','21520'),
	 ('Kỹ sư viễn thông','','','','2153','21530'),
	 ('Kiến trúc sư, nhà quy hoạch, khảo sát và thiết kế','','','216','',''),
	 ('Kiến trúc sư xây dựng','','','','2161','21610'),
	 ('Kiến trúc sư cảnh quan','','','','2162','21620'),
	 ('Nhà thiết kế sản phẩm và may mặc','','','','2163',''),
	 ('Nhà thiết kế trang phục/thời trang, phụ kiện','','','','','21631'),
	 ('Nhà thiết kế công nghiệp và sản phẩm','','','','','21632'),
	 ('Nhà quy hoạch đô thị và giao thông','','','','2164','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà quy hoạch đô thị ','','','','','21641'),
	 ('Nhà quy hoạch giao thông khác','','','','','21649'),
	 ('Nhà vẽ bản đồ và khảo sát hiện trường','','','','2165',''),
	 ('Nhà khảo sát chung','','','','','21651'),
	 ('Nhà khảo sát đất','','','','','21652'),
	 ('Nhà khảo sát thủy văn','','','','','21653'),
	 ('Người vẽ bản đồ','','','','','21654'),
	 ('Nhà khảo sát và vẽ bản đồ khác','','','','','21659'),
	 ('Nhà thiết kế đồ họa và truyền thông đa phương tiện','','','','2166','21660'),
	 ('Nhà chuyên môn về sức khỏe','','22','','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Bác sỹ y khoa','','','221','',''),
	 ('Bác sỹ đa khoa','','','','2211','22110'),
	 ('Bác sỹ chuyên khoa','','','','2212',''),
	 ('Bác sỹ tim mạch','','','','','22121'),
	 ('Bác sỹ da liễu','','','','','22122'),
	 ('Bác sỹ tiêu hóa','','','','','22123'),
	 ('Bác sỹ nội khoa','','','','','22124'),
	 ('Bác sỹ ung bướu','','','','','22125'),
	 ('Bác sỹ nhi khoa','','','','','22126'),
	 ('Bác sỹ hô hấp','','','','','22127');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Bác sỹ tâm thần','','','','','22128'),
	 ('Bác sỹ chuyên khoa khác','','','','','22129'),
	 ('Y tá/Điều dưỡng (cao cấp) và hộ sinh (cao cấp)','','','222','',''),
	 ('Y tá/Điều dưỡng (cao cấp)','','','','2221','22210'),
	 ('Hộ sinh (cao cấp)','','','','2222','22220'),
	 ('Nhà chuyên môn về y học cổ truyền và hỗ trợ','','','223','2230','22300'),
	 ('Bác sỹ phụ tá','','','224','2240','22400'),
	 ('Bác sỹ thú y','','','225','2250','22500'),
	 ('Nhà chuyên môn về sức khỏe khác','','','226','',''),
	 ('Bác sỹ răng - hàm - mặt','','','','2261','22610');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Dược sỹ','','','','2262',''),
	 ('Dược sỹ sản xuất thuốc','','','','','22621'),
	 ('Dược sỹ khác','','','','','22629'),
	 ('Nhà chuyên môn về vệ sinh môi trường và bệnh nghề nghiệp','','','','2263','22630'),
	 ('Nhà chuyên môn về vật lý trị liệu','','','','2264','22640'),
	 ('Nhà chuyên môn về dinh dưỡng','','','','2265','22650'),
	 ('Bác sỹ thính học và đặc trị các khuyết tật về ngôn ngữ','','','','2266','22660'),
	 ('Nhà chuyên môn về thị lực và nhãn khoa','','','','2267','22670'),
	 ('Nhà chuyên môn khác về sức khỏe chưa được phân vào đâu','','','','2269','22690'),
	 ('Nhà chuyên môn về giảng dạy','','23','','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Giảng viên cao đẳng, đại học và cao học','','','231','',''),
	 ('Giảng viên đại học và cao học','','','','2311','23110'),
	 ('Giảng viên cao đẳng','','','','2312','23120'),
	 ('Giáo viên trung cấp','','','232','2320','23200'),
	 ('Giáo viên trung học ','','','233','',''),
	 ('Giáo viên trung học phổ thông (cấp III)','','','','2331','23310'),
	 ('Giáo viên trung học cơ sở (cấp II)','','','','2332','23320'),
	 ('Giáo viên tiểu học và mầm non','','','234','',''),
	 ('Giáo viên tiểu học (cấp I)','','','','2341','23410'),
	 ('Giáo viên mầm non','','','','2342','23420');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà chuyên môn giảng dạy khác chưa được phân vào đâu ','','','239','',''),
	 ('Chuyên gia về phương pháp giáo dục','','','','2391','23910'),
	 ('Giáo viên theo các nhu cầu đặc biệt','','','','2392','23920'),
	 ('Giáo viên ngôn ngữ khác','','','','2393','23930'),
	 ('Giáo viên âm nhạc khác','','','','2394','23940'),
	 ('Giáo viên nghệ thuật khác','','','','2395','23950'),
	 ('Giáo viên công nghệ thông tin','','','','2396','23960'),
	 ('Nhà chuyên môn giảng dạy khác chưa được phân vào đâu','','','','2399','23990'),
	 ('Nhà chuyên môn về kinh doanh và quản lý','','24','','',''),
	 ('Nhà chuyên môn về tài chính','','','241','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Kế toán và các nhà chuyên môn có liên quan','','','','2411',''),
	 ('Kế toán (trừ kế toán thuế)','','','','','24111'),
	 ('Kiểm toán','','','','','24112'),
	 ('Kế toán thuế','','','','','24113'),
	 ('Nhà tư vấn tài chính và đầu tư','','','','2412','24120'),
	 ('Nhà phân tích tài chính và các nhà chuyên môn có liên quan','','','','2413',''),
	 ('Nhà phân tích tài chính','','','','','24131'),
	 ('Nhà phân tích rủi ro','','','','','24132'),
	 ('Nhà quản lý quỹ đầu tư','','','','','24133'),
	 ('Nhà quản lý quỹ ủy thác','','','','','24134');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà phân tích tài chính và các nhà chuyên môn có liên quan khác','','','','','24139'),
	 ('Nhà chuyên môn về quản trị','','','242','',''),
	 ('Nhà phân tích tổ chức và quản lý','','','','2421','24210'),
	 ('Nhà chuyên môn về quản trị chính sách','','','','2422','24220'),
	 ('Nhà chuyên môn về nhân sự và nghề nghiệp','','','','2423','24230'),
	 ('Nhà chuyên môn về đào tạo và phát triển nhân viên','','','','2424','24240'),
	 ('Nhà chuyên môn về bán hàng, tiếp thị và quan hệ công chúng','','','243','',''),
	 ('Nhà chuyên môn về quảng cáo và tiếp thị','','','','2431','24310'),
	 ('Nhà chuyên môn về quan hệ công chúng','','','','2432','24320'),
	 ('Nhà chuyên môn về bán hàng hóa kỹ thuật và y tế (không bao gồm công nghệ thông tin và truyền thông) ','','','','2433','24330');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà chuyên môn về bán hàng hóa trong lĩnh vực công nghệ thông tin và truyền thông ','','','','2434','24340'),
	 ('Nhà chuyên môn điều tiết của Chính phủ','','','244','',''),
	 ('Nhà chuyên môn về hải quan của Chính phủ','','','','2441','24410'),
	 ('Nhà chuyên môn về thuế của Chính phủ','','','','2442','24420'),
	 ('Nhà chuyên môn về trợ cấp xã hội của Chính phủ','','','','2443','24430'),
	 ('Nhà chuyên môn về cấp phép của Chính phủ','','','','2444','24440'),
	 ('Kiểm lâm','','','','2445','24450'),
	 ('Nhà ngoại giao','','','','2446','24460'),
	 ('Nhà chuyên môn điều tiết của Chính phủ khác chưa được phân vào đâu','','','','2449','24490'),
	 ('Nhà chuyên môn trong lĩnh vực công nghệ thông tin và truyền thông','','25','','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà chuyên môn về phân tích và phát triển phần mềm và các ứng dụng','','','251','',''),
	 ('Nhà phân tích hệ thống','','','','2511',''),
	 ('Nhà phân tích/thiết kế hệ thống','','','','','25111'),
	 ('Tư vấn quy trình kinh doanh công nghệ thông tin/phân tích kinh doanh','','','','','25112'),
	 ('Nhà kiến trúc giải pháp/doanh nghiệp','','','','','25113'),
	 ('Nhà phát triển phần mềm','','','','2512','25120'),
	 ('Nhà phát triển web và truyền thông đa phương tiện','','','','2513','25130'),
	 ('Nhà lập trình các ứng dụng','','','','2514','25140'),
	 ('Nhà chuyên môn về phát triển phần mềm ứng dụng và nhà phân tích chưa được phân vào đâu','','','','2519','25190'),
	 ('Nhà chuyên môn về cơ sở dữ liệu và mạng','','','252','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà quản trị và thiết kế cơ sở dữ liệu','','','','2521',''),
	 ('Nhà quản trị cơ sở dữ liệu','','','','','25211'),
	 ('Nhà thiết kế cơ sở dữ liệu','','','','','25212'),
	 ('Nhà quản trị hệ thống','','','','2522','25220'),
	 ('Nhà chuyên môn về mạng máy tính','','','','2523','25230'),
	 ('Nhà chuyên môn về cơ sở dữ liệu và mạng chưa được phân vào đâu','','','','2529',''),
	 ('Nhà khoa học dữ liệu','','','','','25291'),
	 ('Nhà chuyên môn về mạng và cơ sở dữ liệu','','','','','25292'),
	 ('Nhà chuyên môn về luật pháp, văn hóa, xã hội ','','26','','',''),
	 ('Nhà chuyên môn về luật','','','261','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Luật sư','','','','2611',''),
	 ('Luật sư tham gia tố tụng','','','','','26111'),
	 ('Luật sư tư vấn pháp luật','','','','','26112'),
	 ('Luật sư khác','','','','','26119'),
	 ('Thẩm phán','','','','2612','26120'),
	 ('Nhà chuyên môn về luật khác chưa được phân vào đâu','','','','2619',''),
	 ('Công chứng viên','','','','','26191'),
	 ('Thừa phát lại','','','','','26192'),
	 ('Nhà chuyên môn về luật khác chưa được phân vào đâu','','','','','26199'),
	 ('Thủ thư, nhà chuyên môn về lưu trữ và giám tuyển ','','','262','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà chuyên môn về lưu trữ và giám tuyển','','','','2621','26210'),
	 ('Thủ thư và các nhà chuyên môn về thông tin liên quan','','','','2622','26220'),
	 ('Nhà chuyên môn về xã hội và tôn giáo','','','263','',''),
	 ('Nhà kinh tế học ','','','','2631','26310'),
	 ('Nhà xã hội học, nhà nhân chủng học và các nghề có liên quan','','','','2632','26320'),
	 ('Nhà triết học, sử học và khoa học chính trị','','','','2633','26330'),
	 ('Nhà tâm lý học','','','','2634','26340'),
	 ('Nhà chuyên môn về tư vấn và công tác xã hội ','','','','2635','26350'),
	 ('Nhà chuyên môn về tôn giáo','','','','2636','26360'),
	 ('Nhà văn, nhà báo và nhà ngôn ngữ học','','','264','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà văn và nghề có liên quan  ','','','','2641',''),
	 ('Nhà văn','','','','','26411'),
	 ('Người viết kịch bản ','','','','','26412'),
	 ('Người viết lời quảng cáo','','','','','26413'),
	 ('Người viết tài liệu kỹ thuật','','','','','26414'),
	 ('Nhà biên tập kịch bản và kết nối','','','','','26415'),
	 ('Biên tập viên xuất bản phẩm','','','','','26416'),
	 ('Người viết khác và các nghề liên quan','','','','','26419'),
	 ('Nhà báo, biên tập viên','','','','2642',''),
	 ('Nhà báo','','','','','26421');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Biên tập viên','','','','','26422'),
	 ('Nhà biên dịch, phiên dịch và nhà ngôn ngữ khác','','','','2643',''),
	 ('Phiên dịch','','','','','26431'),
	 ('Biên dịch','','','','','26432'),
	 ('Nhà ngôn ngữ khác','','','','','26439'),
	 ('Nghệ sỹ sáng tạo và trình diễn','','','265','',''),
	 ('Nghệ sỹ hình ảnh','','','','2651',''),
	 ('Nhà điêu khắc','','','','','26511'),
	 ('Hoạ sỹ','','','','','26512'),
	 ('Người vẽ tranh hoạt họa','','','','','26513');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nghệ sỹ hình ảnh khác','','','','','26519'),
	 ('Nhạc công, ca sỹ và nhạc sỹ','','','','2652',''),
	 ('Nhạc công','','','','','26521'),
	 ('Nhạc sỹ','','','','','26522'),
	 ('Nhạc trưởng/giám đốc dàn nhạc/ban nhạc/dàn hợp xướng','','','','','26523'),
	 ('Ca sỹ','','','','','26524'),
	 ('Nhạc công, ca sỹ và nhạc sỹ khác','','','','','26529'),
	 ('Vũ công và biên đạo múa','','','','2653','26530'),
	 ('Đạo diễn, nhà sản xuất phim, sân khấu và các nghề liên quan','','','','2654','26540'),
	 ('Diễn viên','','','','2655','26550');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Phát thanh viên trên đài, truyền hình và các phương tiện truyền thông đại chúng khác','','','','2656','26560'),
	 ('Nghệ sỹ sáng tạo và trình diễn liên quan khác chưa được phân vào đâu','','','','2659','26590'),
	 ('Nhà chuyên môn bậc trung','3','','','',''),
	 ('Kỹ thuật viên khoa học và kỹ thuật ','','31','','',''),
	 ('Kỹ thuật viên khoa học vật lý và kỹ thuật ','','','311','',''),
	 ('Kỹ thuật viên khoa học hóa học và vật lý ','','','','3111',''),
	 ('Kỹ thuật viên hóa học','','','','','31111'),
	 ('Kỹ thuật viên vật lí','','','','','31112'),
	 ('Kỹ thuật viên hóa học và vật lí khác','','','','','31119'),
	 ('Kỹ thuật viên kỹ thuật xây dựng','','','','3112','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Kỹ thuật viên xây dựng dân dụng','','','','','31121'),
	 ('Kỹ thuật viên kết cấu','','','','','31122'),
	 ('Kỹ thuật viên xây dựng công trình','','','','','31123'),
	 ('Kỹ thuật viên khảo sát đất đai','','','','','31124'),
	 ('Kỹ thuật viên xây dựng dân dụng khác','','','','','31129'),
	 ('Kỹ thuật viên kỹ thuật điện ','','','','3113',''),
	 ('Kỹ thuật viên điện dân dụng chung','','','','','31131'),
	 ('Kỹ thuật viên điện dân dụng cao tần','','','','','31132'),
	 ('Kỹ thuật viên điện dân dụng khác','','','','','31139'),
	 ('Kỹ thuật viên kỹ thuật điện tử','','','','3114','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Kỹ thuật viên điện tử dân dụng (chung)','','','','','31141'),
	 ('Kỹ thuật viên bán dẫn','','','','','31142'),
	 ('Kỹ thuật viên thiết bị ghi âm, ghi hình','','','','','31143'),
	 ('Kỹ thuật viên thiết bị đo đạc ','','','','','31144'),
	 ('Kỹ thuật viên điện tử dân dụng khác','','','','','31149'),
	 ('Kỹ thuật viên kỹ thuật cơ khí','','','','3115',''),
	 ('Kỹ thuật viên kỹ thuật cơ khí chung','','','','','31151'),
	 ('Kỹ thuật viên cơ khí hàng không','','','','','31152'),
	 ('Kỹ thuật viên máy tự động','','','','','31153'),
	 ('Kỹ thuật viên điều hòa không khí/điện lạnh','','','','','31154');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Kỹ thuật viên máy móc, công cụ','','','','','31155'),
	 ('Người thiết kế khuôn/công cụ','','','','','31156'),
	 ('Kỹ thuật viên cơ khí dân dụng khác','','','','','31159'),
	 ('Kỹ thuật viên kỹ thuật hóa học','','','','3116','31160'),
	 ('Kỹ thuật viên khai thác mỏ và luyện kim','','','','3117','31170'),
	 ('Kỹ thuật viên phác thảo kỹ thuật','','','','3118','31180'),
	 ('Kỹ thuật viên khoa học vật lý và kỹ thuật chưa được phân vào đâu','','','','3119','31190'),
	 ('Giám sát viên khai thác mỏ, sản xuất và xây dựng','','','312','',''),
	 ('Giám sát viên khai thác mỏ','','','','3121','31210'),
	 ('Giám sát viên sản xuất','','','','3122','31220');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Giám sát viên xây dựng','','','','3123','31230'),
	 ('Kỹ thuật viên kiểm soát, vận hành và điều khiển quy trình','','','313','',''),
	 ('Người vận hành trạm hoặc nhà máy phát điện','','','','3131','31310'),
	 ('Người vận hành lò đốt rác và nhà máy xử lý nước','','','','3132','31320'),
	 ('Kiểm soát viên nhà máy xử lý hoá chất','','','','3133','31330'),
	 ('Người vận hành nhà máy lọc dầu và khí tự nhiên','','','','3134','31340'),
	 ('Kiểm soát viên quy trình sản xuất kim loại','','','','3135','31350'),
	 ('Kỹ thuật viên kiểm soát quy trình khác chưa được phân vào đâu','','','','3139','31390'),
	 ('Kỹ thuật viên khoa học sự sống và kỹ thuật viên hỗ trợ liên quan','','','314','',''),
	 ('Kỹ thuật viên khoa học sự sống (không kể y tế) ','','','','3141','31410');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Kỹ thuật viên nông nghiệp','','','','3142','31420'),
	 ('Kỹ thuật viên lâm nghiệp','','','','3143','31430'),
	 ('Kỹ thuật viên nuôi trồng thủy sản','','','','3144','31440'),
	 ('Kỹ thuật viên và kiểm soát viên tàu thuỷ và phương tiện bay ','','','315','',''),
	 ('Kỹ thuật viên máy của tàu thủy','','','','3151','31510'),
	 ('Hoa tiêu và nhân viên văn phòng trên tàu','','','','3152','31520'),
	 ('Phi công phương tiện bay và kỹ thuật viên hỗ trợ liên quan','','','','3153','31530'),
	 ('Kiểm soát viên không lưu','','','','3154','31540'),
	 ('Kỹ thuật viên điện tử an toàn không lưu','','','','3155','31550'),
	 ('Kỹ thuật viên sức khỏe','','32','','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Kỹ thuật viên y tế và dược','','','321','',''),
	 ('Kỹ thuật viên hình ảnh và thiết bị y tế','','','','3211',''),
	 ('Kỹ thuật viên siêu âm','','','','','32111'),
	 ('Kỹ thuật viên X quang','','','','','32112'),
	 ('Kỹ thuật viên thiết bị y tế và hình ảnh khác','','','','','32119'),
	 ('Kỹ thuật viên phòng thí nghiệm y tế ','','','','3212','32120'),
	 ('Kỹ thuật viên và trợ lý dược','','','','3213','32130'),
	 ('Kỹ thuật viên lắp răng giả và chỉnh hình','','','','3214',''),
	 ('Kỹ thuật viên lắp chân tay giả và chỉnh hình','','','','','32141'),
	 ('Người làm và sửa các thiết bị chỉnh hình','','','','','32142');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Kỹ thuật viên lắp răng giả, chân tay giả và các thiết bị chỉnh hình khác  ','','','','','32143'),
	 ('Y tá/điều dưỡng, kỹ thuật viên chăm sóc bệnh nhân và hộ sinh','','','322','',''),
	 ('Y tá/điều dưỡng, kỹ thuật viên chăm sóc bệnh nhân','','','','3221','32210'),
	 ('Hộ sinh','','','','3222','32220'),
	 ('Kỹ thuật viên y học cổ truyền và bổ trợ','','','323','3230','32300'),
	 ('Kỹ thuật viên thú y và phụ tá','','','324','3240','32400'),
	 ('Kỹ thuật viên sức khỏe khác','','','325','',''),
	 ('Phụ tá nha khoa và trị liệu ','','','','3251','32510'),
	 ('Kỹ thuật viên ghi chép sổ sách y tế và thông tin về sức khỏe','','','','3252','32520'),
	 ('Nhân viên y tế cộng đồng','','','','3253','32530');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Kỹ thuật viên nhãn khoa','','','','3254','32540'),
	 ('Kỹ thuật viên vật lý trị liệu và phụ tá','','','','3255','32550'),
	 ('Nhân viên trợ giúp y tế','','','','3256','32560'),
	 ('Thanh tra viên và cộng tác viên môi trường và sức khỏe nghề nghiệp ','','','','3257','32570'),
	 ('Nhân viên cấp cứu','','','','3258','32580'),
	 ('Kỹ thuật viên sức khỏe khác chưa được phân vào đâu','','','','3259','32590'),
	 ('Nhân viên về kinh doanh và quản lý','','33','','',''),
	 ('Nhân viên về toán ứng dụng và tài chính ','','','331','',''),
	 ('Nhân viên môi giới, buôn bán chứng khoán và tài chính','','','','3311','33110'),
	 ('Nhân viên phụ trách các khoản tín dụng và khoản vay','','','','3312','33120');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Kế toán viên','','','','3313','33130'),
	 ('Nhân viên về thống kê và toán học ứng dụng có liên quan','','','','3314','33140'),
	 ('Nhân viên định giá và đánh giá mức độ thiệt hại ','','','','3315',''),
	 ('Thẩm định viên/định giá (trừ tài sản vô hình)','','','','','33151'),
	 ('Giám định viên','','','','','33152'),
	 ('Nhân viên định giá tài sản vô hình','','','','','33153'),
	 ('Thủ quỹ','','','','3316','33160'),
	 ('Nhân viên bán hàng, mua sắm và môi giới ','','','332','',''),
	 ('Nhân viên đại diện bảo hiểm','','','','3321',''),
	 ('Đại lý môi giới bảo hiểm (gồm cả nhà kế hoạch tài chính 
độc lập)','','','','','33211');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Đại diện bảo hiểm và các nhân viên hỗ trợ liên quan khác','','','','','33219'),
	 ('Nhân viên đại diện bán hàng hóa thương mại','','','','3322','33220'),
	 ('Nhân viên/đại lý mua hàng ','','','','3323',''),
	 ('Nhân viên thu mua','','','','','33231'),
	 ('Đại lý thu mua','','','','','33232'),
	 ('Nhân viên môi giới thương mại ','','','','3324','33240'),
	 ('Nhân viên/đại lý dịch vụ kinh doanh ','','','333','',''),
	 ('Nhân viên làm thủ tục thông quan và vận tải hàng hóa','','','','3331','33310'),
	 ('Nhân viên tổ chức hội thảo và sự kiện','','','','3332','33320'),
	 ('Nhân viên môi giới việc làm và nhà thầu','','','','3333','33330');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhân viên môi giới bất động sản và quản lý tài sản/bất động sản','','','','3334','33340'),
	 ('Nhân viên/đại lý dịch vụ kinh doanh khác chưa được phân vào đâu','','','','3339','33390'),
	 ('Thư ký hành chính và nhân viên chuyên môn khác','','','334','',''),
	 ('Giám sát viên văn phòng','','','','3341','33410'),
	 ('Thư ký luật','','','','3342','33420'),
	 ('Thư ký hành chính và điều hành','','','','3343','33430'),
	 ('Thư ký y tế','','','','3344','33440'),
	 ('Nhân viên điều tiết của Chính phủ','','','335','',''),
	 ('Nhân viên hải quan của Chính phủ','','','','3351','33510'),
	 ('Nhân viên thuế của Chính phủ','','','','3352','33520');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhân viên trợ cấp xã hội của Chính phủ','','','','3353','33530'),
	 ('Nhân viên cấp phép của Chính phủ','','','','3354','33540'),
	 ('Kiểm lâm','','','','3355','33550'),
	 ('Nhân viên điều tiết của Chính phủ khác chưa được phân vào đâu','','','','3359','33590'),
	 ('Nhân viên luật pháp, văn hóa, xã hội ','','34','','',''),
	 ('Nhân viên về luật pháp, xã hội và tôn giáo','','','341','',''),
	 ('Nhân viên về luật pháp','','','','3411','34110'),
	 ('Nhân viên về công tác xã hội ','','','','3412','34120'),
	 ('Nhân viên về tôn giáo','','','','3413','34130'),
	 ('Nhân viên về thể thao và tập luyện','','','342','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Vận động viên và người chơi thể thao','','','','3421','34210'),
	 ('Huấn luyện viên, nhân viên hướng dẫn thể thao và làm việc trong lĩnh vực thể thao','','','','3422',''),
	 ('Huấn luyện viên thể thao','','','','','34221'),
	 ('Nhân viên hướng dẫn thể dục thẩm mỹ','','','','','34222'),
	 ('Nhân viên hướng dẫn tập thể hình','','','','','34223'),
	 ('Nhân viên làm việc trong lĩnh vực thể thao','','','','','34224'),
	 ('Huấn luyện viên, nhân viên hướng dẫn thể thao và làm việc trong lĩnh vực thể thao khác','','','','','34229'),
	 ('Người hướng dẫn tập luyện và giải trí, người chỉ đạo chương trình','','','','3423','34230'),
	 ('Nhân viên về nghệ thuật, văn hóa và ẩm thực','','','343','',''),
	 ('Nhiếp ảnh gia','','','','3431','34310');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà thiết kế và trang trí nội thất','','','','3432','34320'),
	 ('Kỹ thuật viên thư viện, viện bảo tàng và triển lãm','','','','3433','34330'),
	 ('Đầu bếp trưởng','','','','3434','34340'),
	 ('Nhân viên về nghệ thuật và văn hóa khác ','','','','3439','34390'),
	 ('Kỹ thuật viên thông tin và truyền thông','','35','','',''),
	 ('Kỹ thuật viên hỗ trợ người sử dụng và vận hành công nghệ thông tin và truyền thông','','','351','',''),
	 ('Kỹ thuật viên vận hành công nghệ thông tin và truyền thông','','','','3511','35110'),
	 ('Kỹ thuật viên hỗ trợ người sử dụng công nghệ thông tin và truyền thông','','','','3512','35120'),
	 ('Kỹ thuật viên hệ thống và mạng máy tính ','','','','3513','35130'),
	 ('Kỹ thuật viên web','','','','3514','35140');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Kỹ thuật viên viễn thông và phát thanh truyền hình','','','352','',''),
	 ('Kỹ thuật viên truyền hình và nghe - nhìn','','','','3521',''),
	 ('Kỹ thuật viên điều hành chương trình','','','','','35211'),
	 ('Nhân viên điều khiển máy quay phim','','','','','35212'),
	 ('Nhân viên điều khiển máy quay hình động/tivi','','','','','35213'),
	 ('Nhân viên điều khiển thiết bị phòng thu phát thanh truyền hình','','','','','35214'),
	 ('Nhân viên điều khiển thiết bị ghi âm','','','','','35215'),
	 ('Nhân viên dựng phim','','','','','35216'),
	 ('Các kỹ thuật viên phát thanh và nghe nhìn khác','','','','','35219'),
	 ('Kỹ thuật viên kỹ thuật viễn thông','','','','3522','35220');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Giáo viên bậc trung','','36','','',''),
	 ('Giáo viên tiểu học','','','361','3610','36100'),
	 ('Giáo viên mầm non','','','362','3620','36200'),
	 ('Giáo viên dạy các đối tượng bị khuyết tật','','','363','3630','36300'),
	 ('Giáo viên khác','','','364','',''),
	 ('Giáo viên sơ cấp','','','','3641','36410'),
	 ('Giáo viên đào tạo khác','','','','3642','36420'),
	 ('Nhân viên trợ lý văn phòng ','4','','','',''),
	 ('Nhân viên tổng hợp và nhân viên làm các công việc bàn giấy','','41','','',''),
	 ('Nhân viên tổng hợp ','','','411','4110','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhân viên văn phòng (gồm cả sắp xếp tài liệu và sao chụp)','','','','','41101'),
	 ('Nhân viên nguồn nhân lực/tổ chức','','','','','41102'),
	 ('Nhân viên hành chính khác ','','','','','41109'),
	 ('Thư ký (tổng hợp)','','','412','4120','41200'),
	 ('Nhân viên làm công việc bàn giấy','','','413','',''),
	 ('Nhân viên đánh máy','','','','4131','41310'),
	 ('Nhân viên nhập dữ liệu','','','','4132','41320'),
	 ('Nhân viên dịch vụ khách hàng','','42','','',''),
	 ('Nhân viên thu ngân, thu tiền và các nghề liên quan','','','421','',''),
	 ('Nhân viên giao dịch ngân hàng và các nghề liên quan','','','','4211','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhân viên giao dịch ngân hàng','','','','','42111'),
	 ('Nhân viên thu ngân dịch vụ bưu điện','','','','','42112'),
	 ('Nhân viên đổi tiền','','','','','42113'),
	 ('Nhân viên giao dịch và thu ngân khác','','','','','42119'),
	 ('Nhân viên chia bài trong sòng bạc và các nghề liên quan đến cờ bạc khác','','','','4212','42120'),
	 ('Chủ hiệu cầm đồ và cho vay tiền','','','','4213',''),
	 ('Chủ hiệu cầm đồ','','','','','42131'),
	 ('Người cho vay tiền','','','','','42132'),
	 ('Người thu nợ và các công việc liên quan','','','','4214',''),
	 ('Người thu nợ','','','','','42141');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Người thu nợ khác và làm công việc có liên quan ','','','','','42149'),
	 ('Nhân viên thông tin khách hàng','','','422','',''),
	 ('Nhân viên và tư vấn viên du lịch','','','','4221','42210'),
	 ('Nhân viên trung tâm thông tin liên lạc','','','','4222','42220'),
	 ('Nhân viên vận hành tổng đài điện thoại','','','','4223','42230'),
	 ('Nhân viên lễ tân khách sạn','','','','4224','42240'),
	 ('Nhân viên hướng dẫn','','','','4225','42250'),
	 ('Lễ tân (tổng hợp)','','','','4226','42260'),
	 ('Phỏng vấn viên điều tra và nghiên cứu thị trường','','','','4227','42270'),
	 ('Nhân viên thông tin khách hàng chưa được phân vào đâu','','','','4229','42290');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhân viên ghi chép số liệu và vật liệu','','43','','',''),
	 ('Nhân viên làm công việc liên quan đến số liệu ','','','431','',''),
	 ('Nhân viên kế toán','','','','4311','43110'),
	 ('Nhân viên thống kê, tài chính và bảo hiểm','','','','4312','43120'),
	 ('Nhân viên kế toán tiền lương','','','','4313','43130'),
	 ('Nhân viên ghi chép nguyên vật liệu và vận chuyển','','','432','',''),
	 ('Nhân viên ghi chép tồn kho','','','','4321','43210'),
	 ('Nhân viên sản xuất','','','','4322','43220'),
	 ('Nhân viên vận chuyển','','','','4323','43230'),
	 ('Nhân viên hỗ trợ văn phòng khác','','44','440','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhân viên thư viện','','','','4401','44010'),
	 ('Nhân viên phân loại và vận chuyển thư','','','','4402','44020'),
	 ('Nhân viên đánh mã, đọc và sửa bản in thử','','','','4403','44030'),
	 ('Người ghi chép thuê và người làm các công việc có liên quan','','','','4404','44040'),
	 ('Nhân viên văn thư và phô tô','','','','4405','44050'),
	 ('Nhân viên tổ chức nhân sự','','','','4406','44060'),
	 ('Nhân viên hỗ trợ văn phòng khác chưa được phân vào đâu','','','','4409','44090'),
	 ('Nhân viên dịch vụ và bán hàng','5','','','',''),
	 ('Nhân viên dịch vụ cá nhân','','51','','',''),
	 ('Nhân viên hướng dẫn, tổ chức khách du lịch','','','511','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Tiếp viên trên tàu hoặc máy bay','','','','5111','51110'),
	 ('Nhân viên phụ tàu xe','','','','5112','51120'),
	 ('Nhân viên hướng dẫn du lịch','','','','5113',''),
	 ('Nhân viên hướng dẫn khu thiên nhiên','','','','','51131'),
	 ('Nhân viên hướng dẫn công viên chủ đề','','','','','51132'),
	 ('Nhân viên hướng dẫn du lịch khác (như di tích lịch sử, 
bảo tàng)','','','','','51139'),
	 ('Bồi bàn và nhân viên pha chế','','','513','',''),
	 ('Bồi bàn','','','','5131',''),
	 ('Tổ trưởng/Giám sát bồi bàn','','','','','51311'),
	 ('Bồi bàn (trừ bồi bàn rượu)','','','','','51312');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Bồi bàn rượu','','','','','51313'),
	 ('Nhân viên pha chế','','','','5132','51320'),
	 ('Thợ làm đầu, nhân viên làm đẹp','','','514','',''),
	 ('Thợ làm đầu','','','','5141','51410'),
	 ('Nhân viên làm đẹp và nhân viên có liên quan','','','','5142','51420'),
	 ('Người giám sát tòa nhà, quản gia','','','515','',''),
	 ('Người giám sát việc dọn dẹp và vệ sinh trong văn phòng, khách sạn và các cơ quan khác','','','','5151','51510'),
	 ('Người quản lý công việc gia đình','','','','5152','51520'),
	 ('Người chăm sóc, bảo vệ tòa nhà','','','','5153','51530'),
	 ('Nhân viên dịch vụ cá nhân khác','','','516','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhà chiêm tinh, nhà tướng số và những người có liên quan đến tâm linh khác','','','','5161','51610'),
	 ('Người bồi phòng và những người được thuê để làm bầu bạn','','','','5162','51620'),
	 ('Người làm nghề phục vụ tang lễ và ướp xác','','','','5163','51630'),
	 ('Nhân viên chăm sóc và làm đẹp động vật','','','','5164','51640'),
	 ('Giáo viên hướng dẫn lái xe','','','','5165','51650'),
	 ('Nhân viên dịch vụ cá nhân khác chưa được phân vào đâu','','','','5169','51690'),
	 ('Nhân viên bán hàng','','52','','',''),
	 ('Người bán hàng trên đường phố và tại chợ','','','521','',''),
	 ('Người bán hàng trong quầy hàng và tại chợ','','','','5211','52110'),
	 ('Người bán đồ ăn trên đường phố','','','','5212','52120');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhân viên bán hàng trong cửa hàng','','','522','',''),
	 ('Chủ cửa hiệu','','','','5221','52210'),
	 ('Nhân viên giám sát cửa hàng','','','','5222','52220'),
	 ('Nhân viên trợ giúp bán hàng','','','','5223','52230'),
	 ('Nhân viên thu ngân và bán vé','','','523','5230',''),
	 ('Nhân viên thu ngân và bán vé','','','','','52301'),
	 ('Nhân viên thu ngân','','','','','52302'),
	 ('Nhân viên thu ngân và bán vé có liên quan khác','','','','','52309'),
	 ('Nhân viên bán hàng khác','','','524','',''),
	 ('Nhân viên làm mẫu ','','','','5241','52410');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhân viên thuyết minh giới thiệu hàng hóa','','','','5242','52420'),
	 ('Nhân viên bán hàng tận nhà','','','','5243','52430'),
	 ('Nhân viên bán hàng qua trung tâm liên lạc','','','','5244','52440'),
	 ('Nhân viên phục vụ ở các trạm dịch vụ','','','','5245','52450'),
	 ('Nhân viên phục vụ đồ ăn uống','','','','5246','52460'),
	 ('Nhân viên bán hàng khác chưa được phân vào đâu','','','','5249','52490'),
	 ('Nhân viên chăm sóc cá nhân','','53','','',''),
	 ('Nhân viên chăm sóc trẻ em và người phụ tá cho giáo viên','','','531','',''),
	 ('Nhân viên chăm sóc trẻ em','','','','5311','53110'),
	 ('Người phụ tá cho giáo viên','','','','5312','53120');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhân viên chăm sóc cá nhân trong các dịch vụ y tế','','','532','',''),
	 ('Nhân viên hỗ trợ về chăm sóc sức khỏe','','','','5321','53210'),
	 ('Nhân viên chăm sóc cá nhân tại nhà','','','','5322',''),
	 ('Nhân viên chăm sóc cá nhân (như vật lý trị liệu)','','','','','53221'),
	 ('Điều dưỡng tại nhà','','','','','53222'),
	 ('Nhân viên chăm sóc cá nhân trong các dịch vụ y tế chưa được phân vào đâu','','','','5329','53290'),
	 ('Nhân viên dịch vụ bảo vệ','','54','540','',''),
	 ('Nhân viên an ninh (trừ công an)','','','','5401','54010'),
	 ('Nhân viên dịch vụ bảo vệ khác chưa được phân vào đâu','','','','5409',''),
	 ('Thám tử tư','','','','','54091');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Nhân viên bảo vệ rừng','','','','','54092'),
	 ('Nhân viên dịch vụ bảo vệ khác còn lại chưa được phân vào đâu','','','','','54099'),
	 ('Lao động có kỹ năng trong nông nghiệp, lâm nghệp và thủy sản','6','','','',''),
	 ('Lao động có kỹ năng trong nông nghiệp có sản phẩm chủ yếu để bán','','61','','',''),
	 ('Lao động trồng trọt và làm vườn có sản phẩm chủ yếu để bán','','','611','',''),
	 ('Lao động trồng, thu hoạch rau và cây mùa vụ','','','','6111',''),
	 ('Lao động trồng, thu hoạch lúa','','','','','61111'),
	 ('Lao động trồng, thu hoạch rau các loại','','','','','61112'),
	 ('Lao động trồng, thu hoạch cây mùa vụ khác','','','','','61119'),
	 ('Lao động trồng, thu hoạch sản phẩm cây bụi và cây thân gỗ','','','','6112','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Lao động trồng, thu hoạch sản phẩm cây cà phê','','','','','61121'),
	 ('Lao động trồng, thu hoạch sản phẩm cây chè','','','','','61122'),
	 ('Lao động trồng, thu hoạch sản phẩm cây tiêu','','','','','61123'),
	 ('Lao động trồng, thu hoạch sản phẩm cây điều','','','','','61124'),
	 ('Lao động trồng, thu hoạch sản phẩm cây cao su','','','','','61125'),
	 ('Lao động trồng, thu hoạch sản phẩm cây bụi và cây thân gỗ khác','','','','','61129'),
	 ('Lao động làm vườn, trồng vườn và vườn ươm','','','','6113',''),
	 ('Lao động trồng, thu hoạch hoa, cây cảnh','','','','','61131'),
	 ('Lao động làm vườn, trồng vườn và vườn ươm khác','','','','','61139'),
	 ('Lao động trồng trọt hỗn hợp','','','','6114','61140');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Lao động chăn nuôi ','','','612','',''),
	 ('Lao động chăn nuôi gia súc và vật nuôi lấy sữa','','','','6121',''),
	 ('Lao động chăn nuôi trâu bò','','','','','61211'),
	 ('Lao động chăn nuôi dê, cừu, hươu','','','','','61212'),
	 ('Lao động chăn nuôi lợn','','','','','61213'),
	 ('Lao động chăn nuôi gia súc khác','','','','','61219'),
	 ('Lao động chăn nuôi gia cầm','','','','6122',''),
	 ('Lao động chăn nuôi gà','','','','','61221'),
	 ('Lao động chăn nuôi vịt, ngan, ngỗng','','','','','61222'),
	 ('Lao động chăn nuôi gia cầm khác','','','','','61229');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Lao động nuôi ong và nuôi tằm','','','','6123',''),
	 ('Lao động nuôi ong','','','','','61231'),
	 ('Lao động nuôi tằm','','','','','61232'),
	 ('Lao động chăn nuôi chưa được phân vào đâu','','','','6129','61290'),
	 ('Lao động trồng trọt và chăn nuôi hỗn hợp','','','613','6130','61300'),
	 ('Lao động có kỹ năng trong lâm nghiệp, thủy sản và săn bắn có sản phẩm chủ yếu để bán','','62','','',''),
	 ('Lao động trong lâm nghiệp và lĩnh vực có liên quan','','','621','6210',''),
	 ('Lao động ươm giống cây lâm nghiệp','','','','','62101'),
	 ('Lao động trồng rừng và chăm sóc rừng lấy gỗ','','','','','62102'),
	 ('Lao động trồng rừng và chăm sóc rừng tre, nứa','','','','','62103');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Lao động trong lâm nghiệp và lĩnh vực có liên quan khác','','','','','62109'),
	 ('Lao động thủy sản, săn bắn và đánh bẫy','','','622','',''),
	 ('Lao động nuôi trồng thủy sản','','','','6221',''),
	 ('Lao động nuôi cá','','','','','62211'),
	 ('Lao động nuôi tôm','','','','','62212'),
	 ('Lao động nuôi trồng thủy sản khác','','','','','62219'),
	 ('Lao động khai thác thủy sản trong nội địa','','','','6222',''),
	 ('Lao động khai thác cá trong nội địa','','','','','62221'),
	 ('Lao động khai thác thủy sản khác trong nội địa','','','','','62229'),
	 ('Lao động khai thác thủy sản trong vùng biển Việt Nam','','','','6223','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Lao động khai thác cá trong vùng biển Việt Nam','','','','','62231'),
	 ('Lao động khai thác thủy sản khác trong vùng biển Việt Nam','','','','','62239'),
	 ('Lao động săn bắn, đánh bẫy','','','','6224','62240'),
	 ('Lao động tự cung tự cấp trong nông nghiệp, lâm nghiệp và thủy sản','','63','','',''),
	 ('Lao động trồng trọt tự cung tự cấp','','','631','6310','63100'),
	 ('Lao động chăn nuôi gia súc tự cung tự cấp','','','632','6320','63200'),
	 ('Lao động trồng trọt và chăn nuôi hỗn hợp tự cung tự cấp ','','','633','6330','63300'),
	 ('Lao động đánh cá, săn bắn, đánh bẫy và thu hái tự cung tự cấp','','','634','6340','63400'),
	 ('Lao động thủ công và các nghề có liên quan khác','7','','','',''),
	 ('Lao động xây dựng và lao động có liên quan đến nghề xây dựng (trừ thợ điện)','','71','','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ xây dựng khung nhà và thợ khác có liên quan','','','711','',''),
	 ('Thợ xây nhà','','','','7111','71110'),
	 ('Thợ nề và các thợ có liên quan','','','','7112','71120'),
	 ('Thợ xây nhà bằng đá, thợ cắt đá, thợ tách đá và thợ khắc đá','','','','7113',''),
	 ('Thợ đẽo đá/thợ khắc đá','','','','','71131'),
	 ('Thợ xây nhà bằng đá','','','','','71132'),
	 ('Thợ đổ bê tông và các thợ có liên quan ','','','','7114',''),
	 ('Thợ đổ bê tông cốt thép (chung)','','','','','71141'),
	 ('Thợ bê tông','','','','','71142'),
	 ('Thợ bê tông khác, thợ hoàn thiện bê tông và thợ liên quan khác','','','','','71149');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ mộc và thợ làm đồ gỗ','','','','7115','71150'),
	 ('Thợ xây dựng khung nhà và thợ khác có liên quan chưa được phân vào đâu','','','','7119',''),
	 ('Thợ giàn giáo','','','','','71191'),
	 ('Thợ phá dỡ','','','','','71192'),
	 ('Thợ ốp tường','','','','','71193'),
	 ('Thợ xây khác và thợ có liên quan chưa được phân vào đâu','','','','','71199'),
	 ('Thợ hoàn thiện công trình và thợ có liên quan','','','712','',''),
	 ('Thợ lợp mái','','','','7121','71210'),
	 ('Thợ lát sàn và thợ lát đá','','','','7122','71220'),
	 ('Thợ thạch cao','','','','7123','71230');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ lắp đặt vật liệu cách âm, cách nhiệt','','','','7124',''),
	 ('Thợ lắp đặt cách điện xây dựng','','','','','71241'),
	 ('Thợ nồi hơi/thợ ống cách điện','','','','','71242'),
	 ('Thợ lắp đặt cách điện thiết bị điều hòa không khí','','','','','71243'),
	 ('Thợ lắp đặt vật liệu chịu lửa','','','','','71244'),
	 ('Thợ lắp đặt vật liệu cách âm, cách nhiệt khác','','','','','71249'),
	 ('Thợ lắp kính','','','','7125','71250'),
	 ('Thợ ống nước','','','','7126','71260'),
	 ('Thợ cơ khí thiết bị điều hòa không khí và làm lạnh','','','','7127','71270'),
	 ('Thợ sơn, người lau dọn tòa nhà và lao động có liên quan','','','713','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ sơn và thợ liên quan khác','','','','7131',''),
	 ('Thợ sơn','','','','','71311'),
	 ('Thợ dán giấy dán tường/trần','','','','','71312'),
	 ('Thợ phun sơn và thợ đánh véc ni','','','','7132',''),
	 ('Thợ sơn kết cấu thép/sơn tàu','','','','','71321'),
	 ('Thợ phun sơn xe cơ giới','','','','','71322'),
	 ('Thợ vẽ bảng hiệu','','','','','71323'),
	 ('Thợ phun sơn (trừ tàu, xe cơ giới và biển báo)','','','','','71324'),
	 ('Thợ sơn khác và thợ có liên quan','','','','','71329'),
	 ('Người lau dọn tòa nhà','','','','7133','71330');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ luyện kim, cơ khí và thợ có liên quan','','72','','',''),
	 ('Thợ luyện kim loại, thợ đúc, thợ hàn và thợ có liên quan','','','721','',''),
	 ('Thợ tạo khuôn và lõi kim loại','','','','7211','72110'),
	 ('Thợ hàn và thợ cắt kim loại bằng nhiệt','','','','7212',''),
	 ('Thợ hàn','','','','','72121'),
	 ('Thợ cắt kim loại bằng nhiệt','','','','','72122'),
	 ('Thợ luyện kim loại','','','','7213','72130'),
	 ('Thợ chuẩn bị và lắp ráp các cấu kiện kim loại ','','','','7214','72140'),
	 ('Thợ lắp ráp và thợ nối cáp','','','','7215','72150'),
	 ('Thợ rèn, thợ chế tạo các dụng cụ và thợ có liên quan','','','722','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ rèn, thợ quai búa và thợ rèn ép nén kim loại','','','','7221','72210'),
	 ('Thợ chế tạo dụng cụ và thợ có liên quan','','','','7222','72220'),
	 ('Thợ lắp ráp và vận hành máy công cụ kim loại','','','','7223','72230'),
	 ('Thợ đánh bóng, thợ mài kim loại và dụng cụ kim loại','','','','7224','72240'),
	 ('Thợ cơ khí và sửa chữa máy móc','','','723','',''),
	 ('Thợ cơ khí và sửa chữa xe có động cơ','','','','7231',''),
	 ('Thợ cơ khí xe có động cơ','','','','','72311'),
	 ('Thợ sửa chữa xe có động cơ','','','','','72312'),
	 ('Thợ cơ khí và sửa chữa động cơ máy bay','','','','7232',''),
	 ('Thợ cơ khí máy bay','','','','','72321');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ sửa chữa động cơ máy bay','','','','','72322'),
	 ('Thợ cơ khí và sửa chữa máy móc nông nghiệp và công nghiệp','','','','7233',''),
	 ('Thợ cơ khí máy móc (chung)','','','','','72331'),
	 ('Thợ sửa chữa máy móc (chung)','','','','','72332'),
	 ('Thợ cơ khí máy móc công nghiệp/máy văn phòng','','','','','72333'),
	 ('Thợ sửa chữa động cơ biển','','','','','72334'),
	 ('Thợ lắp đặt máy móc, thiết bị','','','','','72335'),
	 ('Thợ cơ khí và sửa chữa máy móc khác (như thợ cơ khí máy móc nông nghiệp)','','','','','72339'),
	 ('Thợ sửa chữa xe đạp và thợ có liên quan ','','','','7234','72340'),
	 ('Thợ thủ công và thợ liên quan đến in','','73','','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ thủ công','','','731','',''),
	 ('Thợ sản xuất và sửa chữa dụng cụ chính xác','','','','7311','73110'),
	 ('Thợ sản xuất và điều chỉnh nhạc cụ','','','','7312','73120'),
	 ('Thợ kim hoàn','','','','7313',''),
	 ('Thợ kim hoàn (nói chung)','','','','','73131'),
	 ('Thợ cắt và đánh bóng đá quý','','','','','73132'),
	 ('Thợ vàng/thợ bạc','','','','','73133'),
	 ('Thợ khắc kim hoàn','','','','','73134'),
	 ('Thợ kim hoàn khác','','','','','73139'),
	 ('Thợ gốm và thợ có liên quan ','','','','7314','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ gốm','','','','','73141'),
	 ('Thợ gạch ngói','','','','','73142'),
	 ('Thợ gốm và thợ có liên quan khác','','','','','73149'),
	 ('Thợ sản xuất, thợ cắt, thợ mài và thợ hoàn thiện đồ thủy tinh','','','','7315','73150'),
	 ('Thợ vẽ biển quảng cáo, thợ trang trí, thợ khắc và thợ khắc axit','','','','7316',''),
	 ('Thợ khắc thủy tinh/thợ khắc axit','','','','','73161'),
	 ('Thợ vẽ/thợ trang trí thủy tinh và gốm','','','','','73162'),
	 ('Thợ vẽ biển quảng cáo, thợ trang trí, thợ khắc và thợ khắc axit khác','','','','','73169'),
	 ('Thợ thủ công sản xuất đồ gỗ, rổ rá và các nguyên liệu có liên quan','','','','7317','73170'),
	 ('Thợ thủ công dệt vải, da và các nguyên liệu có liên quan','','','','7318','73180');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ thủ công khác chưa được phân vào đâu','','','','7319','73190'),
	 ('Thợ liên quan đến in','','','732','',''),
	 ('Thợ thực hiện công đoạn trước in','','','','7321','73210'),
	 ('Thợ in','','','','7322',''),
	 ('Thợ in offset, in lõm, in cao, in lưới và in kỹ thuật số','','','','','73221'),
	 ('Thợ in khác','','','','','73229'),
	 ('Thợ hoàn thiện sản phẩm in','','','','7323','73230'),
	 ('Thợ điện và thợ điện tử','','74','','',''),
	 ('Thợ lắp đặt và sửa chữa thiết bị điện','','','741','',''),
	 ('Thợ lắp điện cho tòa nhà và thợ điện có liên quan','','','','7411','74110');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ lắp ráp và thợ cơ khí điện ','','','','7412',''),
	 ('Thợ lắp ráp điện (chung)','','','','','74121'),
	 ('Thợ lắp ráp điện thang máy, thang cuốn và các thiết bị liên quan','','','','','74122'),
	 ('Thợ sửa chữa điện gia dụng','','','','','74123'),
	 ('Thơ lắp ráp và thợ cơ khí điện khác','','','','','74129'),
	 ('Thợ lắp đặt và sửa chữa đường dây điện ','','','','7413',''),
	 ('Thợ lắp đặt đường dây điện','','','','','74131'),
	 ('Thợ ghép cáp điện','','','','','74132'),
	 ('Thợ lắp đặt và sửa chữa đường dây điện khác','','','','','74139'),
	 ('Thợ lắp đặt và thợ sửa chữa điện tử viễn thông','','','742','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ cơ khí và thợ dịch vụ điện tử','','','','7421',''),
	 ('Thợ lắp đặt thiết bị điện tử (chung)','','','','','74211'),
	 ('Thợ cơ khí thiết bị video và âm thanh','','','','','74212'),
	 ('Thợ lắp đặt thiết bị điện tử khác','','','','','74219'),
	 ('Thợ lắp đặt và dịch vụ kỹ thuật thông tin và truyền thông','','','','7422',''),
	 ('Thợ lắp đặt phát sóng rada, phát thanh truyền hình/thiết bị truyền dẫn','','','','','74221'),
	 ('Thợ lắp đặt và sửa chữa máy tính và thiết bị điện tử liên quan','','','','','74222'),
	 ('Thợ kéo dây cáp viễn thông','','','','','74223'),
	 ('Thợ cài đặt viễn thông/dịch vụ viễn thông','','','','','74224'),
	 ('Thợ chế biến thực phẩm, gia công gỗ, may mặc, đồ thủ công và thợ có liên quan khác','','75','','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ chế biến thực phẩm và các thợ khác có liên quan','','','751','',''),
	 ('Thợ giết, mổ, chuẩn bị thịt, cá và thực phẩm khác có liên quan','','','','7511',''),
	 ('Thợ giết mổ','','','','','75111'),
	 ('Thợ giết mổ, chuẩn bị thịt, cá và thực phẩm khác có liên quan','','','','','75119'),
	 ('Thợ nướng bánh, thợ làm bánh ngọt và bánh kẹo','','','','7512',''),
	 ('Thợ làm bánh (chung)','','','','','75121'),
	 ('Thợ làm bánh mỳ','','','','','75122'),
	 ('Thợ làm bánh ngọt và bánh kẹo','','','','','75123'),
	 ('Thợ làm sản phẩm từ sữa','','','','7513','75130'),
	 ('Thợ bảo quản rau, hoa quả tươi và các thứ có liên quan','','','','7514','75140');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ nếm và phân loại đồ uống, thực phẩm','','','','7515',''),
	 ('Thợ nếm cà phê và trà','','','','','75151'),
	 ('Thợ nếm và phân loại đồ uống, thực phẩm khác','','','','','75159'),
	 ('Thợ sản xuất và chuẩn bị thuốc lá','','','','7516','75160'),
	 ('Thợ xử lý gỗ, thợ sản xuất đồ gỗ và các thợ có liên quan ','','','752','',''),
	 ('Thợ xử lý gỗ','','','','7521',''),
	 ('Thợ lò sấy','','','','','75211'),
	 ('Thợ xử lý gỗ','','','','','75212'),
	 ('Thợ xử lý gỗ khác','','','','','75219'),
	 ('Thợ sản xuất làm đồ gỗ và các thợ có liên quan','','','','7522','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ sản xuất đồ nội thất','','','','','75221'),
	 ('Thợ hoàn thiện đồ gỗ','','','','','75222'),
	 ('Thợ sản xuất khung hình','','','','','75223'),
	 ('Thợ sản xuất đồ gỗ và các thợ có liên quan khác','','','','','75229'),
	 ('Thợ lắp đặt và vận hành máy công cụ chế biến gỗ','','','','7523','75230'),
	 ('Thợ may mặc và các thợ có liên quan','','','753','',''),
	 ('Thợ may, thợ làm da thú và thợ làm mũ','','','','7531','75310'),
	 ('Thợ tạo mẫu và cắt quần áo và các thợ có liên quan','','','','7532',''),
	 ('Thợ tạo mẫu','','','','','75321'),
	 ('Thợ cắt','','','','','75322');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ tạo và cắt mẫu áo quần và các mẫu có liên quan khác','','','','','75329'),
	 ('Thợ khâu vá, thợ thêu và các thợ có liên quan','','','','7533','75330'),
	 ('Thợ làm nghề bọc đồ đạc và các thợ có liên quan','','','','7534','75340'),
	 ('Thợ thuộc da sống, thợ nhuộm và thợ chuyên lột da, lông thú','','','','7535','75350'),
	 ('Thợ đóng giày và các thợ có liên quan','','','','7536',''),
	 ('Thợ đóng giày','','','','','75361'),
	 ('Thợ sản xuất giày chỉnh hình','','','','','75362'),
	 ('Thợ vá giày','','','','','75363'),
	 ('Thợ sản xuất/lắp ráp hàng da','','','','','75364'),
	 ('Thợ đóng giày và các thợ có liên quan khác','','','','','75369');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ thủ công khác và các thợ có liên quan','','','754','',''),
	 ('Thợ lặn','','','','7541','75410'),
	 ('Thợ giật mìn phá đá ','','','','7542','75420'),
	 ('Thợ phân loại và kiểm tra sản phẩm (trừ thực phẩm và đồ uống)','','','','7543','75430'),
	 ('Thợ hun khói và thợ kiểm soát thực vật, động vật có hại khác','','','','7544','75440'),
	 ('Thợ thủ công và các thợ khác chưa được phân vào đâu','','','','7549','75490'),
	 ('Thợ lắp ráp và vận hành máy móc, thiết bị','8','','','',''),
	 ('Thợ vận hành máy móc và thiết bị','','81','','',''),
	 ('Thợ vận hành máy móc, thiết bị xử lý khai khoáng','','','811','',''),
	 ('Thợ khai thác mỏ và đá','','','','8111','81110');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ vận hành thiết bị chế biến khoáng sản và đá','','','','8112','81120'),
	 ('Thợ khoan, đào giếng và các thợ có liên quan','','','','8113',''),
	 ('Thợ khoan giếng (giếng dầu khí)','','','','','81131'),
	 ('Thợ khoan giếng (trừ giếng dầu khí)','','','','','81132'),
	 ('Thợ vận hành máy khoan sâu','','','','','81133'),
	 ('Thợ khoan, đào giếng và các thợ có liên quan khác','','','','','81139'),
	 ('Thợ vận hành máy sản xuất xi măng, đá và khoáng khác','','','','8114',''),
	 ('Thợ vận hành máy sản xuất sản phẩm bê tông đúc sẵn','','','','','81141'),
	 ('Thợ vận hành máy sản xuất xi măng amiăng','','','','','81142'),
	 ('Thợ vận hành máy làm gạch đất nung, ngói','','','','','81143');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ vận hành máy trộn bê tông','','','','','81144'),
	 ('Thợ vận hành bơm bê tông','','','','','81145'),
	 ('Thợ vận hành máy chế biến và các sản phẩm khoáng sản khác','','','','','81149'),
	 ('Thợ vận hành thiết bị xử lý và hoàn thiện kim loại','','','812','',''),
	 ('Thợ vận hành thiết bị xử lý kim loại','','','','8121','81210'),
	 ('Thợ vận hành máy hoàn thiện, tráng, mạ kim loại','','','','8122','81220'),
	 ('Thợ vận hành máy móc, thiết bị sản xuất hóa học và sản xuất sản phẩm phim ảnh','','','813','',''),
	 ('Thợ vận hành máy và thiết bị sản xuất hóa chất','','','','8131',''),
	 ('Thợ vận hành thiết bị nghiền/trộn hóa chất','','','','','81311'),
	 ('Thợ vận hành máy xử lý nhiệt hóa học','','','','','81312');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ vận hành máy lọc và tách hóa chất','','','','','81313'),
	 ('Thợ vận hành hóa chất tĩnh/lò phản ứng','','','','','81314'),
	 ('Thợ vận hành máy sợi tổng hợp','','','','','81315'),
	 ('Thợ vận hành máy và thiết bị sản xuất hóa học khác','','','','','81319'),
	 ('Thợ vận hành máy sản xuất sản phẩm phim ảnh','','','','8132','81320'),
	 ('Thợ vận hành máy sản xuất sản phẩm giấy, nhựa và cao su','','','814','',''),
	 ('Thợ vận hành máy sản xuất sản phẩm cao su','','','','8141',''),
	 ('Thợ vận hành máy phay cao su','','','','','81411'),
	 ('Thợ vận hành máy cán cao su','','','','','81412'),
	 ('Thợ vận hành máy sản xuất sản phẩm cao su khác','','','','','81419');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ vận hành máy sản xuất sản phẩm nhựa','','','','8142','81420'),
	 ('Thợ vận hành máy sản xuất sản phẩm từ giấy và thùng catong','','','','8143',''),
	 ('Thợ vận hành máy làm thùng catong/hộp giấy','','','','','81431'),
	 ('Thợ vận hành máy sản xuất sản phẩm giấy','','','','','81432'),
	 ('Thợ vận hành máy sản xuất sản phẩm giấy và thùng catong khác','','','','','81439'),
	 ('Thợ vận hành máy sản xuất nguyên liệu dệt, da lông thú và da thuộc','','','815','',''),
	 ('Thợ vận hành máy xe sợi, kéo sợi và cuộn sợi','','','','8151',''),
	 ('Thợ vận hành máy xe chỉ (chỉ và sợi)','','','','','81511'),
	 ('Thợ vận hành máy cuộn chỉ (chỉ và sợi)','','','','','81512'),
	 ('Thợ vận hành máy dệt kim, máy đan','','','','8152','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ vận hành máy dệt','','','','','81521'),
	 ('Thợ vận hành máy đan','','','','','81522'),
	 ('Thợ vận hành máy may','','','','8153',''),
	 ('Thợ vận hành máy may','','','','','81531'),
	 ('Thợ vận hành máy thêu','','','','','81532'),
	 ('Thợ vận hành máy tẩy trắng, máy nhuộm và làm sạch sợi','','','','8154',''),
	 ('Thợ vận hành máy tẩy trắng','','','','','81541'),
	 ('Thợ vận hành máy nhuộm','','','','','81542'),
	 ('Thợ vận hành máy làm sạch sợi','','','','','81543'),
	 ('Thợ vận hành máy tẩy trắng, máy nhuộm và làm sạch sợi khác','','','','','81549');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ vận hành máy chuẩn bị da, lông thú','','','','8155','81550'),
	 ('Thợ vận hành máy đóng giầy, dép và các thợ có liên quan','','','','8156','81560'),
	 ('Thợ vận hành máy giặt là','','','','8157','81570'),
	 ('Thợ vận hành máy sản xuất nguyên liệu dệt, da lông thú và da thuộc chưa được phân vào đâu','','','','8159','81590'),
	 ('Thợ vận hành máy sản xuất thực phẩm và các thợ có liên quan','','','816','8160',''),
	 ('Thợ vận hành máy sản xuất các sản phẩm từ thịt và cá','','','','','81601'),
	 ('Thợ vận hành máy sản xuất sữa và bánh kẹo','','','','','81602'),
	 ('Thợ vận hành máy xay ngũ cốc và gia vị','','','','','81603'),
	 ('Thợ vận hành máy nướng và các sản phẩm từ ngũ cốc','','','','','81604'),
	 ('Thợ vận hành máy sản xuất các sản phẩm từ trái cây, rau quả','','','','','81605');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ vận hành máy chế biến và tinh chế đường','','','','','81606'),
	 ('Thợ vận hành máy sản xuất bia, rượu và nước giải khát khác','','','','','81607'),
	 ('Thợ vận hành máy sản xuất thuốc lá','','','','','81608'),
	 ('Thợ vận hành máy sản xuất thực phẩm và các thợ có liên quan chưa được phân vào đâu','','','','','81609'),
	 ('Thợ vận hành thiết bị chế biến gỗ và sản xuất giấy','','','817','',''),
	 ('Thợ vận hành máy nghiền bột giấy và làm giấy','','','','8171',''),
	 ('Thợ vận hành thiết bị chế tạo bột giấy','','','','','81711'),
	 ('Thợ vận hành thiết bị chế tạo giấy','','','','','81712'),
	 ('Thợ vận hành thiết bị chế tạo bột giấy và giấy','','','','','81719'),
	 ('Thợ vận hành máy chế biến gỗ','','','','8172','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ cưa','','','','','81721'),
	 ('Thợ vận hành máy cắt','','','','','81722'),
	 ('Thợ sơn lõi ván ép','','','','','81723'),
	 ('Thợ vận hành máy ép ván ép','','','','','81724'),
	 ('Thợ phân loại gỗ','','','','','81725'),
	 ('Thợ vận hành máy chế biến gỗ','','','','','81726'),
	 ('Thợ vận hành máy cưa gỗ chính xác','','','','','81727'),
	 ('Thợ vận hành thiết bị chế biến gỗ khác','','','','','81729'),
	 ('Thợ vận hành máy móc thiết bị khác','','','818','',''),
	 ('Thợ vận hành thiết bị sản xuất thủy tinh và gốm','','','','8181','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ vận hành lò nung thủy tinh/gốm','','','','','81811'),
	 ('Thợ sản xuất sợi thủy tinh','','','','','81812'),
	 ('Thợ vận hành thiết bị sản xuất thủy tinh và gốm','','','','','81819'),
	 ('Thợ vận hành động cơ hơi nước và nồi hơi','','','','8182',''),
	 ('Thợ vận hành động cơ hơi nước','','','','','81821'),
	 ('Thợ đốt lò','','','','','81822'),
	 ('Thợ vận hành động cơ hơi nước và nồi hơi khác','','','','','81829'),
	 ('Thợ vận hành thiết bị đóng gói, đóng chai và dán nhãn','','','','8183','81830'),
	 ('Thợ vận hành máy móc, thiết bị khác chưa được phân vào đâu','','','','8189',''),
	 ('Thợ vận hành máy in, máy đóng sách và máy có liên quan','','','','','81891');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ vận hành máy cắt dây cáp và dây tải điện','','','','','81892'),
	 ('Thợ vận hành máy sản xuất con chip silicon','','','','','81893'),
	 ('Thợ vận hành dây chuyền lắp ráp tự động và vận hành rô bốt công nghiệp','','','','','81894'),
	 ('Thợ vận hành thiết bị khác chưa được phân vào đâu','','','','','81899'),
	 ('Thợ lắp ráp','','82','820','',''),
	 ('Thợ lắp ráp máy cơ khí','','','','8201','82010'),
	 ('Thợ lắp ráp thiết bị điện và điện tử','','','','8202',''),
	 ('Thợ lắp ráp thiết bị điện/linh kiện điện','','','','','82021'),
	 ('Thợ lắp ráp thiết bị điện tử/linh kiện điện tử','','','','','82022'),
	 ('Thợ lắp ráp pin','','','','','82023');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ lắp ráp chưa được phân vào đâu','','','','8209',''),
	 ('Thợ lắp ráp đồ chơi','','','','','82091'),
	 ('Thợ lắp ráp khác chưa được phân vào đâu (lắp ráp sản phẩm nhựa, lắp ráp sản phẩm cao su)','','','','','82099'),
	 ('Lái xe và thợ vận hành thiết bị chuyển động','','83','','',''),
	 ('Lái các phương tiện vận chuyển trên đường ray và các công nhân có liên quan','','','831','',''),
	 ('Lái các phương tiện vận chuyển trên đường ray','','','','8311','83110'),
	 ('Nhân viên điều khiển tín hiệu, bẻ ghi và chuyển hướng tàu hỏa','','','','8312',''),
	 ('Nhân viên điều khiển tín hiệu, bẻ ghi và chuyển hướng tàu hỏa','','','','','83121'),
	 ('Nhân viên đường sắt khác và nhân viên có liên quan','','','','','83129'),
	 ('Lái xe con, xe tải và xe máy','','','832','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Lái xe máy','','','','8321',''),
	 ('Người chở người, chở hàng bằng xe máy (không phải là thư)','','','','','83211'),
	 ('Người chở người, chở hàng bằng xe máy sử dụng các thiết bị di động cá nhân (lái xe máy công nghệ)','','','','','83212'),
	 ('Lái xe con, taxi và xe tải hạng nhẹ','','','','8322',''),
	 ('Lái xe taxi','','','','','83221'),
	 ('Lái xe con','','','','','83222'),
	 ('Lái xe tải hạng nhẹ','','','','','83223'),
	 ('Lái xe cứu thương','','','','','83224'),
	 ('Người trông bãi đỗ xe','','','','','83225'),
	 ('Lái xe con và xe hạng nhẹ khác','','','','','83229');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Lái xe tải hạng vừa, hạng nặng, xe buýt và xe điện','','','833','',''),
	 ('Lái xe buýt và xe điện','','','','8331',''),
	 ('Lái xe buýt','','','','','83311'),
	 ('Lái xe điện','','','','','83312'),
	 ('Lái xe tải hạng vừa và xe tải hạng nặng','','','','8332',''),
	 ('Lái xe tải hạng nặng','','','','','83321'),
	 ('Lái xe tải rơ móoc (bao gồm cả lái xe chính)','','','','','83322'),
	 ('Lái xe cứu hỏa','','','','','83323'),
	 ('Lái thiết bị di động sân bay','','','','','83324'),
	 ('Lái xe tải trộn bê tông','','','','','83325');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Lái xe tải chở chất thải (bao gồm cả xe tải móc với thùng chứa cuộn)','','','','','83326'),
	 ('Lái xe tải hạng vừa và xe tải hạng nặng khác','','','','','83329'),
	 ('Thợ vận hành thiết bị chuyển động','','','834','',''),
	 ('Thợ vận hành thiết bị nông nghiệp và lâm nghiệp','','','','8341','83410'),
	 ('Thợ vận hành máy đào đất và thợ vận hành thiết bị có liên quan','','','','8342',''),
	 ('Thợ vận hành máy đào','','','','','83421'),
	 ('Thợ vận hành máy ủi','','','','','83422'),
	 ('Thợ vận hành máy nạo vét','','','','','83423'),
	 ('Thợ vận hành máy đóng cọc/máy khoan','','','','','83424'),
	 ('Thợ vận hành máy làm đường','','','','','83425');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ vận hành máy đào hầm (kể cả thợ vận hành máy kích ống)','','','','','83426'),
	 ('Thợ vận hành máy đào đất và thợ vận hành thiết bị có liên quan khác','','','','','83429'),
	 ('Thợ vận hành cần trục và thợ vận hành các thiết bị có liên quan','','','','8343',''),
	 ('Thợ vận hành cần trục (chung)','','','','','83431'),
	 ('Thợ vận hành cần trục (hải cảng)','','','','','83432'),
	 ('Thợ vận hành cần trục và thợ vận hành các thiết bị có liên quan khác','','','','','83439'),
	 ('Thợ vận hành xe bốc dỡ','','','','8344',''),
	 ('Thủy thủ trên tàu và những thợ có liên quan (trừ lao động trên tàu đánh bắt thủy sản)','','','835','8350',''),
	 ('Người lái tàu','','','','','83501'),
	 ('Thủy thủ (bao gồm cả người chủ tàu)','','','','','83502');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thủy thủ trên tàu và những thợ có liên quan khác','','','','','83509'),
	 ('Lao động giản đơn','9','','','',''),
	 ('Người quét dọn và giúp việc','','91','','',''),
	 ('Người quét dọn và giúp việc gia đình, khách sạn và văn phòng','','','911','',''),
	 ('Người quét dọn và giúp việc gia đình','','','','9111',''),
	 ('Người giúp việc gia đình (chung)','','','','','91111'),
	 ('Người quét dọn và giúp việc gia đình khác','','','','','91119'),
	 ('Người quét dọn và giúp việc trong văn phòng, khách sạn và các cơ sở khác','','','','9112',''),
	 ('Người dọn dẹp văn phòng','','','','','91121'),
	 ('Người dọn dẹp khách sạn','','','','','91122');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Người dọn dẹp cơ sở công nghiệp','','','','','91123'),
	 ('Người dọn dẹp cơ sở thực phẩm và đồ uống (như nhà hàng, trung tâm bán hàng rong)','','','','','91124'),
	 ('Người dọn dẹp khu dân cư (như chung cư, căn hộ riêng, khu vực chung trong khu dân cư)','','','','','91125'),
	 ('Người dọn dẹp khu vực công cộng (như trạm dừng xe buýt, đường sắt, cống rãnh, cầu trên cao, đường giao thông, đường cao tốc, công viên, bãi biển)','','','','','91126'),
	 ('Người dọn dẹp các phương tiện (như máy bay, tàu hỏa, tàu điện ngầm)','','','','','91127'),
	 ('Người dọn dẹp ở các cơ sở khác (như trung tâm mua sắm, trường học, bệnh viện, những nơi thờ tự)','','','','','91129'),
	 ('Thợ rửa xe cộ, làm sạch cửa sổ, giặt là và những người làm công việc dọn dẹp bằng tay khác','','','912','',''),
	 ('Thợ giặt là bằng tay','','','','9121','91210'),
	 ('Thợ rửa xe cộ','','','','9122','91220'),
	 ('Thợ làm sạch cửa sổ','','','','9123','91230');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Thợ lau dọn khác','','','','9129',''),
	 ('Lao động giản đơn trong nông nghiệp, lâm nghiệp và thủy sản','','92','920','',''),
	 ('Lao động trồng trọt','','','','9201','92010'),
	 ('Lao động chăn nuôi','','','','9202','92020'),
	 ('Lao động trồng trọt và chăn nuôi hỗn hợp','','','','9203','92030'),
	 ('Lao động làm vườn','','','','9204','92040'),
	 ('Lao động lâm nghiệp','','','','9205','92050'),
	 ('Lao động thủy sản','','','','9206',''),
	 ('Lao động nuôi trồng thủy sản','','','','','92061'),
	 ('Lao động khai thác thủy sản trong nội địa','','','','','92062');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Lao động khai thác thủy sản trong vùng biển Việt Nam','','','','','92063'),
	 ('Lao động trong ngành khai khoáng, xây dựng, công nghiệp chế biến, chế tạo và giao thông vận tải','','93','','',''),
	 ('Lao động trong ngành khai khoáng và xây dựng','','','931','',''),
	 ('Lao động trong khai thác mỏ và khai thác đá','','','','9311','93110'),
	 ('Lao động trong xây dựng công trình kỹ thuật (không phải nhà)','','','','9312','93120'),
	 ('Thợ phụ xây dựng','','','','9313','93130'),
	 ('Lao động trong công nghiệp','','','932','',''),
	 ('Lao động đóng gói thủ công','','','','9321','93210'),
	 ('Lao động công nghiệp khác chưa được phân vào đâu','','','','9329','93290'),
	 ('Lao động vận chuyển và kho hàng','','','933','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Lái xe bằng tay và đạp chân','','','','9331','93310'),
	 ('Người điều khiển máy kéo và phương tiện do gia súc kéo','','','','9332','93320'),
	 ('Người mang vác hàng','','','','9333',''),
	 ('Người mang vác hàng hóa xuống tàu và lên bờ','','','','','93331'),
	 ('Người mang vác đường sắt/đường bộ','','','','','93332'),
	 ('Người bốc xếp máy bay (như hành lý sân bay/xử lý hàng hóa)','','','','','93333'),
	 ('Người bốc xếp tại kho','','','','','93334'),
	 ('Người phục vụ xe vận chuyển hàng hóa','','','','','93335'),
	 ('Người đẩy hàng','','','','','93336'),
	 ('Người buộc dây hàng hóa','','','','','93337');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Người mang vác hàng khác','','','','','93339'),
	 ('Người bày hàng lên giá','','','','9334','93340'),
	 ('Người phụ giúp chuẩn bị thực phẩm','','94','940','',''),
	 ('Người chuẩn bị đồ ăn nhanh','','','','9401','94010'),
	 ('Người phụ bếp','','','','9402','94020'),
	 ('Lao động trên đường phố và lao động có liên quan đến bán hàng','','95','','',''),
	 ('Lao động trên đường phố và lao động có liên quan','','','951','9510','95100'),
	 ('Người bán hàng rong trên đường phố (trừ đồ ăn)','','','952','9520','95200'),
	 ('Người thu dọn vật thải và lao động giản đơn khác','','96','','',''),
	 ('Người thu dọn vật thải','','','961','','');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Người thu gom rác và tái chế','','','','9611','96110'),
	 ('Người thu dọn, sắp xếp, phân loại rác','','','','9612','96120'),
	 ('Người quét dọn và lao động khác có liên quan','','','','9613','96130'),
	 ('Lao động giản đơn khác','','','962','',''),
	 ('Người đưa thư, người giao hàng và người khuân vác hành lý','','','','9621',''),
	 ('Người đưa thư','','','','','96211'),
	 ('Người giao hàng','','','','','96212'),
	 ('Người khuân vác ở khách sạn','','','','','96213'),
	 ('Người khuân vác (trừ khách sạn)','','','','','96214'),
	 ('Người làm công việc lặt vặt','','','','9622','96220');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Người đọc đồng hồ đo và người thu tiền từ máy bán hàng tự động','','','','9623','96230'),
	 ('Người thu gom nước và củi','','','','9624','96240'),
	 ('Lao động giản đơn khác chưa được phân vào đâu','','','','9629','96290'),
	 ('Lực lượng vũ trang','0','','','',''),
	 ('Lực lượng quân đội','','01','','',''),
	 ('Sĩ quan','','','011','0110','01100'),
	 ('Hạ sĩ quan, binh sĩ','','','012','0120','01200'),
	 ('Lực lượng khác trong quân đội','','','013','0130','01300'),
	 ('Lực lượng công an','','02','','',''),
	 ('Sĩ quan','','','021','0210','02100');
INSERT INTO public.business_registration_industry (activity_name,level1,level2,level3,level4,level5) VALUES
	 ('Hạ sĩ quan, chiến sĩ','','','022','0220','02200'),
	 ('Lực lượng khác trong công an','','','023','0230','02300'),
	 ('Cơ yếu và lực lượng vũ trang khác','','03','','',''),
	 ('Cơ yếu','','','031','0310','03100'),
	 ('Lực lượng vũ trang khác','','','032','0320','03200'),
	 ('Lãnh đạo, quản lý trong các ngành, các cấp và các đơn vị','1','','','','');
