--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

-- Started on 2024-05-23 19:39:14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 244 (class 1259 OID 182108)
-- Name: business_registration_businessprocessstep; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.business_registration_businessprocessstep (
    id bigint NOT NULL,
    step_name character varying(255) NOT NULL,
    step_order integer NOT NULL,
    step_description text NOT NULL,
    business_type_status_id bigint NOT NULL
);


ALTER TABLE public.business_registration_businessprocessstep OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 182113)
-- Name: business_registration_businessprocessstep_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.business_registration_businessprocessstep ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_registration_businessprocessstep_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 182114)
-- Name: business_registration_businessstatuschange; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.business_registration_businessstatuschange (
    id bigint NOT NULL,
    old_status character varying(5) NOT NULL,
    new_status character varying(5) NOT NULL,
    change_date date NOT NULL,
    business_id bigint NOT NULL
);


ALTER TABLE public.business_registration_businessstatuschange OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 182117)
-- Name: business_registration_businessstatuschange_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.business_registration_businessstatuschange ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_registration_businessstatuschange_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 182118)
-- Name: business_registration_businesstype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.business_registration_businesstype (
    id bigint NOT NULL,
    type_description character varying(255) NOT NULL
);


ALTER TABLE public.business_registration_businesstype OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 182121)
-- Name: business_registration_businesstype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.business_registration_businesstype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_registration_businesstype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 182122)
-- Name: business_registration_businesstypestatus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.business_registration_businesstypestatus (
    id bigint NOT NULL,
    status character varying(5) NOT NULL,
    business_type_id bigint NOT NULL,
    description character varying
);


ALTER TABLE public.business_registration_businesstypestatus OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 182125)
-- Name: business_registration_businesstypestatus_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.business_registration_businesstypestatus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_registration_businesstypestatus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5009 (class 0 OID 182108)
-- Dependencies: 244
-- Data for Name: business_registration_businessprocessstep; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.business_registration_businessprocessstep (id, step_name, step_order, step_description, business_type_status_id) FROM stdin;
70	Trường hợp 1: Đăng ký giải thể doanh nghiệp	1	Nội dung\n\nĐăng ký giải thể doanh nghiệp (trường hợp quy định tại các điểm a, b và c khoản 1 Điều 207 Luật Doanh nghiệp)\nBước 1: Thông báo tình trạng doanh nghiệp đang làm thủ tục giải thể trên Cổng thông tin quốc gia về đăng ký doanh nghiệp\nA. Thành phần hồ sơ:\n1. Thông báo về giải thể doanh nghiệp;\n2. Nghị quyết, quyết định và bản sao biên bản họp của Hội đồng thành viên đối với công ty hợp danh về việc giải thể doanh nghiệp;\n3. Phương án giải quyết nợ (nếu có).\n\n* Doanh nghiệp lưu ý: Sau khi thông tin doanh nghiệp trong Cơ sở dữ liệu quốc gia về đăng ký doanh nghiệp sang tình trạng đang làm thủ tục giải thể: Doanh nghiệp thực hiện thủ tục hoàn thành nghĩa vụ thuế với Cơ quan thuế theo quy định của Luật Quản lý thuế.\n\nBiểu mẫu Phụ lục II-22 THÔNG BÁO VỀ VIỆC GIẢI THỂ DOANH NGHIỆP\n\n\nBước 2: Nộp hồ sơ đăng ký giải thể doanh nghiệp\nA. Thành phần hồ sơ:\n1. Thông báo về giải thể doanh nghiệp (theo mẫu quy định);\n2. Báo cáo thanh lý tài sản doanh nghiệp; danh sách chủ nợ và số nợ đã thanh toán, gồm cả thanh toán hết các khoản nợ về thuế và nợ tiền đóng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp cho người lao động sau khi quyết định giải thể doanh nghiệp (nếu có).\n\n(Doanh nghiệp lưu ý: Đối với doanh nghiệp sử dụng con dấu do cơ quan công an cấp, doanh nghiệp có trách nhiệm trả con dấu, Giấy chứng nhận đã đăng ký mẫu con dấu cho cơ quan công an theo quy định khi làm thủ tục giải thể.)\n\nBiểu mẫu Phụ lục II-22 THÔNG BÁO VỀ VIỆC GIẢI THỂ DOANH NGHIỆP\n\r\n	27
2	Trường hợp 1: Đăng ký thay đổi nội dung đăng ký hộ kinh doanh	1	Thành phần hồ sơ:\n\n- Thông báo thay đổi nội dung đăng ký hộ kinh doanh do chủ hộ kinh doanh ký;\n\n- Bản sao biên bản họp thành viên hộ gia đình về việc đăng ký thay đổi nội dung đăng ký hộ kinh doanh đối với trường hợp các thành viên hộ gia đình đăng ký hộ kinh doanh.\n\nBiểu mẫu: Phụ lục III-2 Thông báo về việc thay đổi nội dung đăng ký hộ kinh doanh.\n\r\n	33
3	Trường hợp 2: Đăng ký thay đổi chủ hộ kinh doanh	2	Thành phần hồ sơ:\n\n- Thông báo thay đổi chủ hộ kinh doanh do chủ hộ kinh doanh cũ và chủ hộ kinh doanh mới ký hoặc do chủ hộ kinh doanh mới ký trong trường hợp thay đổi chủ hộ kinh doanh do thừa kế;\n\n- Hợp đồng mua bán hoặc các giấy tờ chứng minh hoàn tất việc mua bán trong trường hợp bán hộ kinh doanh; hợp đồng tặng cho đối với trường hợp tặng cho hộ kinh doanh; bản sao văn bản xác nhận quyền thừa kế hợp pháp của người thừa kế trong trường hợp thay đổi chủ hộ kinh doanh do thừa kế;\n\n- Bản sao biên bản họp thành viên hộ gia đình về việc thay đổi chủ hộ kinh doanh đối với trường hợp các thành viên hộ gia đình đăng ký hộ kinh doanh;\n\n- Bản sao văn bản ủy quyền của thành viên hộ gia đình cho một thành viên làm chủ hộ kinh doanh đối với trường hợp các thành viên hộ gia đình đăng ký hộ kinh doanh.\n\nLưu ý: Sau khi bán, tặng cho, thừa kế hộ kinh doanh, hộ kinh doanh vẫn phải chịu trách nhiệm về các khoản nợ và nghĩa vụ tài sản khác của hộ kinh doanh phát sinh trong thời gian trước ngày chuyển giao hộ kinh doanh, trừ trường hợp hộ kinh doanh, người mua, người được tặng cho, người thừa kế và chủ nợ của hộ kinh doanh có thỏa thuận khác.\n\nBiểu mẫu: Phụ lục III-3 Thông báo thay đổi chủ hộ kinh doanh\n\r\n	33
5	Đăng ký chấm dứt hoạt động đăng ký kinh doanh	1	Hộ kinh doanh phải gửi thông báo về việc chấm dứt hoạt động hộ kinh doanh đến Cơ quan đăng ký kinh doanh cấp huyện nơi đã đăng ký.\n\nThành phần hồ sơ:\n\n- Thông báo về việc chấm dứt hiệu lực mã số thuế của Cơ quan thuế;\n\n- Bản sao biên bản họp thành viên hộ gia đình về việc chấm dứt hoạt động hộ kinh doanh đối với trường hợp các thành viên hộ gia đình đăng ký hộ kinh doanh;\n\n- Bản gốc Giấy chứng nhận đăng ký hộ kinh doanh.\n\nBiểu mẫu:\n\nPhụ lục III-5 Thông báo về việc chấm dứt hoạt động hộ kinh doanh\r\n	1
12	Trường hợp 1: Đăng ký doanh nghiệp đối với công ty trách nhiệm hữu hạn một thành viên được thành lập trên cơ sở tách công ty	1	Nội dung\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\nb) Giấy tờ pháp lý của cá nhân đối với chủ sở hữu công ty là cá nhân; Giấy tờ pháp lý của tổ chức đối với chủ sở hữu công ty là tổ chức (trừ trường hợp chủ sở hữu công ty là Nhà nước); Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền và văn bản cử người đại diện theo ủy quyền.\nĐối với chủ sở hữu công ty là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\nc) Giấy chứng nhận đăng ký đầu tư đối với trường hợp doanh nghiệp được thành lập bởi nhà đầu tư nước ngoài hoặc tổ chức kinh tế có vốn đầu tư nước ngoài theo quy định tại Luật Đầu tư và các văn bản hướng dẫn thi hành.\n4. Nghị quyết, quyết định của công ty bị tách về việc tách công ty theo quy định tại Điều 199 Luật Doanh nghiệp;\n5. Bản sao biên bản họp Hội đồng thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên (của công ty bị tách), của Đại hội đồng cổ đông (của công ty bị tách) đối với công ty cổ phần về việc tách công ty.\n\r\n	8
8	Đăng ký địa điểm kinh doanh - Hộ kinh doanh	1	Thành phần hồ sơ:\n\nGiấy đề nghị đăng ký hộ kinh doanh;\n\nBiểu mẫu:\n\nPhụ lục III-1 Giấy đề nghị đăng ký hộ kinh doanh\r\n	7
11	Trường hợp 3: Đăng ký doanh nghiệp đối với công ty cổ phần được thành lập trên cơ sở chia công ty	3	Nội dung\n\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Danh sách cổ đông sáng lập và danh sách cổ đông là nhà đầu tư nước ngoài đối với công ty cổ phần.\n4. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\nb) Giấy tờ pháp lý của cá nhân đối với cổ đông sáng lập, cổ đông là nhà đầu tư nước ngoài là cá nhân; Giấy tờ pháp lý của tổ chức đối với cổ đông sáng lập, cổ đông là nhà đầu tư nước ngoài là tổ chức; Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền của cổ đông sáng lập, cổ đông là nhà đầu tư nước ngoài là tổ chức và văn bản cử người đại diện theo ủy quyền.\nĐối với cổ đông là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\nc) Giấy chứng nhận đăng ký đầu tư đối với trường hợp doanh nghiệp được thành lập hoặc tham gia thành lập bởi nhà đầu tư nước ngoài hoặc tổ chức kinh tế có vốn đầu tư nước ngoài theo quy định tại Luật Đầu tư và các văn bản hướng dẫn thi hành.\n5. Nghị quyết, quyết định của công ty bị chia về việc chia công ty theo quy định tại Điều 198 Luật Doanh nghiệp;\n6. Bản sao biên bản họp Hội đồng thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên (của công ty bị chia), của Đại hội đồng cổ đông đối với công ty cổ phần (của công ty bị chia) về việc chia công ty.\n\r\n	8
19	Trường hợp 2: Chuyển đổi công ty cổ phần thành công ty TNHH một thành viên	2	1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\nb) Giấy tờ pháp lý của cá nhân đối với chủ sở hữu công ty là cá nhân; Giấy tờ pháp lý của tổ chức đối với chủ sở hữu công ty là tổ chức (trừ trường hợp chủ sở hữu công ty là Nhà nước); Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền và văn bản cử người đại diện theo ủy quyền.\nĐối với chủ sở hữu công ty là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\n4. Nghị quyết, quyết định và bản sao biên bản họp của Đại hội đồng cổ đông về việc chuyển đổi công ty;\n5. Hợp đồng chuyển nhượng hoặc các giấy tờ chứng minh hoàn tất việc chuyển nhượng trong trường hợp chuyển nhượng cổ phần; Hợp đồng tặng cho trong trường hợp tặng cho cổ phần; Bản sao văn bản xác nhận quyền thừa kế hợp pháp của người thừa kế trong trường hợp thừa kế theo quy định của pháp luật;\n6. Giấy tờ xác nhận việc góp vốn của thành viên, cổ đông mới;\n7. Văn bản của Cơ quan đăng ký đầu tư chấp thuận về việc góp vốn, mua cổ phần, mua phần vốn góp của nhà đầu tư nước ngoài, tổ chức kinh tế có vốn đầu tư nước ngoài đối với trường hợp phải thực hiện thủ tục đăng ký góp vốn, mua cổ phần, mua phần vốn góp theo quy định của Luật Đầu tư.\n \n\nBiểu mẫu\n\nPhụ lục I-2 GIẤY ĐỀ NGHỊ ĐĂNG KÝ CÔNG TY TNHH MỘT THÀNH VIÊN\r\n	4
22	Bước 2: Chuẩn bị hồ sơ	2	Thành phần hồ sơ, bao gồm: \n\nNội dung\n\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Danh sách cổ đông sáng lập và danh sách cổ đông là nhà đầu tư nước ngoài đối với công ty cổ phần.\n4. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\nb) Giấy tờ pháp lý của cá nhân đối với cổ đông sáng lập, cổ đông là nhà đầu tư nước ngoài là cá nhân; Giấy tờ pháp lý của tổ chức đối với cổ đông sáng lập, cổ đông là nhà đầu tư nước ngoài là tổ chức; Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền của cổ đông sáng lập, cổ đông là nhà đầu tư nước ngoài là tổ chức và văn bản cử người đại diện theo ủy quyền.\nĐối với cổ đông là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\nc) Giấy chứng nhận đăng ký đầu tư đối với trường hợp doanh nghiệp được thành lập hoặc tham gia thành lập bởi nhà đầu tư nước ngoài hoặc tổ chức kinh tế có vốn đầu tư nước ngoài theo quy định tại Luật Đầu tư và các văn bản hướng dẫn thi hành.\n\nBiểu mẫu:\n\n-  Phụ lục I-4 GIẤY ĐỀ NGHỊ ĐĂNG KÝ CÔNG TY CỔ PHẦN (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\n\n-  Phụ lục I-7 DANH SÁCH CỔ ĐÔNG SÁNG LẬP CÔNG TY CỔ PHẦN\n\n- Phụ lục I-8 DANH SÁCH CỔ ĐÔNG LÀ NHÀ ĐẦU TƯ NƯỚC NGOÀI\n\n- Phụ lục I-10 DANH SÁCH NGƯỜI ĐẠI DIỆN THEO PHÁP LUẬT/NGƯỜI ĐẠI DIỆN THEO ỦY QUYỀN\n\n- ĐIỀU LỆ CÔNG TY CỔ PHẦN\r\n	5
24	Trường hợp 1: Đăng ký thay đổi địa chỉ trụ sở chính của công ty cổ phần	1	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký;\n2. Nghị quyết, quyết định và bản sao biên bản họp của Đại hội đồng cổ đông đối với công ty cổ phần về việc chuyển địa chỉ trụ sở chính của doanh nghiệp.\n\nBiểu mẫu:\n\nBIÊN BẢN HỌP THAY ĐỔI CỦA ĐẠI HỘI ĐỒNG CỔ ĐÔNG\n\nQUYẾT ĐỊNH THAY ĐỔI CỦA ĐẠI HỘI ĐỒNG CỔ ĐÔNG\n\nPhụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP\r\n	9
27	Trường hợp 1: Thông báo thay đổi cổ đông là nhà đầu tư nước ngoài	1	Nội dung\n\nThông báo thay đổi cổ đông là nhà đầu tư nước ngoài trong công ty cổ phần chưa niêm yết (theo quy định tại khoản 3 điều 31 luật doanh nghiệp)\n\nA. Thành phần hồ sơ:\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký;\n2. Danh sách cổ đông là nhà đầu tư nước ngoài sau khi đã thay đổi.\nDanh sách cổ đông là nhà đầu tư nước ngoài phải bao gồm chữ ký của cổ đông có giá trị cổ phần thay đổi, không bắt buộc phải có chữ ký của cổ đông có giá trị cổ phần không thay đổi;\n3. Hợp đồng chuyển nhượng cổ phần hoặc các giấy tờ chứng minh việc hoàn tất chuyển nhượng;\n4. Bản sao giấy tờ pháp lý của cá nhân trong trường hợp người nhận chuyển nhượng là cá nhân; bản sao giấy tờ pháp lý của tổ chức, bản sao giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền và bản sao văn bản cử người đại diện theo ủy quyền trong trường hợp người nhận chuyển nhượng là tổ chức.\nĐối với cổ đông là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\n5. Văn bản của Cơ quan đăng ký đầu tư chấp thuận về việc góp vốn, mua cổ phần, mua phần vốn góp của nhà đầu tư nước ngoài, tổ chức kinh tế có vốn đầu tư nước ngoài đối với trường hợp phải thực hiện thủ tục đăng ký góp vốn, mua cổ phần, mua phần vốn góp theo quy định của Luật Đầu tư.\n\nBiểu mẫu:\n\n-  DANH SÁCH CỔ ĐÔNG LÀ NHÀ ĐẦU TƯ NƯỚC NGOÀI\n\n-  HỢP ĐỒNG CHUYỂN NHƯỢNG\n\n- Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP\r\n	10
26	Trường hợp 3: Đăng ký đổi tên doanh nghiệp của công ty cổ phần	3	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký;\n2. Nghị quyết, quyết định và bản sao biên bản họp của Đại hội đồng cổ đông đối với công ty cổ phần về việc đổi tên doanh nghiệp.\n\nBiểu mẫu:\n\n- BIÊN BẢN HỌP THAY ĐỔI CỦA ĐẠI HỘI ĐỒNG CỔ ĐÔNG\n\n- QUYẾT ĐỊNH THAY ĐỔI CỦA ĐẠI HỘI ĐỒNG CỔ ĐÔNG\n\n- Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP\r\n	9
28	Trường hợp 2: Thông báo thay đổi ngành, nghề kinh doanh của công ty cổ phần	2	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký;\n2. Nghị quyết, quyết định và bản sao biên bản họp của Đại hội đồng cổ đông đối với công ty cổ phần về việc thay đổi ngành, nghề kinh doanh.\n\nBiểu mẫu:\n\n- BIÊN BẢN HỌP THAY ĐỔI CỦA ĐẠI HỘI ĐỒNG CỔ ĐÔNG\n\n- QUYẾT ĐỊNH THAY ĐỔI CỦA ĐẠI HỘI ĐỒNG CỔ ĐÔNG\n\n- Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP\n\r\n	10
29	Trường hợp 3: Thông báo thay đổi nội dung đăng ký thuế	3	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký.\n\nBiểu mẫu:\n\nPhụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP\n\n \r\n	10
30	Trường hợp 1: Đăng ký tạm ngừng kinh doanh đối với doanh nghiệp	1	Nội dung\n\n1. Thông báo tạm ngừng kinh doanh.\n2. Nghị quyết, quyết định và bản sao biên bản họp của Hội đồng quản trị đối với công ty cổ phần về việc tạm ngừng kinh doanh.\n\nBiểu mẫu:\n\n- Phụ lục II-19 THÔNG BÁO VỀ VIỆC TẠM NGỪNG KINH DOANH - TIIẾP TỤC KINH DOANH TRƯỚC THỜI HẠN ĐÃ THÔNG BÁO\n\n- BIÊN BẢN HỌP TẠM NGỪNG KINH DOANH CỦA HỘI ĐỒNG QUẢN TRỊ\n\n- QUYẾT ĐỊNH TẠM NGỪNG KINH DOANH CỦA HỘI ĐỒNG QUẢN TRỊ\n\r\n	11
34	Bước 1: Nộp hồ sơ	1	Cách thức thực hiện:\n\nNgười thành lập doanh nghiệp hoặc doanh nghiệp hoặc người được ủy quyền thực hiện thủ tục đăng ký doanh nghiệp theo phương thức sau đây:\na) Đăng ký doanh nghiệp trực tiếp tại Phòng Đăng ký kinh doanh;\nb) Đăng ký doanh nghiệp qua dịch vụ bưu chính;\nc) Đăng ký doanh nghiệp qua mạng thông tin điện tử tại Cổng thông tin quốc gia về đăng ký doanh nghiệp (https://dangkykinhdoanh.gov.vn)\n\nSố lượng hồ sơ: 01 bộ hồ sơ\n\nỦy quyền thực hiện thủ tục đăng ký doanh nghiệp\na) Trường hợp ủy quyền cho cá nhân thực hiện thủ tục đăng ký doanh nghiệp, kèm theo hồ sơ đăng ký doanh nghiệp phải có văn bản ủy quyền cho cá nhân thực hiện thủ tục liên quan đến đăng ký doanh nghiệp và bản sao giấy tờ pháp lý của cá nhân được ủy quyền. Văn bản ủy quyền này không bắt buộc phải công chứng, chứng thực.\nb) Trường hợp ủy quyền cho tổ chức thực hiện thủ tục đăng ký doanh nghiệp, kèm theo hồ sơ đăng ký doanh nghiệp phải có bản sao hợp đồng cung cấp dịch vụ với tổ chức làm dịch vụ thực hiện thủ tục liên quan đến đăng ký doanh nghiệp, giấy giới thiệu của tổ chức đó cho cá nhân trực tiếp thực hiện thủ tục liên quan đến đăng ký doanh nghiệp và bản sao giấy tờ pháp lý của cá nhân người được giới thiệu.\nc) Trường hợp ủy quyền cho đơn vị cung cấp dịch vụ bưu chính công ích thực hiện thủ tục đăng ký doanh nghiệp thì khi thực hiện thủ tục đăng ký doanh nghiệp, nhân viên bưu chính phải nộp bản sao phiếu gửi hồ sơ theo mẫu do doanh nghiệp cung ứng dịch vụ bưu chính công ích phát hành có chữ ký xác nhận của nhân viên bưu chính và người có thẩm quyền ký văn bản đề nghị đăng ký doanh nghiệp.\nd) Trường hợp ủy quyền cho đơn vị cung cấp dịch vụ bưu chính không phải là bưu chính công ích thực hiện thủ tục đăng ký doanh nghiệp, kèm theo hồ sơ đăng ký doanh nghiệp phải có bản sao hợp đồng cung cấp dịch vụ với tổ chức làm dịch vụ thực hiện thủ tục liên quan đến đăng ký doanh nghiệp, giấy giới thiệu của tổ chức đó cho cá nhân trực tiếp thực hiện thủ tục liên quan đến đăng ký doanh nghiệp và bản sao giấy tờ pháp lý của cá nhân người được giới thiệu.\n \n\nThời hạn giải quyết:\n\nTrong thời hạn 03 ngày làm việc kể từ ngày nhận hồ sơ, Cơ quan đăng ký kinh doanh có trách nhiệm xem xét tính hợp lệ của hồ sơ đăng ký doanh nghiệp và cấp đăng ký doanh nghiệp; trường hợp hồ sơ chưa hợp lệ, Cơ quan đăng ký kinh doanh phải thông báo bằng văn bản nội dung cần sửa đổi, bổ sung cho người thành lập doanh nghiệp. Trường hợp từ chối đăng ký doanh nghiệp thì phải thông báo bằng văn bản cho người thành lập doanh nghiệp và nêu rõ lý do.\r\n	13
35	Bước 2: Chuẩn bị hồ sơ	2	Thành phần hồ sơ, bao gồm:\n\n1. Giấy đề nghị đăng ký doanh nghiệp.\n\n2. Bản sao giấy tờ pháp lý của cá nhân đối với chủ doanh nghiệp tư nhân.\n\nBiểu mẫu: Phụ lục I-1 GIẤY ĐỀ NGHỊ ĐĂNG KÝ DOANH NGHIỆP TƯ NHÂN (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\n\r\n	13
37	Trường hợp 1: Đăng ký thay đổi địa chỉ trụ sở chính của doanh nghiệp tư nhân	1	Thành phần hồ sơ:\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký.\n\nBiểu mẫu: Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\r\n	14
32	Trường hợp 1: Đăng ký giải thể doanh nghiệp	1	Nội dung\n\nĐăng ký giải thể doanh nghiệp (trường hợp quy định tại các điểm a, b và c khoản 1 Điều 207 Luật Doanh nghiệp)\nBước 1: Thông báo tình trạng doanh nghiệp đang làm thủ tục giải thể trên Cổng thông tin quốc gia về đăng ký doanh nghiệp\nA. Thành phần hồ sơ:\n1. Thông báo về giải thể doanh nghiệp;\n2. Nghị quyết, quyết định và bản sao biên bản họp của Đại hội đồng cổ đông đối với công ty cổ phần về việc giải thể doanh nghiệp;\n3. Phương án giải quyết nợ (nếu có).\n\n* Doanh nghiệp lưu ý: Sau khi thông tin doanh nghiệp trong Cơ sở dữ liệu quốc gia về đăng ký doanh nghiệp sang tình trạng đang làm thủ tục giải thể: Doanh nghiệp thực hiện thủ tục hoàn thành nghĩa vụ thuế với Cơ quan thuế theo quy định của Luật Quản lý thuế.\n\nBiểu mẫu:\n\n- Phụ lục II-22 THÔNG BÁO VỀ VIỆC GIẢI THỂ DOANH NGHIỆP\n\n- BIÊN BẢN HỌP GIẢI THỂ CỦA ĐẠI HỘI ĐỒNG CỔ ĐÔNG\n\n- QUYẾT ĐỊNH GIẢI THỂ CỦA ĐẠI HỘI ĐỒNG CỔ ĐÔNG\n\n \n\nBước 2: Nộp hồ sơ đăng ký giải thể doanh nghiệp\nA. Thành phần hồ sơ:\n1. Thông báo về giải thể doanh nghiệp (theo mẫu quy định);\n2. Báo cáo thanh lý tài sản doanh nghiệp; danh sách chủ nợ và số nợ đã thanh toán, gồm cả thanh toán hết các khoản nợ về thuế và nợ tiền đóng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp cho người lao động sau khi quyết định giải thể doanh nghiệp (nếu có).\n\n(Doanh nghiệp lưu ý: Đối với doanh nghiệp sử dụng con dấu do cơ quan công an cấp, doanh nghiệp có trách nhiệm trả con dấu, Giấy chứng nhận đã đăng ký mẫu con dấu cho cơ quan công an theo quy định khi làm thủ tục giải thể.)\n\nBiểu mẫu: Phụ lục II-22 THÔNG BÁO VỀ VIỆC GIẢI THỂ DOANH NGHIỆP\r\n	12
33	Trường hợp 2: Hủy bỏ nghị quyết, quyết định giải thể doanh nghiệp	2	Nội dung\n\n1. Thông báo về việc hủy bỏ nghị quyết, quyết định giải thể\n2. Nghị quyết, quyết định và bản sao biên bản họp của Đại hội đồng cổ đông đối với công ty cổ phần về việc hủy bỏ nghị quyết, quyết định giải thể doanh nghiệp\n\nBiểu mẫu: Phụ lục II-23 THÔNG BÁO VỀ VIỆC HỦY BỎ NGHỊ QUYẾT QUYẾT ĐỊNH GIẢI THỂ DOANH NGHIỆP\n\r\n	12
39	Trường hợp 3: Đăng ký đổi tên doanh nghiệp của doanh nghiệp tư nhân	3	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký.\n\nBiểu mẫu: Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\r\n	14
40	Trường hợp 1: Thông báo thay đổi ngành, nghề kinh doanh của doanh nghiệp tư nhân	1	Thành phần hồ sơ:\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký.\n\nBiểu mẫu: Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\n\r\n	15
41	Trường hợp 2: Cho thuê doanh nghiệp tư nhân	2	Thành phần hồ sơ:\n\n1. Thông báo cho thuê doanh nghiệp tư nhân;\n\n2. Bản sao hợp đồng cho thuê có công chứng.\n\nBiểu mẫu: Phụ lục II-6 THÔNG BÁO VỀ VIỆC CHO THUÊ DOANH NGHIỆP TƯ NHÂN (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\r\n	15
42	Trường hợp 3: Thay đổi nội dung đăng ký thuế	3	Thành phần hồ sơ:\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký.\n\nBiểu mẫu: Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\r\n	15
43	Trường hợp 1: Đăng ký tạm ngừng kinh doanh đối với doanh nghiệp	1	Nội dung\n\n1. Cách thức thực hiện:\nNgười thành lập doanh nghiệp hoặc doanh nghiệp hoặc người được ủy quyền thực hiện thủ tục đăng ký doanh nghiệp theo phương thức sau đây:\na) Đăng ký doanh nghiệp trực tiếp tại Phòng Đăng ký kinh doanh;\nb) Đăng ký doanh nghiệp qua dịch vụ bưu chính;\nc) Đăng ký doanh nghiệp qua mạng thông tin điện tử tại Cổng thông tin quốc gia về đăng ký doanh nghiệp (https://dangkykinhdoanh.gov.vn)\n\n2. Số lượng hồ sơ: 01 bộ hồ sơ\n\n3. Thành phần hồ sơ:\n\n- Thông báo tạm ngừng kinh doanh.\n\nBiểu mẫu:  Phụ lục II-19 THÔNG BÁO VỀ VIỆC TẠM NGỪNG KINH DOANH - TIIẾP TỤC KINH DOANH TRƯỚC THỜI HẠN ĐÃ THÔNG BÁO (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\n\n4. Thời hạn giải quyết: 03 ngày làm việc kể từ ngày nhận được hồ sơ.\n\n5. Kết quả hồ sơ:\n\n- Nếu hồ sơ hợp lệ: Giấy xác nhận về việc doanh nghiệp đăng ký tạm ngừng kinh doanh\n- Nếu hồ sơ chưa hợp lệ: Thông báo về việc sửa đổi, bổ sung đăng ký doanh nghiệp.\r\n	16
46	Trường hợp 2: Hủy bỏ nghị quyết, quyết định giải thể doanh nghiệp	2	Nội dung\n\n1. Cách thức thực hiện:\nNgười thành lập doanh nghiệp hoặc doanh nghiệp hoặc người được ủy quyền thực hiện thủ tục đăng ký doanh nghiệp theo phương thức sau đây:\na) Đăng ký doanh nghiệp trực tiếp tại Phòng Đăng ký kinh doanh;\nb) Đăng ký doanh nghiệp qua dịch vụ bưu chính;\nc) Đăng ký doanh nghiệp qua mạng thông tin điện tử tại Cổng thông tin quốc gia về đăng ký doanh nghiệp (https://dangkykinhdoanh.gov.vn)\n\n2. Số lượng hồ sơ: 01 bộ hồ sơ\n\n3. Thành phần hồ sơ:\n\n- Thông báo về việc hủy bỏ nghị quyết, quyết định giải thể\n\nBiểu mẫu:  Phụ lục II-23 THÔNG BÁO VỀ VIỆC HỦY BỎ NGHỊ QUYẾT QUYẾT ĐỊNH GIẢI THỂ DOANH NGHIỆP\n\n4. Thời hạn giải quyết: \n\n03 ngày làm việc kể từ ngày nhận được thông báo về việc giải thể doanh nghiệp.\r\n	17
47	Bước 1: Nộp hồ sơ	1	Cách thức thực hiện:\n\nNgười thành lập doanh nghiệp hoặc doanh nghiệp hoặc người được ủy quyền thực hiện thủ tục đăng ký doanh nghiệp theo phương thức sau đây:\na) Đăng ký doanh nghiệp trực tiếp tại Phòng Đăng ký kinh doanh;\nb) Đăng ký doanh nghiệp qua dịch vụ bưu chính;\nc) Đăng ký doanh nghiệp qua mạng thông tin điện tử tại Cổng thông tin quốc gia về đăng ký doanh nghiệp (https://dangkykinhdoanh.gov.vn)\n\nSố lượng hồ sơ: 01 bộ hồ sơ\n\nỦy quyền thực hiện thủ tục đăng ký doanh nghiệp\na) Trường hợp ủy quyền cho cá nhân thực hiện thủ tục đăng ký doanh nghiệp, kèm theo hồ sơ đăng ký doanh nghiệp phải có văn bản ủy quyền cho cá nhân thực hiện thủ tục liên quan đến đăng ký doanh nghiệp và bản sao giấy tờ pháp lý của cá nhân được ủy quyền. Văn bản ủy quyền này không bắt buộc phải công chứng, chứng thực.\nb) Trường hợp ủy quyền cho tổ chức thực hiện thủ tục đăng ký doanh nghiệp, kèm theo hồ sơ đăng ký doanh nghiệp phải có bản sao hợp đồng cung cấp dịch vụ với tổ chức làm dịch vụ thực hiện thủ tục liên quan đến đăng ký doanh nghiệp, giấy giới thiệu của tổ chức đó cho cá nhân trực tiếp thực hiện thủ tục liên quan đến đăng ký doanh nghiệp và bản sao giấy tờ pháp lý của cá nhân người được giới thiệu.\nc) Trường hợp ủy quyền cho đơn vị cung cấp dịch vụ bưu chính công ích thực hiện thủ tục đăng ký doanh nghiệp thì khi thực hiện thủ tục đăng ký doanh nghiệp, nhân viên bưu chính phải nộp bản sao phiếu gửi hồ sơ theo mẫu do doanh nghiệp cung ứng dịch vụ bưu chính công ích phát hành có chữ ký xác nhận của nhân viên bưu chính và người có thẩm quyền ký văn bản đề nghị đăng ký doanh nghiệp.\nd) Trường hợp ủy quyền cho đơn vị cung cấp dịch vụ bưu chính không phải là bưu chính công ích thực hiện thủ tục đăng ký doanh nghiệp, kèm theo hồ sơ đăng ký doanh nghiệp phải có bản sao hợp đồng cung cấp dịch vụ với tổ chức làm dịch vụ thực hiện thủ tục liên quan đến đăng ký doanh nghiệp, giấy giới thiệu của tổ chức đó cho cá nhân trực tiếp thực hiện thủ tục liên quan đến đăng ký doanh nghiệp và bản sao giấy tờ pháp lý của cá nhân người được giới thiệu.\n \n\nThời hạn giải quyết:\n\nTrong thời hạn 03 ngày làm việc kể từ ngày nhận hồ sơ, Cơ quan đăng ký kinh doanh có trách nhiệm xem xét tính hợp lệ của hồ sơ đăng ký doanh nghiệp và cấp đăng ký doanh nghiệp; trường hợp hồ sơ chưa hợp lệ, Cơ quan đăng ký kinh doanh phải thông báo bằng văn bản nội dung cần sửa đổi, bổ sung cho người thành lập doanh nghiệp. Trường hợp từ chối đăng ký doanh nghiệp thì phải thông báo bằng văn bản cho người thành lập doanh nghiệp và nêu rõ lý do.\r\n	18
48	Bước 2: Chuẩn bị hồ sơ	2	Thành phần hồ sơ, bao gồm: \n\n1. Giấy đề nghị đăng ký doanh nghiệp.\n\n2. Điều lệ công ty.\n\n3. Bản sao các giấy tờ sau đây:\n\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\n\nb) Giấy tờ pháp lý của cá nhân đối với chủ sở hữu công ty là cá nhân; Giấy tờ pháp lý của tổ chức đối với chủ sở hữu công ty là tổ chức (trừ trường hợp chủ sở hữu công ty là Nhà nước); Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền và văn bản cử người đại diện theo ủy quyền.\n\nĐối với chủ sở hữu công ty là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\n\nc) Giấy chứng nhận đăng ký đầu tư đối với trường hợp doanh nghiệp được thành lập bởi nhà đầu tư nước ngoài hoặc tổ chức kinh tế có vốn đầu tư nước ngoài theo quy định tại Luật Đầu tư và các văn bản hướng dẫn thi hành.\n\n\r\n	18
50	Trường hợp 1: Đăng ký thay đổi địa chỉ trụ sở chính của công ty trách nhiệm hữu hạn một thành viên	1	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký;\n2. Nghị quyết, quyết định của chủ sở hữu công ty đối với công ty trách nhiệm hữu hạn một thành viên về việc chuyển địa chỉ trụ sở chính của doanh nghiệp.\n\nBiểu mẫu: QUYẾT ĐỊNH THAY ĐỔI CỦA CHỦ SỞ HỮU\n\n Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\n\r\n	19
52	Trường hợp 3: Đăng ký đổi tên doanh nghiệp của công ty trách nhiệm hữu hạn một thành viên	3	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký;\n2. Nghị quyết, quyết định của chủ sở hữu công ty đối với công ty trách nhiệm hữu hạn một thành viên về việc đổi tên doanh nghiệp.\n\nBiểu mẫu: QUYẾT ĐỊNH THAY ĐỔI CỦA CHỦ SỞ HỮU; Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP\r\n	19
53	Trường hợp 1: Thông báo thay đổi ngành, nghề kinh doanh của công ty trách nhiệm hữu hạn một thành viên	1	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký;\n2. Nghị quyết, quyết định của chủ sở hữu công ty đối với công ty trách nhiệm hữu hạn một thành viên về việc thay đổi ngành, nghề kinh doanh.\n\nBiểu mẫu: QUYẾT ĐỊNH THAY ĐỔI CỦA CHỦ SỞ HỮU, Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP.\n\r\n	20
54	Trường hợp 2: Thông báo thay đổi thông tin người đại diện theo ủy quyền của chủ sở hữu là tổ chức	2	Nội dung\n\n1. Thông báo thay đổi thông tin;\n\nBiểu mẫu: Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\n\r\n	20
55	Trường hợp 3: Thông báo thay đổi nội dung đăng ký thuế	3	Nội dung\n\n1. Thông báo thay đổi thông tin;\n\nBiểu mẫu: Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\n\r\n	20
56	Trường hợp 1: Đăng ký tạm ngừng kinh doanh đối với doanh nghiệp	1	Nội dung\n\n1. Thông báo tạm ngừng kinh doanh.\n2. Nghị quyết, quyết định của chủ sở hữu công ty đối với công ty trách nhiệm hữu hạn một thành viên về việc tạm ngừng kinh doanh.\n\nBiểu mẫu: Phụ lục II-19 THÔNG BÁO VỀ VIỆC TẠM NGỪNG KINH DOANH - TIIẾP TỤC KINH DOANH TRƯỚC THỜI HẠN ĐÃ THÔNG BÁO; QUYẾT ĐỊNH TẠM NGỪNG KINH DOANH CỦA CHỦ SỞ HỮU\n\r\n	21
59	Trường hợp 2: Hủy bỏ nghị quyết, quyết định giải thể doanh nghiệp	2	Nội dung\n\n1. Thông báo về việc hủy bỏ nghị quyết, quyết định giải thể\n2. Nghị quyết, quyết định của chủ sở hữu công ty đối với công ty trách nhiệm hữu hạn một thành viên về việc giải thể doanh nghiệp;\n\nBiểu mẫu: Phụ lục II-23 THÔNG BÁO VỀ VIỆC HỦY BỎ NGHỊ QUYẾT QUYẾT ĐỊNH GIẢI THỂ DOANH NGHIỆP\n\r\n	22
60	Bước 1: Nộp hồ sơ	1	Cách thức thực hiện:\n\nNgười thành lập doanh nghiệp hoặc doanh nghiệp hoặc người được ủy quyền thực hiện thủ tục đăng ký doanh nghiệp theo phương thức sau đây:\na) Đăng ký doanh nghiệp trực tiếp tại Phòng Đăng ký kinh doanh;\nb) Đăng ký doanh nghiệp qua dịch vụ bưu chính;\nc) Đăng ký doanh nghiệp qua mạng thông tin điện tử tại Cổng thông tin quốc gia về đăng ký doanh nghiệp (https://dangkykinhdoanh.gov.vn)\n\nSố lượng hồ sơ: 01 bộ hồ sơ\n\nỦy quyền thực hiện thủ tục đăng ký doanh nghiệp\na) Trường hợp ủy quyền cho cá nhân thực hiện thủ tục đăng ký doanh nghiệp, kèm theo hồ sơ đăng ký doanh nghiệp phải có văn bản ủy quyền cho cá nhân thực hiện thủ tục liên quan đến đăng ký doanh nghiệp và bản sao giấy tờ pháp lý của cá nhân được ủy quyền. Văn bản ủy quyền này không bắt buộc phải công chứng, chứng thực.\nb) Trường hợp ủy quyền cho tổ chức thực hiện thủ tục đăng ký doanh nghiệp, kèm theo hồ sơ đăng ký doanh nghiệp phải có bản sao hợp đồng cung cấp dịch vụ với tổ chức làm dịch vụ thực hiện thủ tục liên quan đến đăng ký doanh nghiệp, giấy giới thiệu của tổ chức đó cho cá nhân trực tiếp thực hiện thủ tục liên quan đến đăng ký doanh nghiệp và bản sao giấy tờ pháp lý của cá nhân người được giới thiệu.\nc) Trường hợp ủy quyền cho đơn vị cung cấp dịch vụ bưu chính công ích thực hiện thủ tục đăng ký doanh nghiệp thì khi thực hiện thủ tục đăng ký doanh nghiệp, nhân viên bưu chính phải nộp bản sao phiếu gửi hồ sơ theo mẫu do doanh nghiệp cung ứng dịch vụ bưu chính công ích phát hành có chữ ký xác nhận của nhân viên bưu chính và người có thẩm quyền ký văn bản đề nghị đăng ký doanh nghiệp.\nd) Trường hợp ủy quyền cho đơn vị cung cấp dịch vụ bưu chính không phải là bưu chính công ích thực hiện thủ tục đăng ký doanh nghiệp, kèm theo hồ sơ đăng ký doanh nghiệp phải có bản sao hợp đồng cung cấp dịch vụ với tổ chức làm dịch vụ thực hiện thủ tục liên quan đến đăng ký doanh nghiệp, giấy giới thiệu của tổ chức đó cho cá nhân trực tiếp thực hiện thủ tục liên quan đến đăng ký doanh nghiệp và bản sao giấy tờ pháp lý của cá nhân người được giới thiệu.\n \n\nThời hạn giải quyết:\n\nTrong thời hạn 03 ngày làm việc kể từ ngày nhận hồ sơ, Cơ quan đăng ký kinh doanh có trách nhiệm xem xét tính hợp lệ của hồ sơ đăng ký doanh nghiệp và cấp đăng ký doanh nghiệp; trường hợp hồ sơ chưa hợp lệ, Cơ quan đăng ký kinh doanh phải thông báo bằng văn bản nội dung cần sửa đổi, bổ sung cho người thành lập doanh nghiệp. Trường hợp từ chối đăng ký doanh nghiệp thì phải thông báo bằng văn bản cho người thành lập doanh nghiệp và nêu rõ lý do.\n\r\n	23
62	Bước 3: Nhận kết quả	3	Trường hợp đăng ký trực tiếp:\n\nTrường hợp nhận đủ hồ sơ hợp lệ, Phòng Đăng ký kinh doanh cấp Giấy chứng nhận đăng ký doanh nghiệp trong thời hạn 03 (ba) ngày làm việc.\nNếu từ chối cấp Giấy chứng nhận đăng ký doanh nghiệp thì Phòng Đăng ký kinh doanh sẽ thông báo cho người thành lập doanh nghiệp biết bằng văn bản trong thời hạn 03 (ba) ngày làm việc.\nLưu ý: Người sử dụng không phải thanh toán lại khi sửa đổi, bổ sung hồ sơ\n\nNgoài ra, nhận biên lai phí, lệ phí (đối với hồ sơ thanh toán phí qua mạng điện tử)\n\n- Đối với hồ sơ có thanh toán phí công bố nội dung đăng ký doanh nghiệp qua mạng điện tử, sau khi hồ sơ được chấp thuận, doanh nghiệp sẽ nhận được email phát hành biên lai điện tử (được gửi về địa chỉ email đã nhập ở bước thanh toán điện tử).\n\n- Trường hợp hồ sơ đăng ký qua mạng không được chấp thuận, người sử dụng sẽ được hoàn phí công bố nội dung đăng ký doanh nghiệp đã nộp theo quy định.\n\nĐường dây hỗ trợ đăng ký qua mạng điện tử:\n\nSố hotline: 19009026\n\nEmail: hotro@dangkykinhdoanh.gov.vn\n\r\n	23
61	Bước 2: Chuẩn bị hồ sơ	2	Nội dung\n\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Danh sách thành viên.\n4. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với thành viên công ty là cá nhân; Giấy tờ pháp lý của tổ chức đối với thành viên công ty là tổ chức; Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền và văn bản cử người đại diện theo ủy quyền.\nĐối với thành viên là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\nb) Giấy chứng nhận đăng ký đầu tư đối với trường hợp doanh nghiệp được thành lập hoặc tham gia thành lập bởi nhà đầu tư nước ngoài hoặc tổ chức kinh tế có vốn đầu tư nước ngoài theo quy định tại Luật Đầu tư và các văn bản hướng dẫn thi hành.\n\nBiểu mẫu: Phụ lục I-5 GIẤY ĐỀ NGHỊ ĐĂNG KÝ CÔNG TY HỢP DANH; Phụ lục I-9 DANH SÁCH THÀNH VIÊN CÔNG TY HỢP DANH\n\r\n	23
63	Trường hợp 1: Đăng ký thay đổi địa chỉ trụ sở chính của công ty hợp danh	1	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký;\n2. Nghị quyết, quyết định và bản sao biên bản họp của Hội đồng thành viên đối với công ty hợp danh về việc chuyển địa chỉ trụ sở chính của doanh nghiệp.\n\nBiểu mẫu: Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP\n\r\n	24
64	Trường hợp 2: Đăng ký đổi tên doanh nghiệp của công ty hợp danh	2	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký;\n2. Nghị quyết, quyết định và bản sao biên bản họp của Hội đồng thành viên đối với công ty hợp danh về việc đổi tên doanh nghiệp.\n\nBiểu mẫu: Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP\n\r\n	24
65	Trường hợp 3: Đăng ký thay đổi thành viên hợp danh	3	Nội dung\n\nĐăng ký thay đổi thành viên hợp danh trong trường hợp chấm dứt tư cách thành viên hợp danh, tiếp nhận thành viên hợp danh mới theo quy định tại Điều 185 và Điều 186 Luật Doanh nghiệp\nA. Thành phần hồ sơ:\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký;\n2. Danh sách thành viên công ty hợp danh quy định tại Điều 25 Luật Doanh nghiệp, trong đó không bao gồm nội dung kê khai về thành viên góp vốn;\n\nBiểu mẫu: Phụ lục I-9 DANH SÁCH THÀNH VIÊN CÔNG TY HỢP DANH;  Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP\n\r\n	24
66	Trường hợp 1: Thông báo thay đổi ngành, nghề kinh doanh của công ty hợp danh	1	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký;\n2. Nghị quyết, quyết định và bản sao biên bản họp của Hội đồng thành viên đối với công ty hợp danh về việc thay đổi ngành, nghề kinh doanh.\n\nBiểu mẫu: Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP\n\r\n	25
67	Trường hợp 2: Thông báo thay đổi nội dung đăng ký thuế	2	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp do người đại diện theo pháp luật của doanh nghiệp ký.\n\nBiểu mẫu: Phụ lục II-1 THÔNG BÁO THAY ĐỔI NỘI DUNG ĐĂNG KÝ DOANH NGHIỆP\n\r\n	25
68	Trường hợp 1: Đăng ký tạm ngừng kinh doanh đối với doanh nghiệp	1	Nội dung\n\n1. Thông báo tạm ngừng kinh doanh.\n2. Nghị quyết, quyết định và bản sao biên bản họp của Hội đồng thành viên đối với công ty hợp danh về việc tạm ngừng kinh doanh.\n\nBiểu mẫu: Phụ lục II-19 THÔNG BÁO VỀ VIỆC TẠM NGỪNG KINH DOANH - TIIẾP TỤC KINH DOANH TRƯỚC THỜI HẠN ĐÃ THÔNG BÁO\n\r\n	26
69	Trường hợp 2: Đăng ký tiếp tục kinh doanh trước thời hạn đã thông báo doanh nghiệp	2	Nội dung\n\nThông báo tiếp tục kinh doanh trước thời hạn đã thông báo.\n\nBiểu mẫu: Phụ lục II-19 THÔNG BÁO VỀ VIỆC TẠM NGỪNG KINH DOANH - TIIẾP TỤC KINH DOANH TRƯỚC THỜI HẠN ĐÃ THÔNG BÁO\n\r\n	26
71	Trường hợp 2: Hủy bỏ nghị quyết, quyết định giải thể doanh nghiệp	2	Nội dung\n\n1. Thông báo về việc hủy bỏ nghị quyết, quyết định giải thể\n2. Nghị quyết, quyết định và bản sao biên bản họp của Hội đồng thành viên đối với công ty hợp danh về việc hủy bỏ nghị quyết, quyết định giải thể doanh nghiệp;\n\nBiểu mẫu Phụ lục II-23 THÔNG BÁO VỀ VIỆC HỦY BỎ NGHỊ QUYẾT QUYẾT ĐỊNH GIẢI THỂ DOANH NGHIỆP	27
72	Thông báo lập địa điểm kinh doanh	1	Nội dung\n\n1. Thông báo lập địa điểm kinh doanh do người đại diện theo pháp luật của doanh nghiệp ký trong trường hợp địa điểm kinh doanh trực thuộc doanh nghiệp hoặc do người đứng đầu chi nhánh ký trong trường hợp địa điểm kinh doanh trực thuộc chi nhánh.\n\n \n\nBiểu mẫu: Phụ lục II-7 THÔNG BÁO VỀ VIỆC ĐĂNG KÝ HOẠT ĐỘNG CHI NHÁNH - VĂN PHÒNG ĐẠI DIỆN - ĐỊA ĐIỂM KINH DOANH.\n\r\n	28
73	Đăng ký thay đổi hoạt động địa điểm đăng ký kinh doanh	1	Nội dung\n\n1. Thông báo thay đổi nội dung đăng ký hoạt động chi nhánh, văn phòng đại diện, địa điểm kinh doanh.\n\nBiểu mẫu: Phụ lục II-9 THÔNG BÁO VỀ VIỆC THAY ĐỔI NỘI DUNG ĐĂNG KÝ HOẠT ĐỘNG CHI NHÁNH - VĂN PHÒNG ĐẠI DIỆN - ĐỊA ĐIỂM KINH DOANH\n\r\n	29
74	Trường hợp 1: Đăng ký tạm ngừng kinh doanh đối với địa điểm kinh doanh	1	Nội dung\n\n1. Thông báo tạm ngừng kinh doanh.\n\nBiểu mẫu: Phụ lục II-19 THÔNG BÁO VỀ VIỆC TẠM NGỪNG KINH DOANH - TIIẾP TỤC KINH DOANH TRƯỚC THỜI HẠN ĐÃ THÔNG BÁO\n\r\n	30
75	Trường hợp 2: Đăng ký tiếp tục kinh doanh trước thời hạn đã thông báo của địa điểm kinh doanh	2	Nội dung\n\nThông báo tiếp tục kinh doanh trước thời hạn đã thông báo.\n\nBiểu mẫu: Phụ lục II-19 THÔNG BÁO VỀ VIỆC TẠM NGỪNG KINH DOANH - TIIẾP TỤC KINH DOANH TRƯỚC THỜI HẠN ĐÃ THÔNG BÁO\n\r\n	30
78	Bước 2: Chuẩn bị hồ sơ	2	Thành phần hồ sơ đăng ký hộ kinh doanh bao gồm:\n\n- Giấy đề nghị đăng ký hộ kinh doanh;\n\n- Giấy tờ pháp lý của cá nhân đối với chủ hộ kinh doanh, thành viên hộ gia đình đăng ký hộ kinh doanh trong trường hợp các thành viên hộ gia đình đăng ký hộ kinh doanh;\n\n- Bản sao biên bản họp thành viên hộ gia đình về việc thành lập hộ kinh doanh trong trường hợp các thành viên hộ gia đình đăng ký hộ kinh doanh;\n\n- Bản sao văn bản ủy quyền của thành viên hộ gia đình cho một thành viên làm chủ hộ kinh doanh đối với trường hợp các thành viên hộ gia đình đăng ký hộ kinh doanh.\n\nBiểu mẫu: Phụ lục III-1 Giấy đề nghị đăng ký hộ kinh doanh\n\r\n	32
79	Bước 3: Nhận kết quả	3	Trường hợp đăng ký trực tiếp:\n\n- Trường hợp nhận đủ hồ sơ hợp lệ, Cơ quan đăng ký kinh doanh cấp huyện cấp Giấy chứng nhận đăng ký hộ kinh doanh trong thời hạn 03 (ba) ngày làm việc.\n\n- Nếu từ chối cấp Giấy chứng nhận đăng ký hộ kinh doanh thì Cơ quan đăng ký kinh doanh cấp huyện sẽ thông báo cho người thành lập hộ kinh doanh, hộ kinh doanh biết bằng văn bản trong thời hạn 03 (ba) ngày làm việc.\n\nTrường hợp đăng ký qua mạng thông tin điện tử:\n\nCơ quan đăng ký kinh doanh cấp huyện trả giấy biên nhận hồ sơ và kết quả giải quyết thủ tục đăng ký hộ kinh doanh cho người nộp hồ sơ qua mạng thông tin điện tử theo quy trình trên hệ thống thông tin về đăng ký hộ kinh doanh.\n\nLưu ý: Lệ phí đăng ký hộ kinh doanh không được hoàn trả cho hộ kinh doanh trong trường hợp hộ kinh doanh không được cấp đăng ký hộ kinh doanh.\n\nĐường dây hỗ trợ đăng ký qua mạng điện tử: Email: congthongtin@dangkykinhdoanh\r\n	32
6	Trường hợp 1: Tạm ngừng kinh doanh từ 30 ngày trở lên	1	Nội dung:\n\nThông báo với Cơ quan đăng ký kinh doanh cấp huyện nơi đã đăng ký kinh doanh và Cơ quan thuế trực tiếp quản lý.\n\nBiểu mẫu:\n\nPhụ lục III-4 Thông báo về việc tạm ngừng kinh doanh/tiếp tục kinh doanh trước thời hạn đã thông báo của hộ kinh doanh.\n\r\n	6
7	Trường hợp 2: Tạm ngừng kinh doanh, tiếp tục kinh doanh trước thời hạn đã thông báo của hộ kinh doanh	2	Nội dung:\n\n- Thông báo tạm ngừng kinh doanh hoặc tiếp tục kinh doanh trước thời hạn đã thông báo;\n\n- Bản sao biên bản họp thành viên hộ gia đình.\n\nBiểu mẫu:\n\nPhụ lục III-4 Thông báo về việc tạm ngừng kinh doanh/tiếp tục kinh doanh trước thời hạn đã thông báo của hộ kinh doanh.\n\r\n	6
76	Chấm dứt hoạt động địa điểm kinh doanh	1	Nội dung\n\n1. Thông báo về việc chấm dứt hoạt động địa điểm kinh doanh.\n\nBiểu mẫu: Phụ lục II-20 THÔNG BÁO VỀ VIỆC CHẤM DỨT HOẠT ĐỘNG CHI NHÁNH - VĂN PHÒNG ĐẠI DIỆN - ĐỊA ĐIỂM KINH DOANH\r\n	31
18	Trường hợp 1: Chuyển đổi công ty cổ phần thành công ty TNHH hai thành viên trở lên	1	Nội dung\n\nHồ sơ đăng ký doanh nghiệp đối với trường hợp chuyển đổi công ty cổ phần thành công ty trách nhiệm hữu hạn hai thành viên trở lên\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Danh sách thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên.\n4. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\nb) Giấy tờ pháp lý của cá nhân đối với thành viên công ty; Giấy tờ pháp lý của tổ chức đối với thành viên là tổ chức; Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền của thành viên là tổ chức và văn bản cử người đại diện theo ủy quyền.\nĐối với thành viên là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\n5. Nghị quyết, quyết định và bản sao biên bản họp của Đại hội đồng cổ đông về việc chuyển đổi công ty;\n6. Hợp đồng chuyển nhượng hoặc các giấy tờ chứng minh hoàn tất việc chuyển nhượng trong trường hợp chuyển nhượng cổ phần; Hợp đồng tặng cho trong trường hợp tặng cho cổ phần; Bản sao văn bản xác nhận quyền thừa kế hợp pháp của người thừa kế trong trường hợp thừa kế theo quy định của pháp luật;\n7. Giấy tờ xác nhận việc góp vốn của thành viên, cổ đông mới;\n8. Văn bản của Cơ quan đăng ký đầu tư chấp thuận về việc góp vốn, mua cổ phần, mua phần vốn góp của nhà đầu tư nước ngoài, tổ chức kinh tế có vốn đầu tư nước ngoài đối với trường hợp phải thực hiện thủ tục đăng ký góp vốn, mua cổ phần, mua phần vốn góp theo quy định của Luật Đầu tư.\n\nBiểu mẫu:\n\nPhụ lục I-3 GIẤY ĐỀ NGHỊ ĐĂNG KÝ CÔNG TY TNHH HAI THÀNH VIÊN TRỞ LÊN\n\nPhụ lục I-6 DANH SÁCH THÀNH VIÊN CÔNG TY TRÁCH NHIỆM HỮU HẠN HAI THÀNH VIÊN TRỞ LÊN\n\r\n	4
1	Bước 1: Nộp hồ sơ	1	Cách thức thực hiện:\n\nNgười thành lập doanh nghiệp hoặc doanh nghiệp hoặc người được ủy quyền thực hiện thủ tục đăng ký doanh nghiệp theo phương thức sau đây:\na) Đăng ký doanh nghiệp trực tiếp tại Phòng Đăng ký kinh doanh;\nb) Đăng ký doanh nghiệp qua dịch vụ bưu chính;\nc) Đăng ký doanh nghiệp qua mạng thông tin điện tử tại Cổng thông tin quốc gia về đăng ký doanh nghiệp (https://dangkykinhdoanh.gov.vn)\n\nSố lượng hồ sơ: 01 bộ hồ sơ\n\nỦy quyền thực hiện thủ tục đăng ký doanh nghiệp\na) Trường hợp ủy quyền cho cá nhân thực hiện thủ tục đăng ký doanh nghiệp, kèm theo hồ sơ đăng ký doanh nghiệp phải có văn bản ủy quyền cho cá nhân thực hiện thủ tục liên quan đến đăng ký doanh nghiệp và bản sao giấy tờ pháp lý của cá nhân được ủy quyền. Văn bản ủy quyền này không bắt buộc phải công chứng, chứng thực.\nb) Trường hợp ủy quyền cho tổ chức thực hiện thủ tục đăng ký doanh nghiệp, kèm theo hồ sơ đăng ký doanh nghiệp phải có bản sao hợp đồng cung cấp dịch vụ với tổ chức làm dịch vụ thực hiện thủ tục liên quan đến đăng ký doanh nghiệp, giấy giới thiệu của tổ chức đó cho cá nhân trực tiếp thực hiện thủ tục liên quan đến đăng ký doanh nghiệp và bản sao giấy tờ pháp lý của cá nhân người được giới thiệu.\nc) Trường hợp ủy quyền cho đơn vị cung cấp dịch vụ bưu chính công ích thực hiện thủ tục đăng ký doanh nghiệp thì khi thực hiện thủ tục đăng ký doanh nghiệp, nhân viên bưu chính phải nộp bản sao phiếu gửi hồ sơ theo mẫu do doanh nghiệp cung ứng dịch vụ bưu chính công ích phát hành có chữ ký xác nhận của nhân viên bưu chính và người có thẩm quyền ký văn bản đề nghị đăng ký doanh nghiệp.\nd) Trường hợp ủy quyền cho đơn vị cung cấp dịch vụ bưu chính không phải là bưu chính công ích thực hiện thủ tục đăng ký doanh nghiệp, kèm theo hồ sơ đăng ký doanh nghiệp phải có bản sao hợp đồng cung cấp dịch vụ với tổ chức làm dịch vụ thực hiện thủ tục liên quan đến đăng ký doanh nghiệp, giấy giới thiệu của tổ chức đó cho cá nhân trực tiếp thực hiện thủ tục liên quan đến đăng ký doanh nghiệp và bản sao giấy tờ pháp lý của cá nhân người được giới thiệu.\n \n\nThời hạn giải quyết:\n\nTrong thời hạn 03 ngày làm việc kể từ ngày nhận hồ sơ, Cơ quan đăng ký kinh doanh có trách nhiệm xem xét tính hợp lệ của hồ sơ đăng ký doanh nghiệp và cấp đăng ký doanh nghiệp; trường hợp hồ sơ chưa hợp lệ, Cơ quan đăng ký kinh doanh phải thông báo bằng văn bản nội dung cần sửa đổi, bổ sung cho người thành lập doanh nghiệp. Trường hợp từ chối đăng ký doanh nghiệp thì phải thông báo bằng văn bản cho người thành lập doanh nghiệp và nêu rõ lý do.\n	5
20	Trường hợp 3: Chuyển đổi công ty TNHH hai thành viên trở lên thành công ty cổ phần	3	Nội dung\n\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Danh sách cổ đông sáng lập và danh sách cổ đông là nhà đầu tư nước ngoài đối với công ty cổ phần.\n4. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\nb) Giấy tờ pháp lý của cá nhân đối với cổ đông sáng lập, cổ đông là nhà đầu tư nước ngoài là cá nhân; Giấy tờ pháp lý của tổ chức đối với cổ đông sáng lập, cổ đông là nhà đầu tư nước ngoài là tổ chức; Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền của cổ đông sáng lập, cổ đông là nhà đầu tư nước ngoài là tổ chức và văn bản cử người đại diện theo ủy quyền.\nĐối với cổ đông là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\n5. Nghị quyết, quyết định và bản sao biên bản họp của Hội đồng thành viên về việc chuyển đổi công ty;\n6. Hợp đồng chuyển nhượng hoặc các giấy tờ chứng minh hoàn tất việc chuyển nhượng trong trường hợp chuyển nhượng phần vốn góp; Hợp đồng tặng cho trong trường hợp tặng cho phần vốn góp; Bản sao văn bản xác nhận quyền thừa kế hợp pháp của người thừa kế trong trường hợp thừa kế theo quy định của pháp luật;\n7. Giấy tờ xác nhận việc góp vốn của thành viên, cổ đông mới;\n8. Văn bản của Cơ quan đăng ký đầu tư chấp thuận về việc góp vốn, mua cổ phần, mua phần vốn góp của nhà đầu tư nước ngoài, tổ chức kinh tế có vốn đầu tư nước ngoài đối với trường hợp phải thực hiện thủ tục đăng ký góp vốn, mua cổ phần, mua phần vốn góp theo quy định của Luật Đầu tư.\n\nBiểu mẫu:\n\nPhụ lục I-4 GIẤY ĐỀ NGHỊ ĐĂNG KÝ CÔNG TY CỔ PHẦN\n\nPhụ lục I-7 DANH SÁCH CỔ ĐÔNG SÁNG LẬP CÔNG TY CỔ PHẦN\n\nPhụ lục I-8 DANH SÁCH CỔ ĐÔNG LÀ NHÀ ĐẦU TƯ NƯỚC NGOÀI\n\r\n	4
36	Bước 3: Nhận kết quả	3	Trường hợp đăng ký trực tiếp:\n\nTrường hợp nhận đủ hồ sơ hợp lệ, Phòng Đăng ký kinh doanh cấp Giấy chứng nhận đăng ký doanh nghiệp trong thời hạn 03 (ba) ngày làm việc.\nNếu từ chối cấp Giấy chứng nhận đăng ký doanh nghiệp thì Phòng Đăng ký kinh doanh sẽ thông báo cho người thành lập doanh nghiệp biết bằng văn bản trong thời hạn 03 (ba) ngày làm việc.\nLưu ý: Người sử dụng không phải thanh toán lại khi sửa đổi, bổ sung hồ sơ\n\nNgoài ra, nhận biên lai phí, lệ phí (đối với hồ sơ thanh toán phí qua mạng điện tử)\n\n- Đối với hồ sơ có thanh toán phí công bố nội dung đăng ký doanh nghiệp qua mạng điện tử, sau khi hồ sơ được chấp thuận, doanh nghiệp sẽ nhận được email phát hành biên lai điện tử (được gửi về địa chỉ email đã nhập ở bước thanh toán điện tử).\n\n- Trường hợp hồ sơ đăng ký qua mạng không được chấp thuận, người sử dụng sẽ được hoàn phí công bố nội dung đăng ký doanh nghiệp đã nộp theo quy định.\n\nĐường dây hỗ trợ đăng ký qua mạng điện tử:\n\nSố hotline: 19009026\n\nEmail: hotro@dangkykinhdoanh.gov.vn\r\n	13
38	Trường hợp 2: Đăng ký thay đổi chủ doanh nghiệp tư nhân	2	Thành phần hồ sơ:\n\n1. Thông báo thay đổi nội dung đăng ký doanh nghiệp có chữ ký của người bán, người tặng cho và người mua, người được tặng cho doanh nghiệp tư nhân đối với trường hợp bán, tặng cho doanh nghiệp tư nhân; chữ ký của người thừa kế đối với trường hợp chủ doanh nghiệp tư nhân chết;\n\n2. Bản sao giấy tờ pháp lý của cá nhân đối với người mua, người được tặng cho doanh nghiệp tư nhân, người thừa kế;\n\n3. Hợp đồng mua bán hoặc các giấy tờ chứng minh hoàn tất việc mua bán trong trường hợp bán doanh nghiệp tư nhân; hợp đồng tặng cho trong trường hợp tặng cho doanh nghiệp tư nhân; bản sao văn bản xác nhận quyền thừa kế hợp pháp của người thừa kế trong trường hợp thừa kế.\n\nBiểu mẫu: Phụ lục II-3 THÔNG BÁO THAY ĐỔI CHỦ DOANH NGHIỆP TƯ NHÂN (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\r\n	14
31	Trường hợp 2: Đăng ký tiếp tục kinh doanh trước thời hạn đã thông báo doanh nghiệp	2	Nội dung\n\nThông báo tiếp tục kinh doanh trước thời hạn đã thông báo.\n\nBiểu mẫu: Phụ lục II-19 THÔNG BÁO VỀ VIỆC TẠM NGỪNG KINH DOANH - TIIẾP TỤC KINH DOANH TRƯỚC THỜI HẠN ĐÃ THÔNG BÁO\r\n	11
44	Trường hợp 2: Đăng ký tiếp tục kinh doanh trước thời hạn đã thông báo doanh nghiệp	2	Thành phần hồ sơ:\n\n- Thông báo tiếp tục kinh doanh trước thời hạn đã thông báo.\n\nBiểu mẫu:  Phụ lục II-19 THÔNG BÁO VỀ VIỆC TẠM NGỪNG KINH DOANH - TIIẾP TỤC KINH DOANH TRƯỚC THỜI HẠN ĐÃ THÔNG BÁO (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\r\n	16
45	Trường hợp 1: Đăng ký giải thể doanh nghiệp	1	Nội dung\n\n1. Cách thức thực hiện:\nNgười thành lập doanh nghiệp hoặc doanh nghiệp hoặc người được ủy quyền thực hiện thủ tục đăng ký doanh nghiệp theo phương thức sau đây:\na) Đăng ký doanh nghiệp trực tiếp tại Phòng Đăng ký kinh doanh;\nb) Đăng ký doanh nghiệp qua dịch vụ bưu chính;\nc) Đăng ký doanh nghiệp qua mạng thông tin điện tử tại Cổng thông tin quốc gia về đăng ký doanh nghiệp (https://dangkykinhdoanh.gov.vn)\n\n2. Số lượng hồ sơ: 01 bộ hồ sơ\n\n3. Thành phần hồ sơ:\n\nĐăng ký giải thể doanh nghiệp (trường hợp quy định tại các điểm a, b và c khoản 1 điều 207 luật doanh nghiệp)\nBước 1: Thông báo tình trạng doanh nghiệp đang làm thủ tục giải thể trên Cổng thông tin quốc gia về đăng ký doanh nghiệp\nA. Thành phần hồ sơ:\n1. Thông báo về giải thể doanh nghiệp;\n2. Phương án giải quyết nợ (nếu có).\n\n* Doanh nghiệp lưu ý: Sau khi thông tin doanh nghiệp trong Cơ sở dữ liệu quốc gia về đăng ký doanh nghiệp sang tình trạng đang làm thủ tục giải thể: Doanh nghiệp thực hiện thủ tục hoàn thành nghĩa vụ thuế với Cơ quan thuế theo quy định của Luật Quản lý thuế.\n\nBiểu mẫu:   Phụ lục II-22 THÔNG BÁO VỀ VIỆC GIẢI THỂ DOANH NGHIỆP; QUYẾT ĐỊNH GIẢI THỂ CỦA CHỦ DOANH NGHIỆP TƯ NHÂN\n\nBước 2: Nộp hồ sơ đăng ký giải thể doanh nghiệp\nA. Thành phần hồ sơ:\n1. Thông báo về giải thể doanh nghiệp (theo mẫu quy định);\n2. Báo cáo thanh lý tài sản doanh nghiệp; danh sách chủ nợ và số nợ đã thanh toán, gồm cả thanh toán hết các khoản nợ về thuế và nợ tiền đóng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp cho người lao động sau khi quyết định giải thể doanh nghiệp (nếu có).\n\n(Doanh nghiệp lưu ý: Đối với doanh nghiệp sử dụng con dấu do cơ quan công an cấp, doanh nghiệp có trách nhiệm trả con dấu, Giấy chứng nhận đã đăng ký mẫu con dấu cho cơ quan công an theo quy định khi làm thủ tục giải thể.)\n\nBiểu mẫu:  Phụ lục II-22 THÔNG BÁO VỀ VIỆC GIẢI THỂ DOANH NGHIỆP\n\n4. Thời hạn giải quyết: \n\n05 ngày làm việc kể từ ngày nhận được thông báo về việc giải thể doanh nghiệp.\n\n5. Kết quả hồ sơ:\n\nBước 1: Thông báo về việc doanh nghiệp đang làm thủ tục giải thể\nBước 2: Thông báo về việc doanh nghiệp giải thể\r\n	17
51	Trường hợp 2: Đăng ký thay đổi người đại diện theo pháp luật của công ty trách nhiệm hữu hạn một thành viên	2	Nội dung\n\n1. Thông báo thay đổi người đại diện theo pháp luật;\n2. Bản sao giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật mới;\n3. Nghị quyết, quyết định của chủ sở hữu công ty đối với công ty trách nhiệm hữu hạn một thành viên về việc thay đổi người đại diện theo pháp luật.\n\n(Doanh nghiệp lưu ý: Người ký thông báo thay đổi người đại diện theo pháp luật là một trong các cá nhân sau đây: Chủ tịch Hội đồng thành viên hoặc Chủ tịch công ty đối với công ty trách nhiệm hữu hạn một thành viên.)\n\nBiểu mẫu: QUYẾT ĐỊNH THAY ĐỔI; Phụ lục II-2 THÔNG BÁO THAY ĐỔI NGƯỜI ĐẠI DIỆN THEO PHÁP LUẬT (Thông tư số 01/2021/TT-BKHĐT hướng dẫn về đăng ký doanh nghiệp)\n\r\n	19
57	Trường hợp 2: Đăng ký tiếp tục kinh doanh trước thời hạn đã thông báo doanh nghiệp	2	Nội dung\n\nThông báo tiếp tục kinh doanh trước thời hạn đã thông báo.\n\nBiểu mẫu: Phụ lục II-19 THÔNG BÁO VỀ VIỆC TẠM NGỪNG KINH DOANH - TIIẾP TỤC KINH DOANH TRƯỚC THỜI HẠN ĐÃ THÔNG BÁO\n\r\n	21
4	Trường hợp 3: Hộ kinh doanh chuyển địa chỉ trụ sở	3	Thành phần hồ sơ phải có bản sao các giấy tờ sau:\n\n- Thông báo thay đổi nội dung đăng ký hộ kinh doanh do chủ hộ kinh doanh ký;\n\n- Bản sao biên bản họp thành viên hộ gia đình về việc đăng ký thay đổi địa chỉ trụ sở đối với trường hợp các thành viên hộ gia đình đăng ký hộ kinh doanh;\n\n- Bản sao giấy tờ pháp lý của cá nhân đối với chủ hộ kinh doanh, thành viên hộ gia đình đăng ký hộ kinh doanh trong trường hợp các thành viên hộ gia đình đăng ký hộ kinh doanh.\n\nLưu ý: Trong thời hạn 03 ngày làm việc kể từ ngày cấp Giấy chứng nhận đăng ký hộ kinh doanh trong trường hợp hộ kinh doanh đăng ký thay đổi địa chỉ trụ sở, Cơ quan đăng ký kinh doanh cấp huyện nơi hộ kinh doanh đặt địa chỉ mới phải thông báo đến Cơ quan đăng ký kinh doanh nơi trước đây hộ kinh doanh đã đăng ký.\n\nBiểu mẫu: Phụ lục III-2 Thông báo về việc thay đổi nội dung đăng ký hộ kinh doanh.\n\r\n	33
77	Bước 1: Nộp hồ sơ	1	Cách thức thực hiện:\n\nNgười thành lập hộ kinh doanh hoặc người được ủy quyền thực hiện thủ tục đăng ký hộ kinh doanh theo phương thức sau đây:\n- Đăng ký hộ kinh doanh trực tiếp tại Cơ quan đăng ký kinh doanh cấp huyện nơi đặt trụ sở hộ kinh doanh;\n- Đăng ký hộ kinh doanh qua mạng thông tin điện tử theo địa chỉ: https://hokinhdoanh.dkkd.gov.vn.\n\nSố lượng hồ sơ: 01 bộ hồ sơ\n\nThời hạn giải quyết:\n\nTrong thời hạn 03 ngày làm việc kể từ ngày nhận hồ sơ, Cơ quan đăng ký kinh doanh cấp huyện có trách nhiệm xem xét tính hợp lệ của hồ sơ đăng ký hộ kinh doanh và cấp đăng ký hộ kinh doanh; trường hợp hồ sơ không hợp lệ, Cơ quan đăng ký kinh doanh cấp huyện phải thông báo bằng văn bản cho người nộp hồ sơ hoặc người thành lập hộ kinh doanh biết. Thông báo phải nêu rõ lý do và các yêu cầu sửa đổi, bổ sung hồ sơ (nếu có). Nếu sau 03 ngày làm việc kể từ ngày nộp hồ sơ đăng ký hộ kinh doanh mà không nhận được Giấy chứng nhận đăng ký hộ kinh doanh hoặc không nhận được thông báo yêu cầu sửa đổi, bổ sung hồ sơ đăng ký hộ kinh doanh thì người thành lập hộ kinh doanh hoặc hộ kinh doanh có quyền khiếu nại, tố cáo theo quy định của pháp luật về khiếu nại, tố cáo.\n\r\n	32
10	Trường hợp 2: Đăng ký doanh nghiệp đối với công ty trách nhiệm hữu hạn hai thành viên trở lên được thành lập trên cơ sở chia công ty	2	Nội dung\n\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Danh sách thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên.\n4. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\nb) Giấy tờ pháp lý của cá nhân đối với thành viên công ty; Giấy tờ pháp lý của tổ chức đối với thành viên là tổ chức; Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền của thành viên là tổ chức và văn bản cử người đại diện theo ủy quyền.\nĐối với thành viên là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\nc) Giấy chứng nhận đăng ký đầu tư đối với trường hợp doanh nghiệp được thành lập hoặc tham gia thành lập bởi nhà đầu tư nước ngoài hoặc tổ chức kinh tế có vốn đầu tư nước ngoài theo quy định tại Luật Đầu tư và các văn bản hướng dẫn thi hành.\n5. Nghị quyết, quyết định của công ty bị chia về việc chia công ty theo quy định tại Điều 198 Luật Doanh nghiệp;\n6. Bản sao biên bản họp Hội đồng thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên (của công ty bị chia), của Đại hội đồng cổ đông đối với công ty cổ phần (của công ty bị chia) về việc chia công ty.\n\r\n	8
15	Trường hợp 1: Đăng ký doanh nghiệp đối với công ty hợp danh được thành lập trên cơ sở hợp nhất công ty	1	Nội dung\n\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Danh sách thành viên.\n4. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với thành viên công ty là cá nhân; Giấy tờ pháp lý của tổ chức đối với thành viên công ty là tổ chức; Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền và văn bản cử người đại diện theo ủy quyền.\nĐối với thành viên là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\nb) Giấy chứng nhận đăng ký đầu tư đối với trường hợp doanh nghiệp được thành lập hoặc tham gia thành lập bởi nhà đầu tư nước ngoài hoặc tổ chức kinh tế có vốn đầu tư nước ngoài theo quy định tại Luật Đầu tư và các văn bản hướng dẫn thi hành.\n5. Hợp đồng hợp nhất theo quy định tại Điều 200 Luật Doanh nghiệp;\n6. Nghị quyết, quyết định về việc thông qua hợp đồng hợp nhất công ty của các công ty bị hợp nhất và bản sao biên bản họp Hội đồng thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên, công ty hợp danh, của Đại hội đồng cổ đông đối với công ty cổ phần về việc thông qua hợp đồng hợp nhất để thành lập công ty mới.\n\r\n	3
23	Bước 3: Nhận kết quả	3	Trường hợp đăng ký trực tiếp:\n\nTrường hợp nhận đủ hồ sơ hợp lệ, Phòng Đăng ký kinh doanh cấp Giấy chứng nhận đăng ký doanh nghiệp trong thời hạn 03 (ba) ngày làm việc.\nNếu từ chối cấp Giấy chứng nhận đăng ký doanh nghiệp thì Phòng Đăng ký kinh doanh sẽ thông báo cho người thành lập doanh nghiệp biết bằng văn bản trong thời hạn 03 (ba) ngày làm việc.\nLưu ý: Người sử dụng không phải thanh toán lại khi sửa đổi, bổ sung hồ sơ\n\nNgoài ra, nhận biên lai phí, lệ phí (đối với hồ sơ thanh toán phí qua mạng điện tử)\n\n- Đối với hồ sơ có thanh toán phí công bố nội dung đăng ký doanh nghiệp qua mạng điện tử, sau khi hồ sơ được chấp thuận, doanh nghiệp sẽ nhận được email phát hành biên lai điện tử (được gửi về địa chỉ email đã nhập ở bước thanh toán điện tử).\n\n- Trường hợp hồ sơ đăng ký qua mạng không được chấp thuận, người sử dụng sẽ được hoàn phí công bố nội dung đăng ký doanh nghiệp đã nộp theo quy định.\n\nĐường dây hỗ trợ đăng ký qua mạng điện tử:\n\nSố hotline: 19009026\n\nEmail: hotro@dangkykinhdoanh.gov.vn\r\n	5
25	Trường hợp 2: Đăng ký thay đổi người đại diện theo pháp luật của công ty cổ phần	2	Nội dung\n1. Thông báo thay đổi người đại diện theo pháp luật;\n2. Bản sao giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật mới;\n3. Nghị quyết và bản sao biên bản họp Đại hội đồng cổ đông đối với công ty cổ phần về việc thay đổi người đại diện theo pháp luật trong trường hợp việc thay đổi người đại diện theo pháp luật làm thay đổi nội dung Điều lệ công ty;\nHoặc Nghị quyết, quyết định và bản sao biên bản họp Hội đồng quản trị đối với công ty cổ phần trong trường hợp việc thay đổi người đại diện theo pháp luật không làm thay đổi nội dung của Điều lệ công ty ngoài nội dung họ, tên, chữ ký của người đại diện theo pháp luật của công ty quy định tại Điều 24 Luật Doanh nghiệp.\n(Doanh nghiệp lưu ý: Người ký thông báo thay đổi người đại diện theo pháp luật là một trong các cá nhân sau đây: Chủ tịch Hội đồng quản trị đối với công ty cổ phần. Trường hợp Chủ tịch Hội đồng quản trị là người đại diện theo pháp luật thì người ký thông báo là Chủ tịch Hội đồng quản trị mới được Hội đồng quản trị bầu)\n\n\n Biểu mẫu:\n\n- BIÊN BẢN HỌP THAY ĐỔI CỦA ĐẠI HỘI ĐỒNG CỔ ĐÔNG\n\n- QUYẾT ĐỊNH THAY ĐỔI CỦA ĐẠI HỘI ĐỒNG CỔ ĐÔNG\n\n- Phụ lục II-2 THÔNG BÁO THAY ĐỔI NGƯỜI ĐẠI DIỆN THEO PHÁP LUẬT\r\n	9
17	Trường hợp 3: Đăng ký doanh nghiệp đối với công ty trách nhiệm hữu hạn hai thành viên trở lên được thành lập trên cơ sở hợp nhất công ty	3	Nội dung\n\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Danh sách thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên.\n4. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\nb) Giấy tờ pháp lý của cá nhân đối với thành viên công ty; Giấy tờ pháp lý của tổ chức đối với thành viên là tổ chức; Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền của thành viên là tổ chức và văn bản cử người đại diện theo ủy quyền.\nĐối với thành viên là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\nc) Giấy chứng nhận đăng ký đầu tư đối với trường hợp doanh nghiệp được thành lập hoặc tham gia thành lập bởi nhà đầu tư nước ngoài hoặc tổ chức kinh tế có vốn đầu tư nước ngoài theo quy định tại Luật Đầu tư và các văn bản hướng dẫn thi hành.\n5. Hợp đồng hợp nhất theo quy định tại Điều 200 Luật Doanh nghiệp;\n6. Nghị quyết, quyết định về việc thông qua hợp đồng hợp nhất công ty của các công ty bị hợp nhất và bản sao biên bản họp Hội đồng thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên, công ty hợp danh, của Đại hội đồng cổ đông đối với công ty cổ phần về việc thông qua hợp đồng hợp nhất để thành lập công ty mới.\n\r\n	3
9	Trường hợp 1: Đăng ký doanh nghiệp đối với công ty trách nhiệm hữu hạn một thành viên được thành lập trên cơ sở chia công ty	1	Nội dung\n\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\nb) Giấy tờ pháp lý của cá nhân đối với chủ sở hữu công ty là cá nhân; Giấy tờ pháp lý của tổ chức đối với chủ sở hữu công ty là tổ chức (trừ trường hợp chủ sở hữu công ty là Nhà nước); Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền và văn bản cử người đại diện theo ủy quyền.\nĐối với chủ sở hữu công ty là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\nc) Giấy chứng nhận đăng ký đầu tư đối với trường hợp doanh nghiệp được thành lập bởi nhà đầu tư nước ngoài hoặc tổ chức kinh tế có vốn đầu tư nước ngoài theo quy định tại Luật Đầu tư và các văn bản hướng dẫn thi hành.\n4. Nghị quyết, quyết định của công ty bị chia về việc chia công ty theo quy định tại Điều 198 Luật Doanh nghiệp;\n5. Bản sao biên bản họp Hội đồng thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên (của công ty bị chia), của Đại hội đồng cổ đông đối với công ty cổ phần (của công ty bị chia) về việc chia công ty.\n\r\n	8
49	Bước 3: Nhận kết quả	3	Trường hợp đăng ký trực tiếp:\n\nTrường hợp nhận đủ hồ sơ hợp lệ, Phòng Đăng ký kinh doanh cấp Giấy chứng nhận đăng ký doanh nghiệp trong thời hạn 03 (ba) ngày làm việc.\nNếu từ chối cấp Giấy chứng nhận đăng ký doanh nghiệp thì Phòng Đăng ký kinh doanh sẽ thông báo cho người thành lập doanh nghiệp biết bằng văn bản trong thời hạn 03 (ba) ngày làm việc.\nLưu ý: Người sử dụng không phải thanh toán lại khi sửa đổi, bổ sung hồ sơ\n\nNgoài ra, nhận biên lai phí, lệ phí (đối với hồ sơ thanh toán phí qua mạng điện tử)\n\n- Đối với hồ sơ có thanh toán phí công bố nội dung đăng ký doanh nghiệp qua mạng điện tử, sau khi hồ sơ được chấp thuận, doanh nghiệp sẽ nhận được email phát hành biên lai điện tử (được gửi về địa chỉ email đã nhập ở bước thanh toán điện tử).\n\n- Trường hợp hồ sơ đăng ký qua mạng không được chấp thuận, người sử dụng sẽ được hoàn phí công bố nội dung đăng ký doanh nghiệp đã nộp theo quy định.\n\nĐường dây hỗ trợ đăng ký qua mạng điện tử:\n\nSố hotline: 19009026\n\nEmail: hotro@dangkykinhdoanh.gov.vn\n\r\n	18
58	Trường hợp 1: Đăng ký giải thể doanh nghiệp	1	Thành phần hồ sơ, bao gồm:\n\nNội dung\n\nĐăng ký giải thể doanh nghiệp (trường hợp quy định tại các điểm a, b và c khoản 1 Điều 207 Luật Doanh nghiệp)\nBước 1: Thông báo tình trạng doanh nghiệp đang làm thủ tục giải thể trên Cổng thông tin quốc gia về đăng ký doanh nghiệp\n\nA. Thành phần hồ sơ:\n1. Thông báo về giải thể doanh nghiệp;\n2. Nghị quyết, quyết định của chủ sở hữu công ty đối với công ty trách nhiệm hữu hạn một thành viên về việc giải thể doanh nghiệp;\n3. Phương án giải quyết nợ (nếu có).\n\n* Doanh nghiệp lưu ý: Sau khi thông tin doanh nghiệp trong Cơ sở dữ liệu quốc gia về đăng ký doanh nghiệp sang tình trạng đang làm thủ tục giải thể: Doanh nghiệp thực hiện thủ tục hoàn thành nghĩa vụ thuế với Cơ quan thuế theo quy định của Luật Quản lý thuế.\n\nBiểu mẫu:\n\n- Phụ lục II-22 THÔNG BÁO VỀ VIỆC GIẢI THỂ DOANH NGHIỆP\n\n- QUYẾT ĐỊNH GIẢI THỂ CỦA CHỦ SỞ HỮU\n\nBước 2: Nộp hồ sơ đăng ký giải thể doanh nghiệp\nB. Thành phần hồ sơ:\n1. Thông báo về giải thể doanh nghiệp (theo mẫu quy định);\n2. Báo cáo thanh lý tài sản doanh nghiệp; danh sách chủ nợ và số nợ đã thanh toán, gồm cả thanh toán hết các khoản nợ về thuế và nợ tiền đóng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp cho người lao động sau khi quyết định giải thể doanh nghiệp (nếu có).\n\n(Doanh nghiệp lưu ý: Đối với doanh nghiệp sử dụng con dấu do cơ quan công an cấp, doanh nghiệp có trách nhiệm trả con dấu, Giấy chứng nhận đã đăng ký mẫu con dấu cho cơ quan công an theo quy định khi làm thủ tục giải thể)\n\nBiểu mẫu: Phụ lục II-22 THÔNG BÁO VỀ VIỆC GIẢI THỂ DOANH NGHIỆP\n\r\n	22
16	Trường hợp 2: Đăng ký doanh nghiệp đối với công ty trách nhiệm hữu hạn một thành viên được thanh lập trên cơ sở hợp nhất công ty	2	Nội dung\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\nb) Giấy tờ pháp lý của cá nhân đối với chủ sở hữu công ty là cá nhân; Giấy tờ pháp lý của tổ chức đối với chủ sở hữu công ty là tổ chức (trừ trường hợp chủ sở hữu công ty là Nhà nước); Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền và văn bản cử người đại diện theo ủy quyền.\nĐối với chủ sở hữu công ty là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\nc) Giấy chứng nhận đăng ký đầu tư đối với trường hợp doanh nghiệp được thành lập bởi nhà đầu tư nước ngoài hoặc tổ chức kinh tế có vốn đầu tư nước ngoài theo quy định tại Luật Đầu tư và các văn bản hướng dẫn thi hành.\n4. Hợp đồng hợp nhất theo quy định tại Điều 200 Luật Doanh nghiệp;\n5. Nghị quyết, quyết định về việc thông qua hợp đồng hợp nhất công ty của các công ty bị hợp nhất và bản sao biên bản họp Hội đồng thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên, công ty hợp danh, của Đại hội đồng cổ đông đối với công ty cổ phần về việc thông qua hợp đồng hợp nhất để thành lập công ty mới.\n\r\n	3
13	Trường hợp 2: Đăng ký doanh nghiệp đối với công ty trách nhiệm hữu hạn hai thành viên trở lên được thành lập trên cơ sở tách công ty	2	Nội dung\n\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Danh sách thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên.\n4. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\nb) Giấy tờ pháp lý của cá nhân đối với thành viên công ty; Giấy tờ pháp lý của tổ chức đối với thành viên là tổ chức; Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền của thành viên là tổ chức và văn bản cử người đại diện theo ủy quyền.\nĐối với thành viên là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\nc) Giấy chứng nhận đăng ký đầu tư đối với trường hợp doanh nghiệp được thành lập hoặc tham gia thành lập bởi nhà đầu tư nước ngoài hoặc tổ chức kinh tế có vốn đầu tư nước ngoài theo quy định tại Luật Đầu tư và các văn bản hướng dẫn thi hành.\n5. Nghị quyết, quyết định của công ty bị tách về việc tách công ty theo quy định tại Điều 199 Luật Doanh nghiệp;\n6. Bản sao biên bản họp Hội đồng thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên (của công ty bị tách), của Đại hội đồng cổ đông (của công ty bị tách) đối với công ty cổ phần về việc tách công ty.\n\r\n	8
14	Trường hợp 3: Đăng ký doanh nghiệp đối với công ty cổ phần được thành lập trên cơ sở tách công ty	3	Nội dung\n\n1. Giấy đề nghị đăng ký doanh nghiệp.\n2. Điều lệ công ty.\n3. Danh sách cổ đông sáng lập và danh sách cổ đông là nhà đầu tư nước ngoài đối với công ty cổ phần.\n4. Bản sao các giấy tờ sau đây:\na) Giấy tờ pháp lý của cá nhân đối với người đại diện theo pháp luật của doanh nghiệp;\nb) Giấy tờ pháp lý của cá nhân đối với cổ đông sáng lập, cổ đông là nhà đầu tư nước ngoài là cá nhân; Giấy tờ pháp lý của tổ chức đối với cổ đông sáng lập, cổ đông là nhà đầu tư nước ngoài là tổ chức; Giấy tờ pháp lý của cá nhân đối với người đại diện theo ủy quyền của cổ đông sáng lập, cổ đông là nhà đầu tư nước ngoài là tổ chức và văn bản cử người đại diện theo ủy quyền.\nĐối với cổ đông là tổ chức nước ngoài thì bản sao giấy tờ pháp lý của tổ chức phải được hợp pháp hóa lãnh sự;\nc) Giấy chứng nhận đăng ký đầu tư đối với trường hợp doanh nghiệp được thành lập hoặc tham gia thành lập bởi nhà đầu tư nước ngoài hoặc tổ chức kinh tế có vốn đầu tư nước ngoài theo quy định tại Luật Đầu tư và các văn bản hướng dẫn thi hành.\n5. Nghị quyết, quyết định của công ty bị tách về việc tách công ty theo quy định tại Điều 199 Luật Doanh nghiệp;\n6. Bản sao biên bản họp Hội đồng thành viên đối với công ty trách nhiệm hữu hạn hai thành viên trở lên (của công ty bị tách), của Đại hội đồng cổ đông (của công ty bị tách) đối với công ty cổ phần về việc tách công ty.\n\r\n	8
\.


--
-- TOC entry 5011 (class 0 OID 182114)
-- Dependencies: 246
-- Data for Name: business_registration_businessstatuschange; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.business_registration_businessstatuschange (id, old_status, new_status, change_date, business_id) FROM stdin;
\.


--
-- TOC entry 5013 (class 0 OID 182118)
-- Dependencies: 248
-- Data for Name: business_registration_businesstype; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.business_registration_businesstype (id, type_description) FROM stdin;
4	Doanh nghiệp tư nhân
7	Công ty hợp danh
1	Công ty cổ phần
2	Công ty TNHH Một Thành Viên
3	Địa điểm kinh doanh
5	Hộ kinh doanh
6	Tổ chức lại doanh nghiệp
\.


--
-- TOC entry 5015 (class 0 OID 182122)
-- Dependencies: 250
-- Data for Name: business_registration_businesstypestatus; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.business_registration_businesstypestatus (id, status, business_type_id, description) FROM stdin;
9	CR	1	\N
10	CN	1	\N
12	DI	1	\N
13	NE	4	\N
14	CR	4	\N
15	CN	4	\N
17	DI	4	\N
18	NE	2	\N
19	CR	2	\N
20	CN	2	\N
22	DI	2	\N
23	NE	7	\N
24	CR	7	\N
25	CN	7	\N
27	DI	7	\N
28	NE	3	\N
29	CR	3	\N
30	TS	3	\N
31	TO	3	\N
32	NE	5	\N
33	CR	5	\N
5	NE	1	\N
1	TO	5	\N
7	BL	5	\N
8	BS	6	\N
3	MG	6	\N
4	BC	6	\N
11	TS	1	\N
16	TS	4	\N
21	TS	2	\N
26	TS	7	\N
6	TS	5	\N
2	BS	6	\N
\.


--
-- TOC entry 5022 (class 0 OID 0)
-- Dependencies: 245
-- Name: business_registration_businessprocessstep_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.business_registration_businessprocessstep_id_seq', 79, true);


--
-- TOC entry 5023 (class 0 OID 0)
-- Dependencies: 247
-- Name: business_registration_businessstatuschange_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.business_registration_businessstatuschange_id_seq', 1, false);


--
-- TOC entry 5024 (class 0 OID 0)
-- Dependencies: 249
-- Name: business_registration_businesstype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.business_registration_businesstype_id_seq', 7, true);


--
-- TOC entry 5025 (class 0 OID 0)
-- Dependencies: 251
-- Name: business_registration_businesstypestatus_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.business_registration_businesstypestatus_id_seq', 33, true);


--
-- TOC entry 4854 (class 2606 OID 182378)
-- Name: business_registration_businessprocessstep business_registration_businessprocessstep_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_registration_businessprocessstep
    ADD CONSTRAINT business_registration_businessprocessstep_pkey PRIMARY KEY (id);


--
-- TOC entry 4857 (class 2606 OID 182380)
-- Name: business_registration_businessstatuschange business_registration_businessstatuschange_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_registration_businessstatuschange
    ADD CONSTRAINT business_registration_businessstatuschange_pkey PRIMARY KEY (id);


--
-- TOC entry 4859 (class 2606 OID 182382)
-- Name: business_registration_businesstype business_registration_businesstype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_registration_businesstype
    ADD CONSTRAINT business_registration_businesstype_pkey PRIMARY KEY (id);


--
-- TOC entry 4862 (class 2606 OID 182384)
-- Name: business_registration_businesstypestatus business_registration_businesstypestatus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_registration_businesstypestatus
    ADD CONSTRAINT business_registration_businesstypestatus_pkey PRIMARY KEY (id);


--
-- TOC entry 4860 (class 1259 OID 182475)
-- Name: business_registration_busi_business_type_id_ff6cb471; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX business_registration_busi_business_type_id_ff6cb471 ON public.business_registration_businesstypestatus USING btree (business_type_id);


--
-- TOC entry 4852 (class 1259 OID 182476)
-- Name: business_registration_busi_business_type_status_id_26f2ba55; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX business_registration_busi_business_type_status_id_26f2ba55 ON public.business_registration_businessprocessstep USING btree (business_type_status_id);


--
-- TOC entry 4855 (class 1259 OID 182487)
-- Name: business_registration_businessstatuschange_business_id_64b327c0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX business_registration_businessstatuschange_business_id_64b327c0 ON public.business_registration_businessstatuschange USING btree (business_id);


--
-- TOC entry 4864 (class 2606 OID 182588)
-- Name: business_registration_businessstatuschange business_registratio_business_id_64b327c0_fk_business_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_registration_businessstatuschange
    ADD CONSTRAINT business_registratio_business_id_64b327c0_fk_business_ FOREIGN KEY (business_id) REFERENCES public.business_registration_business(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4865 (class 2606 OID 182618)
-- Name: business_registration_businesstypestatus business_registratio_business_type_id_ff6cb471_fk_business_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_registration_businesstypestatus
    ADD CONSTRAINT business_registratio_business_type_id_ff6cb471_fk_business_ FOREIGN KEY (business_type_id) REFERENCES public.business_registration_businesstype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4863 (class 2606 OID 182623)
-- Name: business_registration_businessprocessstep business_registratio_business_type_status_26f2ba55_fk_business_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.business_registration_businessprocessstep
    ADD CONSTRAINT business_registratio_business_type_status_26f2ba55_fk_business_ FOREIGN KEY (business_type_status_id) REFERENCES public.business_registration_businesstypestatus(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2024-05-23 19:39:14

--
-- PostgreSQL database dump complete
--

