from django.urls import path, re_path
from . import views

urlpatterns = [
    # path('', views.DashboardView.as_view(), name='dashboard'),
    path('dashboard', views.DashboardView.as_view(), name='dashboard'),
    path('bots', views.BotsView.as_view(), name='bots'),
    path('bot_add', views.AddBotView.as_view(), name='add_bot'),
    path('bot_import', views.ImportBotView.as_view(), name='import_bot'),
    re_path(r'^bot/(?P<bot_id>\d+)$', views.EditBotView.as_view(), name='bot_detail'),
    re_path(r'^bot/(?P<bot_id>\d+)/action/edit/(?P<action_id>\d+)$', views.ActionsView.as_view(), name='edit_action'),
    re_path(r'^bot/(?P<bot_id>\d+)/intent/add$', views.AddIntentView.as_view(), name='add_intent'),
    re_path(r'^bot/(?P<bot_id>\d+)/intent/(?P<intent_id>\d+)$', views.EditIntentView.as_view(), name='edit_intent'),
    re_path(r'^bot/(?P<bot_id>\d+)/stories/$', views.StoriesView.as_view(), name='stories'),
    path('entities', views.EntitiesView.as_view(), name='entities'),
    re_path(r'^bot/(?P<bot_id>\d+)/entity/add$', views.AddEntityView.as_view(), name='add_entity'),
    re_path(r'^bot/(?P<bot_id>\d+)/entity/(?P<entity_id>\d+)$', views.EditEntityView.as_view(), name='edit_entity'),
    re_path(r'^bot/(?P<bot_id>\d+)/regex/add$', views.AddRegexView.as_view(), name='add_regex'),
    re_path(r'^bot/(?P<bot_id>\d+)/regex/(?P<regex_id>\d+)$', views.EditRegexView.as_view(), name='edit_regex'),
    re_path(r'^bot/(?P<bot_id>\d+)/synonym/(?P<synonym_id>\d+)$', views.EditSynonymView.as_view(), name='edit_synonym'),
    re_path(r'^bot/(?P<bot_id>\d+)/synonyms/add$', views.AddSynonymView.as_view(), name='add_synonym'),
    path('rasaconfig', views.RasaConfigView.as_view(), name='rasa_config'),
    path('logs', views.LogsView.as_view(), name='logs'),
    path('history', views.HistoryView.as_view(), name='history'),
    re_path(r'^conversation/(?P<bot_id>\d+)/(?P<user_id>\d+)$', views.ConversationView.as_view(), name='conversation'),
    path('insights', views.InsightsView.as_view(), name='insights'),
    path('training', views.TrainingView.as_view(), name='training'),
    path('settings', views.SettingsView.as_view(), name='settings'),
    re_path(r'^models/(?P<bot_id>\d+)$', views.ModelView.as_view(), name='models'),
    path('models', views.ModelView.as_view(), name='models'),
    re_path(r'^models/(?P<bot_id>\d+)/add$', views.AddModelView.as_view(), name='add_model'),
    # re_path(r'^chat/(?P<bot_id>\d+)$', views.ChatView.as_view(), name='chat'),
    # path('chat', views.ChatView.as_view(), name='chat'),
    path('stories', views.StoriesView.as_view(), name='stories'),
    re_path(r'^stories/(?P<bot_id>\d+)$', views.StoriesView.as_view(), name='stories'),
    path('responses', views.ResponseView.as_view(), name='responses'),
    re_path(r'^responses/(?P<bot_id>\d+)$', views.ResponseView.as_view(), name='responses'),
    re_path(r'^responses/(?P<bot_id>\d+)/add$', views.AddActionView.as_view(), name='add_response'),
    re_path(r'^stories/(?P<bot_id>\d+)$', views.StoriesView.as_view(), name='stories'),
]