# Generated by Django 4.2.9 on 2024-06-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circulars',
            options={'verbose_name': 'Circular', 'verbose_name_plural': 'Circulars'},
        ),
        migrations.AlterModelOptions(
            name='decisions',
            options={'verbose_name': 'Decision', 'verbose_name_plural': 'Decisions'},
        ),
        migrations.AlterModelOptions(
            name='decrees',
            options={'verbose_name': 'Decree', 'verbose_name_plural': 'Decrees'},
        ),
        migrations.AlterModelOptions(
            name='laws',
            options={'verbose_name': 'Law', 'verbose_name_plural': 'Laws'},
        ),
        migrations.AlterField(
            model_name='circulars',
            name='circular_link',
            field=models.CharField(max_length=255, verbose_name='Circular Link'),
        ),
        migrations.AlterField(
            model_name='circulars',
            name='circular_name',
            field=models.TextField(verbose_name='Circular Name'),
        ),
        migrations.AlterField(
            model_name='circulars',
            name='circular_number',
            field=models.CharField(max_length=255, verbose_name='Circular Number'),
        ),
        migrations.AlterField(
            model_name='circulars',
            name='issued_date',
            field=models.DateField(verbose_name='Issued Date'),
        ),
        migrations.AlterField(
            model_name='decisions',
            name='decision_link',
            field=models.CharField(max_length=255, verbose_name='Decision Link'),
        ),
        migrations.AlterField(
            model_name='decisions',
            name='decision_name',
            field=models.TextField(verbose_name='Decision Name'),
        ),
        migrations.AlterField(
            model_name='decisions',
            name='decision_number',
            field=models.CharField(max_length=255, verbose_name='Decision Number'),
        ),
        migrations.AlterField(
            model_name='decisions',
            name='issued_date',
            field=models.DateField(verbose_name='Issued Date'),
        ),
        migrations.AlterField(
            model_name='decrees',
            name='decree_link',
            field=models.CharField(max_length=255, verbose_name='Decree Link'),
        ),
        migrations.AlterField(
            model_name='decrees',
            name='decree_name',
            field=models.TextField(verbose_name='Decree Name'),
        ),
        migrations.AlterField(
            model_name='decrees',
            name='decree_number',
            field=models.CharField(max_length=255, verbose_name='Decree Number'),
        ),
        migrations.AlterField(
            model_name='decrees',
            name='issued_date',
            field=models.DateField(verbose_name='Issued Date'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='issued_date',
            field=models.DateField(verbose_name='Issued Date'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='law_link',
            field=models.CharField(max_length=255, verbose_name='Law Link'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='law_name',
            field=models.TextField(verbose_name='Law Name'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='law_number',
            field=models.CharField(max_length=255, verbose_name='Law Number'),
        ),
    ]
