# Generated by Django 4.2.9 on 2024-01-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circulars',
            fields=[
                ('CircularId', models.IntegerField(primary_key=True, serialize=False)),
                ('CircularNumber', models.CharField(max_length=255)),
                ('IssuedDate', models.DateField()),
                ('CircularName', models.TextField()),
                ('CircularLink', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Decisions',
            fields=[
                ('DecisionId', models.IntegerField(primary_key=True, serialize=False)),
                ('DecisionNumber', models.CharField(max_length=255)),
                ('IssuedDate', models.DateField()),
                ('DecisionName', models.TextField()),
                ('DecisionLink', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Decrees',
            fields=[
                ('DecreeId', models.IntegerField(primary_key=True, serialize=False)),
                ('DecreeNumber', models.CharField(max_length=255)),
                ('IssuedDate', models.DateField()),
                ('DecreeName', models.TextField()),
                ('DecreeLink', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('LawId', models.IntegerField(primary_key=True, serialize=False)),
                ('LawNumber', models.CharField(max_length=255)),
                ('IssuedDate', models.DateField()),
                ('LawName', models.TextField()),
                ('LawLink', models.CharField(max_length=255)),
            ],
        ),
    ]
