# Generated by Django 4.2.9 on 2024-01-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('CompanyID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('CityProvince', models.CharField(max_length=255)),
                ('Capital', models.BigIntegerField()),
                ('Phone', models.CharField(max_length=255)),
                ('LegalRepresentative', models.CharField(max_length=255)),
                ('IssuedDate', models.DateField()),
                ('BusinessType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MainBusinessActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainActivityCode', models.IntegerField()),
                ('MainActivityName', models.CharField(max_length=255)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessRegistration.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Fax', models.CharField(max_length=255)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessRegistration.companies')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeDescription', models.CharField(max_length=255)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessRegistration.companies')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityCode', models.IntegerField()),
                ('ActivityName', models.CharField(max_length=255)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessRegistration.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('CityProvince', models.CharField(max_length=255)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessRegistration.companies')),
            ],
        ),
    ]
