# Generated by Django 5.0.2 on 2024-03-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=200)),
                ('bot_config', models.TextField()),
                ('output_folder', models.CharField(max_length=200)),
            ],
        ),
    ]
