# Generated by Django 4.2.9 on 2024-03-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_chatbot', '0003_remove_action_bot_remove_conversation_bot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
