# Generated by Django 4.2.9 on 2024-01-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0002_auto_20240126_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('NE', 'Mới thành lập'), ('OP', 'Đang hoạt động'), ('DI', 'Đang giải thể'), ('BA', 'Đang phá sản')], default='NE', max_length=2),
        ),
    ]
