# Generated by Django 4.2.9 on 2024-01-26 10:47

import business_registration.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0003_alter_business_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='district',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='business_registration.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='province',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='business_registration.province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='capital',
            field=models.BigIntegerField(validators=[business_registration.models.Business.validate_multiple_of_1000]),
        ),
        migrations.AlterField(
            model_name='business',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='main_industry',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_registration.industry'),
            preserve_default=False,
        ),
    ]
