# Generated by Django 4.2.9 on 2024-02-21 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0005_businesstypestatus_businessstatuschange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalrepresentative',
            name='contact_address',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='ethnicity',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='gender',
            field=models.CharField(default=str, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='id_issuance_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='id_issuance_place',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='id_number',
            field=models.CharField(default=str, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='id_type',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='nationality',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='residence_address',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='contact_address',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='ethnicity',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='gender',
            field=models.CharField(default=str, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='id_issuance_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='id_issuance_place',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='id_number',
            field=models.CharField(default=str, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='id_type',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='nationality',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='residence_address',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
    ]
