# Generated by Django 4.2.9 on 2024-02-22 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0006_legalrepresentative_contact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='legal_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_registration.legalrepresentative'),
        ),
    ]
