# Generated by Django 4.2.9 on 2024-02-23 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0007_alter_business_legal_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_registration.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_registration.province')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_registration.ward')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_registration.address')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_registration.business')),
            ],
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
        migrations.AddField(
            model_name='business',
            name='headquarters_address',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_registration.address'),
            preserve_default=False,
        ),
    ]
