# Generated by Django 4.2.9 on 2024-02-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0009_alter_business_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
