# Generated by Django 4.2.9 on 2024-03-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0011_alter_activityfield_options_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(default=str, max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.CharField(default=int, max_length=20, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.CharField(default=int, max_length=20, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='detail',
            field=models.TextField(blank=True, default=str, verbose_name='Details'),
            preserve_default=False,
        ),
    ]
