# Generated by Django 5.0.2 on 2024-04-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0012_business_address_business_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessowner',
            options={'verbose_name': 'Business Owner', 'verbose_name_plural': 'Chủ sở hữu'},
        ),
        migrations.AlterModelOptions(
            name='businesstype',
            options={'verbose_name': 'Business Type', 'verbose_name_plural': 'Loại hình kinh doanh'},
        ),
        migrations.AlterModelOptions(
            name='businesstypestatus',
            options={'verbose_name': 'Business Type Status', 'verbose_name_plural': 'Trạng thái doanh nghiệp'},
        ),
    ]
