# Generated by Django 5.0.2 on 2024-04-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0013_alter_businessowner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityfield',
            options={'verbose_name': 'Activity Field', 'verbose_name_plural': 'Lĩnh vực hoạt động'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Địa chỉ'},
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Doanh nghiệp'},
        ),
        migrations.AlterModelOptions(
            name='businessactivityfield',
            options={'verbose_name': 'Business Activity Field', 'verbose_name_plural': 'Lĩnh vực kinh doanh'},
        ),
        migrations.AlterModelOptions(
            name='businessaddress',
            options={'verbose_name': 'Business Address', 'verbose_name_plural': 'Địa chỉ doanh nghiệp'},
        ),
        migrations.AlterModelOptions(
            name='businessindustry',
            options={'verbose_name': 'Business Industry', 'verbose_name_plural': 'Ngành nghề kinh doanh'},
        ),
        migrations.AlterModelOptions(
            name='businessprocessstep',
            options={'verbose_name': 'Business Process Step', 'verbose_name_plural': 'Quy trình đăng ký'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Liên hệ'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industry', 'verbose_name_plural': 'Ngành nghề'},
        ),
        migrations.AlterModelOptions(
            name='legalrepresentative',
            options={'verbose_name': 'Legal Representative', 'verbose_name_plural': 'Người đại diện'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner', 'verbose_name_plural': 'Chủ sở hữu'},
        ),
    ]
