# Generated by Django 4.2.9 on 2024-04-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0015_alter_business_options_alter_business_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner', 'verbose_name_plural': 'Thông tin Chủ sở hữu'},
        ),
    ]
