# Generated by Django 4.2.9 on 2024-05-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0016_alter_owner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Doanh nghiệp'},
        ),
    ]
