# Generated by Django 4.2.9 on 2024-05-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0017_alter_business_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='activity_code',
        ),
        migrations.AddField(
            model_name='industry',
            name='level1',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Level 1'),
        ),
        migrations.AddField(
            model_name='industry',
            name='level2',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Level 2'),
        ),
        migrations.AddField(
            model_name='industry',
            name='level3',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Level 3'),
        ),
        migrations.AddField(
            model_name='industry',
            name='level4',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Level 4'),
        ),
        migrations.AddField(
            model_name='industry',
            name='level5',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Level 5'),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(blank=True, choices=[('NE', 'Thành lập mới'), ('OP', 'Đang hoạt động'), ('DI', 'Giải thể'), ('BA', 'Đang phá sản'), ('NR', 'Đăng ký mới'), ('CR', 'Thay đổi đăng ký'), ('CN', 'Thông báo thay đổi'), ('TS', 'Tạm ngừng'), ('OC', 'Trường hợp khác'), ('LD', 'Văn bản pháp luật'), ('TO', 'Chấm dứt hoạt động'), ('BL', 'Thay đổi địa điểm kinh doanh'), ('PE', 'Doanh nghiệp tư nhân'), ('LP', 'Công ty TNHH 1 TV'), ('JS', 'Công ty Cổ phần'), ('MG', 'Hợp nhất doanh nghiệp'), ('BS', 'Chia doanh nghiệp'), ('BC', 'Chuyển đổi loại hình doanh nghiệp'), ('NC', 'Thông báo thay đổi')], default='NE', max_length=5, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='businessindustry',
            name='industry',
            field=models.CharField(max_length=255, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='businessstatuschange',
            name='new_status',
            field=models.CharField(choices=[('NE', 'Thành lập mới'), ('OP', 'Đang hoạt động'), ('DI', 'Giải thể'), ('BA', 'Đang phá sản'), ('NR', 'Đăng ký mới'), ('CR', 'Thay đổi đăng ký'), ('CN', 'Thông báo thay đổi'), ('TS', 'Tạm ngừng'), ('OC', 'Trường hợp khác'), ('LD', 'Văn bản pháp luật'), ('TO', 'Chấm dứt hoạt động'), ('BL', 'Thay đổi địa điểm kinh doanh'), ('PE', 'Doanh nghiệp tư nhân'), ('LP', 'Công ty TNHH 1 TV'), ('JS', 'Công ty Cổ phần'), ('MG', 'Hợp nhất doanh nghiệp'), ('BS', 'Chia doanh nghiệp'), ('BC', 'Chuyển đổi loại hình doanh nghiệp'), ('NC', 'Thông báo thay đổi')], max_length=5, verbose_name='New Status'),
        ),
        migrations.AlterField(
            model_name='businessstatuschange',
            name='old_status',
            field=models.CharField(choices=[('NE', 'Thành lập mới'), ('OP', 'Đang hoạt động'), ('DI', 'Giải thể'), ('BA', 'Đang phá sản'), ('NR', 'Đăng ký mới'), ('CR', 'Thay đổi đăng ký'), ('CN', 'Thông báo thay đổi'), ('TS', 'Tạm ngừng'), ('OC', 'Trường hợp khác'), ('LD', 'Văn bản pháp luật'), ('TO', 'Chấm dứt hoạt động'), ('BL', 'Thay đổi địa điểm kinh doanh'), ('PE', 'Doanh nghiệp tư nhân'), ('LP', 'Công ty TNHH 1 TV'), ('JS', 'Công ty Cổ phần'), ('MG', 'Hợp nhất doanh nghiệp'), ('BS', 'Chia doanh nghiệp'), ('BC', 'Chuyển đổi loại hình doanh nghiệp'), ('NC', 'Thông báo thay đổi')], max_length=5, verbose_name='Old Status'),
        ),
        migrations.AlterField(
            model_name='businesstypestatus',
            name='status',
            field=models.CharField(choices=[('NE', 'Thành lập mới'), ('OP', 'Đang hoạt động'), ('DI', 'Giải thể'), ('BA', 'Đang phá sản'), ('NR', 'Đăng ký mới'), ('CR', 'Thay đổi đăng ký'), ('CN', 'Thông báo thay đổi'), ('TS', 'Tạm ngừng'), ('OC', 'Trường hợp khác'), ('LD', 'Văn bản pháp luật'), ('TO', 'Chấm dứt hoạt động'), ('BL', 'Thay đổi địa điểm kinh doanh'), ('PE', 'Doanh nghiệp tư nhân'), ('LP', 'Công ty TNHH 1 TV'), ('JS', 'Công ty Cổ phần'), ('MG', 'Hợp nhất doanh nghiệp'), ('BS', 'Chia doanh nghiệp'), ('BC', 'Chuyển đổi loại hình doanh nghiệp'), ('NC', 'Thông báo thay đổi')], max_length=5, verbose_name='Status'),
        ),
    ]
