# Generated by Django 4.2.9 on 2024-05-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0018_remove_industry_activity_code_industry_level1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='level1',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Level 1'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='level3',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Level 3'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='level4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Level 4'),
        ),
    ]
