# Generated by Django 4.2.9 on 2024-06-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0019_alter_industry_level1_alter_industry_level3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='address',
        ),
        migrations.AlterField(
            model_name='business',
            name='headquarters_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='business_registration.address', verbose_name='Headquarters Address'),
        ),
        migrations.AlterField(
            model_name='businessstatuschange',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_registration.business', verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='businessstatuschange',
            name='change_date',
            field=models.DateField(auto_now_add=True, verbose_name='Change Date'),
        ),
    ]
