# Generated by Django 4.2.9 on 2024-06-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_registration', '0020_alter_businessstatuschange_business_and_more'),
        ('business_registration', '0021_business_address_alter_business_headquarters_address'),
    ]

    operations = [
    ]
